### ISSUE TITLE
Explicit extern "C" wrapping required when compiling with a C++ compiler

### ISSUE THREAD

**Issue by rodyakin** [libressl-portable/portable#100]
Normally, C++ code can #include C headers without wrapping them into an extern "C" block.  Looking at a couple random library headers on my system, this is achieved by putting this into the header:

#ifdef __cplusplus
extern "C" {
#endif

tls.h does not have this declaration, so C++ code that uses the library has to explicitly wrap the #include directive with an extern "C" declaration.  Would be nice if libressl headers took care of that.

**Comment by busterb** [comment]
I added a patch to do just this in 2.2.0. I just pushed the patch into OpenBSD upstream yesterday. Would you mind checking it out? https://github.com/libressl-portable/openbsd/commit/1ce15562e2e3b7e2fce05ef5072b5a96f04ff80a

**Comment by rodyakin** [comment]
Yep, looks good.  Thank you, Brent!
