### ISSUE TITLE
signing with signigy?

### ISSUE THREAD

**Issue by jungle-boogie** [libressl-portable/portable#101]
Hello,

Just curious: would you consider signing releases with signify or is this out of the scope of portable versions?

Thanks!

**Comment by bob-beck** [comment]
The portable releases are signed with signify. Always have been

**Comment by jungle-boogie** [comment]
Hi Bob,

You're right, I see this now:
https://github.com/libressl-portable/portable/blob/master/libressl.pub

I only looked on the last release announcement:
http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.2.0-relnotes.txt

And I see it's here, too:
http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl.pub

Thanks and sorry for the noise!

**Comment by bob-beck** [comment]
They just also happen to be signed with gpg as well, you can validate a
release with either method.

As a point of trivia, the private keys for each method are not kept with
the same person or even in the same country.. So if there ever were an
issue with one method of validation the other could be used to bootstrap
changing the other.
