### ISSUE TITLE
array initialization syntax for tests/cipher_list.c

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#102]
Hi,
Could you modify tests/cipher_list.c line 149 like this, please ?
<pre>
        uint8_t empty_cipher_bytes[] = {0};
</pre>
Refer to https://github.com/libressl-portable/openbsd/pull/9 .

I've got compilation errors on HP C/aC++ on hp-ux 11i, below.
<pre>
...
  CC       cipher_list.o
"cipher_list.c", line 149: error #2029: expected an expression
        uint8_t empty_cipher_bytes[] = { };
                                         ^
"cipher_list.c", line 149: error #3345: an empty initializer is invalid for an
          array with unspecified bound
        uint8_t empty_cipher_bytes[] = { };
                ^
2 errors detected in the compilation of "cipher_list.c".
</pre>

Thanks.

**Comment by busterb** [comment]
Of course, thanks for pointing it out.

**Comment by bcook-r7** [comment]
I forgot to note that this is fixed now: https://github.com/libressl-portable/openbsd/commit/9ffb52d49977f89ebc2188afca5269a7377217b4

**Comment by kinichiro** [comment]
sure, I confirmed this.
Thanks.
