### ISSUE TITLE
cc: warning 901: unknown option: `-fno-strict-aliasing': on hp-ux C/aC++

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#108]
Hi,

I've got this compilation warning on hp-ux 11i 11.31 with C/aC++ compiler.

<pre>
...
  CC       bio/libcrypto_la-bf_buff.lo
cc: warning 901: unknown option: `-fno-strict-aliasing': use +help for online documentation.
...
</pre>

commit https://github.com/libressl-portable/portable/commit/c1a162d83b12babd697586ede45815f890d7a40e appears to cause this ?

Thanks.

**Comment by busterb** [comment]
Hmm, I was hoping that would be a detectable compiler error instead. Does adding -Werror to the check help?

**Comment by busterb** [comment]
I switched to including compiler-specific flags for vendor AIX and HP-UX compilers. https://github.com/libressl-portable/portable/commit/b9291face3ec7c804b6171857f95594d12384706

Thanks!

**Comment by kinichiro** [comment]
Thanks for this fix.
I saw this worked well.
