### ISSUE TITLE
libressl 2.2.2 breaks unbound 1.5.4

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#120]
This is OSX 10.10.4. 

`>/usr/bin/otool  -L unbound`
unbound:
	/tmp/test/lib/libssl.35.dylib (compatibility version 36.0.0, current version 36.0.0)
	/tmp/test/lib/libcrypto.35.dylib (compatibility version 36.0.0, current version 36.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)`

`> make test`
[...]
[0] did 10000 in 293.084 msec for 34119.911015 encode/sec size 615
737567 checks ok.
./testbound -s
selftest successful
for x in testdata/*.rpl; do echo -n "$x "; if ./testbound -p $x >/dev/null 2>&1; then echo OK; else echo failed; exit 1; fi done
-n testdata/acl.rpl
/bin/sh: line 1: 79823 Segmentation fault: 11  ./testbound -p $x > /dev/null 2>&1
failed
make: *** [test] Error 1

`>./unbound-checkconf /tmp/test/etc/unbound.conf`
`Memory fault`

`>sudo ./unbound -dv`
quits immediately

**Comment by busterb** [comment]
Unbound appears to use the same compatibility function libraries as libressl, e.g. reallocarray and others. When it does autoconfigure checks for reallocarray, it initially just checks if they can be linked, and thus it detects the ones in libcrypto.

After that, it appears to do a check by grepping headers for "LibreSSL" and if it finds the string somewhere, it sets a define to check if the headers exist as well. This seems extraneous and fragile. At any rate, for some reason this grep check is not always reliable, causing unbound to do this in config.log:

```
configure:16614: $? = 0
configure:16616: result: no
configure:16685: checking for LibreSSL
configure:16747: result: no
configure:16752: checking for openssl/conf.h
configure:16752: gcc -c  -g -O2 -flto -D_THREAD_SAFE -pthread  -I/tmp/libressl/include conftest.c >&5
```

Thus, reallocarray ends up with the wrong definition in unbound's build environment for OSes without reallocarray:

```
util/config_file.c:1040:11: warning: cast to 'int *' from smaller integer type 'int'
      [-Wint-to-pointer-cast]
        *avail = (int*)reallocarray(NULL, (size_t)num, sizeof(int));
```

Of course, truncating pointers is bad when the c compiler falls back to the default function definition for reallocarray! Since any library can potentially have reallocarray embedded in it, there is no reason to only check system header definitions when using LibreSSL. I corrected the issue in Unbound with the following diff to its configure script to unconditionally check system headers for defines:

```
$ diff -uw configure.ac.orig configure.ac
--- configure.ac.orig	2015-08-09 17:14:57.000000000 -0700
+++ configure.ac	2015-08-09 17:15:03.000000000 -0700
@@ -566,15 +566,7 @@
 ACX_WITH_SSL
 ACX_LIB_SSL
 AC_MSG_CHECKING([for LibreSSL])
-if grep OPENSSL_VERSION_TEXT $ssldir/include/openssl/opensslv.h | grep "LibreSSL" >/dev/null; then
-	AC_MSG_RESULT([yes])
-	AC_DEFINE([HAVE_LIBRESSL], [1], [Define if we have LibreSSL])
-	# libressl provides these compat functions, but they may also be
-	# declared by the OS in libc.  See if they have been declared.
 	AC_CHECK_DECLS([strlcpy,strlcat,arc4random,arc4random_uniform,reallocarray])
-else
-	AC_MSG_RESULT([no])
-fi
 AC_CHECK_HEADERS([openssl/conf.h],,, [AC_INCLUDES_DEFAULT])
 AC_CHECK_HEADERS([openssl/engine.h],,, [AC_INCLUDES_DEFAULT])
 AC_CHECK_FUNCS([OPENSSL_config EVP_sha1 EVP_sha256 EVP_sha512 FIPS_mode])
@@ -1261,7 +1253,6 @@
 char *strptime(const char *s, const char *format, struct tm *tm);
 #endif

-#ifdef HAVE_LIBRESSL
 #  if !HAVE_DECL_STRLCPY
 size_t strlcpy(char *dst, const char *src, size_t siz);
 #  endif
@@ -1277,7 +1268,6 @@
 #  if !HAVE_DECL_REALLOCARRAY
 void *reallocarray(void *ptr, size_t nmemb, size_t size);
 #  endif
-#endif /* HAVE_LIBRESSL */
 #ifndef HAVE_ARC4RANDOM
 void explicit_bzero(void* buf, size_t len);
 int getentropy(void* buf, size_t len);
```

**Comment by busterb** [comment]
I would suggest referring the Unbound developers to this issue, and that the LibreSSL-specific checks should be removed. It should be safe to check unconditionally if reallocarray and other functions are defined in the system headers, rather than only doing it when LibreSSL is present.

**Comment by busterb** [comment]
BTW, the change that broke this for Unbound is this:

```
#define LIBRESSL_VERSION_TEXT   "LibreSSL 2.2.2"
#define OPENSSL_VERSION_TEXT    LIBRESSL_VERSION_TEXT
```

If an app really must check for LibreSSL, it should build a test program and check if LIBRESSL_VERSION_NUMBER is defined instead.

**Comment by hdatma** [comment]
This is my config for unbound:

config_options="
[...]
	--with-ssl=/opt/share/libressl \
	--enable-checking \
[...]"; 

The resulting log: 

[...]
checking for SSL... found in /opt/share/libressl   <---------------------------
checking for HMAC_CTX_init in -lcrypto... yes
checking for library containing dlopen... none required
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for openssl/rand.h... yes
checking if libssl needs libdl... no
checking for LibreSSL... yes <---------------------------------------------------
checking whether strlcpy is declared... yes
checking whether strlcat is declared... yes
checking whether arc4random is declared... yes
checking whether arc4random_uniform is declared... yes
checking whether reallocarray is declared... no
checking for openssl/conf.h... yes
checking for openssl/engine.h... yes
checking for OPENSSL_config... yes
checking for EVP_sha1... yes
checking for EVP_sha256... yes
checking for EVP_sha512... yes
checking for FIPS_mode... no
checking whether SSL_COMP_get_compression_methods is declared... yes
checking whether sk_SSL_COMP_pop_free is declared... yes
checking for EVP_PKEY_set_type_str... yes
checking for EC_KEY_new... yes
checking if GOST works... no
checking for ECDSA_sign... yes
checking for SHA384_Init... yes
checking whether NID_X9_62_prime256v1 is declared... yes
checking whether NID_secp384r1 is declared... yes
checking if openssl supports SHA2 and ECDSA with EVP... yes
[...]

**Comment by busterb** [comment]
Great. Now do make clean and rebuild so the code is built with the correct
definition of reallocarray. I would still strongly recommend that unbound
remove the unneeded and broken grep from the configuration process. I'll
file an issue on their bugzilla later, if you don't beat me first.

**Comment by hdatma** [comment]
No no, I did not use your patch. 

My configuration shows that unbound detects libressl correctly *if* told where to look for it. 
The original problem still holds. 

`>make clean`
[...]

`>make`
[...]

`>make test`
[0] did 10000 in 274.744 msec for 36397.519145 encode/sec size 615
737299 checks ok.
./testbound -s
selftest successful
for x in testdata/*.rpl; do echo -n "$x "; if ./testbound -p $x >/dev/null 2>&1; then echo OK; else echo failed; exit 1; fi done
-n testdata/acl.rpl
/bin/sh: line 1: 86501 Segmentation fault: 11  ./testbound -p $x > /dev/null 2>&1
failed
make: *** [test] Error 1

`>./unbound-checkconf /tmp/test/etc/unbound.conf`
Memory fault

`>sudo ./unbound -dv`
quits immediately

Unbound with libressl 2.2.1 is just fine.

**Comment by busterb** [comment]
Yes, I realize this. Please try my patch anyway.

**Comment by hdatma** [comment]
Patch applied...

`>make test`
[...]
[0] did 10000 in 265.571 msec for 37654.713805 encode/sec size 615
737315 checks ok.
./testbound -s
selftest successful
for x in testdata/*.rpl; do echo -n "$x "; if ./testbound -p $x >/dev/null 2>&1; then echo OK; else echo failed; exit 1; fi done
-n testdata/acl.rpl
/bin/sh: line 1:  3678 Segmentation fault: 11  ./testbound -p $x > /dev/null 2>&1
failed
make: *** [test] Error 1

**Comment by hdatma** [comment]
Patch applied on fresh sources, then autoconf, configure etc. 
Same errors.

**Comment by busterb** [comment]
I forgot to mention that after applying the patch you must also run 'autoreconf -i' to update autoconf's generated files in the unbound tree.

If this still does not resolve the issue, could you check that the headers you are building against are LibreSSL 2.2.2's ? If you wouldn't mind, please try running unbound's check manually:

grep OPENSSL_VERSION_TEXT /tmp/test/include/openssl/opensslv.h | grep "LibreSSL"

You should see no output if the headers are 2.2.2's, but it will print something with 2.2.1. When I was testing earlier, I made the mistake once of using 2.2.1's headers with 2.2.2's libs, which caused problems as well.

**Comment by busterb** [comment]
If you are still getting crashes and seem to have the correct headers, perhaps the backtrace would help. When I was debugging the original issue, the backtrace is:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_pthread.dylib       	0x00007fff910d6a58 pthread_mutex_init + 0
1   testbound                     	0x000000010cee83a1 daemon_main + 449
2   testbound                     	0x000000010ceec0e9 main + 6361
3   libdyld.dylib                 	0x00007fff8f33e5ad start + 1
```

The failure was way before any libressl code was invoked, which is what pointed to a miscompile with the emulated system library functions.

**Comment by hdatma** [comment]
I am happy to confirm that the patch is good. 
This morning I re-built the whole thing from scratch, and it works. 

Thank you.

**Comment by busterb** [comment]
Glad to hear it. This is now fixed upstream as well.

**Comment by Sp1l** [comment]
Patch for FreeBSD as an attachment here https://bugs.freebsd.org/202407
