### ISSUE TITLE
2.2.2 fails to build on OS X 10.6.8

### ISSUE THREAD

**Issue by leonklingele** [libressl-portable/portable#121]
libressl 2.2.2 fails to build on OS X 10.6.8.

```bash
$ ./configure --prefix=/tmp/building/libressl/2.2.2
$ make
```
Output:
```
Making all in crypto
/bin/sh ../libtool    --mode=compile gcc -std=gnu99  -g -O2 -Wall -std=gnu99 -fno-strict-aliasing  -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-all  -c -o bn/mont5-macosx-x86_64.lo bn/mont5-macosx-x86_64.s
libtool: compile:  gcc -std=gnu99 -g -O2 -Wall -std=gnu99 -fno-strict-aliasing -fno-strict-overflow -D_FORTIFY_SOURCE=2 -fstack-protector-all -c bn/mont5-macosx-x86_64.s  -fno-common -DPIC -o bn/.libs/mont5-macosx-x86_64.o
bn/mont5-macosx-x86_64.s:57:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:120:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:203:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:315:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:462:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:630:suffix or operands invalid for `movq'
make[1]: *** [bn/mont5-macosx-x86_64.lo] Error 1
make: *** [all-recursive] Error 1
```

Building 2.2.1 works fine.

**Comment by hdatma** [comment]
On OSX, it is always useful to have an up-to-date compiler. 
libressl on openbsd uses gcc, but libressl-portable on osx uses clang-llvm.

http://llvm.org/releases/download.html#3.6.2
http://llvm.org/releases/3.6.2/clang+llvm-3.6.2-x86_64-apple-darwin.tar.xz.sig
http://llvm.org/releases/3.6.2/clang+llvm-3.6.2-x86_64-apple-darwin.tar.xz

mkdir /opt
cd /opt
tar -xvf /path/to/clang+llvm-3.6.2-x86_64-apple-darwin.tar.xz
sudo ln -s "clang+llvm-3.6.2-x86_64-apple-darwin" llvm
export PATH="/opt/llvm/bin:$PATH";
export  CC="/opt/llvm/bin/clang"; # gcc
export CXX="/opt/llvm/bin/clang++"; # g++

**Comment by busterb** [comment]
This is possibly due to the switch to using AES-NI instructions directly causing issue with older binutils, or something in that area. Try building with '--disable-asm' for now.

**Comment by Qix-** [comment]
Getting this too, osx 10.10.2. `--disable-asm` seems to have worked.

```
$ as -v
Apple Inc version cctools-870, GNU assembler version 1.38

$ gcc --version
gcc (Homebrew gcc 4.9.2_1) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
-richard stallman snip-

$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-242.2
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7m armv7em
LTO support using: LLVM version 3.6.0svn

$ autoconf --version
autoconf (GNU Autoconf) 2.69
```

**Comment by bcook-r7** [comment]
Huh, what is GNU assembler version 1.38? We do automated builds on Travis CI against OS X 10.9 and I haven't seen a failure yet (2.2.2 was certainly tested on a 10.10.4 box as well): https://travis-ci.org/libressl-portable/portable/jobs/78198943 .

**Comment by Qix-** [comment]
Not sure what ASM flavor it's using under the hood, so in the event it was just the basic `as` assembler I figured it'd eliminate a step.

**Comment by busterb** [comment]
Fair enough. I wasn't able to reproduce using:
$ as -v
Apple Inc version cctools-855, GNU assembler version 1.38

Though I don't have homebrew gcc installed - will try that out of curiosity.

**Comment by busterb** [comment]
OK, I can repro when using gcc and not clang:

```
CC=/usr/local/Cellar/gcc49/4.9.3/bin/gcc-4.9 ./configure && make
bn/mont5-macosx-x86_64.s:57:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:120:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:203:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:315:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:462:suffix or operands invalid for `movq'
bn/mont5-macosx-x86_64.s:630:suffix or operands invalid for `movq'
```

**Comment by Qix-** [comment]
Interesting; I'm using clang as far as I'm aware (unless libressl does something wonky with `CC`). The parent project using libressl is building with clang just fine.

**Comment by DomT4** [comment]
> $ gcc --version
gcc (Homebrew gcc 4.9.2_1) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
-richard stallman snip-

How did this happen? Homebrew doesn't symlink anything directly as `gcc` to avoid intercepting calls intended to reach the `gcc` in `/usr/bin`. Did you manually create a symlink to `gcc` or? Under normal conditions you should see something like this:

```
~> gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

~> /usr/local/bin/gcc-5 --version
gcc-5 (Homebrew gcc 5.2.0) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by Qix-** [comment]
Nope, I've installed gcc though. I should probably uninstall it, but it has never conflicted with build scripts before, let alone `$(CC)`. It's not symlinked in any weird way - I'm fully aware of the differences and prefer clang anyway.

**Comment by DomT4** [comment]
Yes, that's my curiosity. We take significant efforts to avoid borking the system's default compilers, including not creating a vanilla `gcc` named symlink.

An `ls -l $(which gcc)` may be interesting.

**Comment by Qix-** [comment]
```
$ ls -l $(which gcc)
lrwxr-xr-x  1 qix  staff  7 Mar 12 20:32 /usr/local/bin/gcc -> gcc-4.9

$ ls -l $(which gcc-4.9)
lrwxr-xr-x  1 qix  staff  33 Mar 12 20:32 /usr/local/bin/gcc-4.9 -> ../Cellar/gcc/4.9.2_1/bin/gcc-4.9
```

**Comment by DomT4** [comment]
It's safe to remove the first symlink unless you left it there intentionally. That's not one of Homebrew's.

**Comment by Qix-** [comment]
But it is.

```
$ ls -l $(which gcc)
lrwxr-xr-x  1 qix  staff  7 Mar 12 20:32 /usr/local/bin/gcc -> gcc-4.9

$ brew unlink gcc
Unlinking /usr/local/Cellar/gcc/4.9.2_1... 778 symlinks removed

$ ls -l $(which gcc)
-rwxr-xr-x  1 root  wheel  14160 Sep 28  2014 /usr/bin/gcc
```

**Comment by Qix-** [comment]
I unlinked and attempted the build again. Seems to have gotten past the nasty part at this point; going to `brew link gcc` and see if it does, too.

**Comment by DomT4** [comment]
The `ls` of the installation's bin is:

```
ls gcc49/4.9.3/bin
c++-4.9  gcc-ar-4.9	 x86_64-apple-darwin14.4.0-c++-4.9    x86_64-apple-darwin14.4.0-gcc-ar-4.9
cpp-4.9  gcc-nm-4.9	 x86_64-apple-darwin14.4.0-g++-4.9    x86_64-apple-darwin14.4.0-gcc-nm-4.9
g++-4.9  gcc-ranlib-4.9  x86_64-apple-darwin14.4.0-gcc-4.9    x86_64-apple-darwin14.4.0-gcc-ranlib-4.9
gcc-4.9  gcov-4.9	 x86_64-apple-darwin14.4.0-gcc-4.9.3
```

If the `gcc` symlink was created inside `/usr/local/Cellar/gcc/` it's expected that it would be unlinked with the rest of the formula as requested. It shouldn't be there normally, and doesn't seem to be in the Yosemite bottle I checked.

Side note: Your Homebrew is out of date. We stopped shipping GCC-4.9 in the core a while ago and updated to GCC 5. `brew unlink gcc` should throw something like:
```
Unlinking /usr/local/Cellar/gcc/5.2.0... 1433 symlinks removed
```

**Comment by bcook-r7** [comment]
This is fixed upstream in https://github.com/libressl-portable/openbsd/commit/59937a4f1f9e742e63ed07ebe81cb92155d14bf9 now.

**Comment by shanyang0827** [comment]
I have the same error and don't know what to do

**Comment by shanyang0827** [comment]
It seem's like it is conflict with macport, but how can I totally uninstall macport

**Comment by Foadsf** [comment]
the problem is definitely with MacPorts. uninstall it.
