### ISSUE TITLE
CMakeLists.txt missing INSTALL directives

### ISSUE THREAD

**Issue by TheNietsnie** [libressl-portable/portable#123]
I love how fast CMake + Ninja makes LibreSSL go. Can we get an INSTALL directive added for headers and libraries (and maybe even add shared libraries?)

**Comment by bob-beck** [comment]
Right now our focus for the initial cmake stuff had been for Windows builds but I'm sure we'd look at diffs if you have them, or further support for this later on

**Comment by busterb** [comment]
Thanks, merged.
