### ISSUE TITLE
compilation error tls/strsep.c "DEF_WEAK" on HP-UX with HP C/aC++

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#127]
Hi,
I found tls/strsep.c caused "DEF_WEAK" compilation error on HP-UX with HP C/aC++.
HP-UX with GCC is OK.
<pre>
...
  CC       strsep.lo
"strsep.c", line 71: warning #2837-D: omission of explicit type is nonstandard
          ("int" assumed)
  DEF_WEAK(strsep);
  ^

"strsep.c", line 71: error #2092: identifier-list parameters may only be used
          in a function definition
  DEF_WEAK(strsep);
  ^

1 error detected in the compilation of "strsep.c".
*** Error exit code 1
</pre>
It seems that commit https://github.com/libressl-portable/openbsd/commit/913d1bab4757f65d7e1ec6d282392099dd3aa91d added DEF_WEAK,
but I could not find what is wrong for HP-UX with HP C/aC++, yet.

**Comment by busterb** [comment]
Thanks, I left out the update for libtls. Incoming shortly.

**Comment by busterb** [comment]
This should be resolved in afcfb2d5047075946a695819ba3723349feaf663

**Comment by kinichiro** [comment]
I have found tests/memmem.c had DEF_WEAK too.
Could you mend this too, please ?
Thanks

**Comment by busterb** [comment]
Thanks for the final patch @kinichiro.
