### ISSUE TITLE
Problems with gitignore file

### ISSUE THREAD

**Issue by btrask** [libressl-portable/portable#130]
Thanks for your great work on LibreSSL and libtls.

According to https://git-scm.com/docs/gitignore:

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined.

librelss-portable appears to do this in several places, for example excluding the `/crypto` directory but then `!` re-including several files within it.

**Comment by busterb** [comment]
Thanks for solving the mystery! This should be resolved now. Let me know if you spot anything else I missed.

**Comment by btrask** [comment]
I didn't realize you could just swap the order, but it seems to work. Thanks.
