### ISSUE TITLE
Windows: Undefined identifier X9_62_id_fieldType

### ISSUE THREAD

**Issue by Qix-** [libressl-portable/portable#131]
Just did a clean download. Using Msys with Git, whatever version was available as of two days ago.

```
$ ./autogen.sh
pulling upstream openbsd source
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Current branch master is up to date.
libcrypto version 35:0:0
libssl version 36:0:0
libtls version 7:0:0
Added OID dsa
objects.txt:41:Undefined identifier X9_62_id_fieldType
```

I tried just doing the CMake stuff but alas it failed since none of the ssl/tls source trees were available.

Not sure how to build this otherwise.

**Comment by bcook-r7** [comment]
I've never tried this with Msys, though I suspect the perl version has something to do with it. Note that if you use the release tarballs, they do not require perl to be on the system. I usually build under Cygwin on Windows platforms, even when not targeting Cygwin itself, using the dist-win.sh script and Cygwin's mingw-w64 cross compiler package

**Comment by Qix-** [comment]
Is there not a way to build with the MSVC toolchain? I prefer mingw-w64 too but this project requires the ability to build without Msys stuff to begin with.

**Comment by bcook-r7** [comment]
You should be able to use CMake with the latest tarball release. Would it be helpful if we packaged the pregenerated MSVC project with the -windows archive?

**Comment by Qix-** [comment]
The latest tarball release doesn't have a `CMakeLists.txt` it appears - even when I copy it into the tarball directory from the repository directory and try it, it fails since all of the source directories are still missing. 

Pre-packaging the MSVC project wouldn't be ideal seeing as how it's all butchered by CMake.

**Comment by busterb** [comment]
Ah, we missed distributing a few files. I'll upload a test tarball with this resolved if you would like to try it locally.

**Comment by busterb** [comment]
See https://github.com/libressl-portable/portable/releases/download/v2.3.0-test/libressl-2.3.0.tar.gz

This should now include all of the needed files in the distribution. There is a copy of the vs2013 output from CMake included for convenience, but if distributing it isn't helpful, I won't for the release tarballs.

**Comment by Qix-** [comment]
Much closer! For the record this is MSVC 2015, but I can't see how that'd make much of a difference.

It configured, appeared to start building but it's an include path problem now.

```
  C:\Users\qix\Downloads\libressl-2.3.0\include\compat\time.h(7): fatal error C1083: Cannot open include file: '../incl
ude/time.h': No such file or directory [C:\Users\qix\Downloads\libressl-2.3.0\build\crypto\crypto-objects.vcxproj]
  C:\Users\qix\Downloads\libressl-2.3.0\include\compat\stdio.h(10): fatal error C1083: Cannot open include file: '../in
clude/stdio.h': No such file or directory [C:\Users\qix\Downloads\libressl-2.3.0\build\crypto\crypto-objects.vcxproj]
  C:\Users\qix\Downloads\libressl-2.3.0\include\compat\stdio.h(10): fatal error C1083: Cannot open include file: '../in
clude/stdio.h': No such file or directory [C:\Users\qix\Downloads\libressl-2.3.0\build\crypto\crypto-objects.vcxproj]
```

Looks like it's looking for the standard headers in the include folder.

**Comment by busterb** [comment]
At any rate, VS2015 support should now exist in the latest portable head, and (provided you have a sufficiently-working perl installation) you can test it now.

If perl still gives you trouble under msys, run './configure && make dist' on a unix-like system and copy the resulting tarball to your windows box until we make the 2.3.0 release. I don't really have plans to support msys for doing development with the release tools themselves.

**Comment by Gwani** [comment]
Just for the record, in case anyone runs into the "Undefined identifier X9_62_id_fieldType" kind of problems when giving it another try with MSYS: It appears that the Perl scripts involved choke on Windows-style CRLF line endings. Make sure that the files being processed (e.g. objects.txt) all have Unix line endings (LF). This solved the problem at least for me. Note that those text files will automatically converted to CRLF line endings on checkout when having core.autocrlf=true (which is the setting recommended by Git on Windows).

**Comment by Qix-** [comment]
@Gwani thank you. I wouldn't have ever figured that out I don't think.

**Comment by anthonynovatsis** [comment]
So based on the above discussion, will future official release archives include all of the files required to build with CMake on Windows (i.e. no need for MSYS/MinGW)?

**Comment by Qix-** [comment]
@twphoenix did someone hijack your email?...

**Comment by busterb** [comment]
That's correct. 2.3.1 should already include everything (though you still need cmake itself).

I cleaned up @twphoenix's phishing messages.

**Comment by anthonynovatsis** [comment]
> That's correct. 2.3.1 should already include everything (though you still need cmake itself).

That's great..! Thanks for clarifying :smile:

The archive that is available now (https://github.com/libressl-portable/portable/archive/v2.3.1.zip) does not include everything (it is missing files that would be put in place by running ``./autogen.sh`` - e.g. files in ``ssl`` directory).  Is that expected?

**Comment by busterb** [comment]
The zip files generated by github for eatch tag are not real releases, but I'm not sure how to turn those off, or I would. What you are looking for is available from your local OpenBSD mirror, e.g.: http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.1.tar.gz

**Comment by Qix-** [comment]
@busterb the idea behind the tag releases (I think) is that repositories should only contain source material - files and resources that are necessary to generate anything and everything required to create the target artifact. Nothing more, nothing less. Github's release system is correct; if you're having to distribute something else along with it chances are it either needs to be generated using a script or included in the repository to begin with.

I'll add this to my list of things to look into, but it sounds like it's a generation issue. I'd like to better understand LibreSSL anyway before using it in production - this is a good excuse to do just that.

**Comment by anthonynovatsis** [comment]
Thanks for the help and clarifications :smile:

**Comment by pdf-outsystems** [comment]
I just hit this issue and was able to found the cause. In my case the crypto/objects/objects.txt was using CR/LF, but the regexes in object.pl are expecting LFs only.

**Comment by busterb** [comment]
Just a quick note almost 8 years later :) The root cause of the perl error in the original issue seems to be due to git checking out files with mismatched line endings from what the perl interpreter is expecting. I'm integrating a Windows builder with github actions now, and ran into the same thing. Workaround is to just install perl from msys2 along with git, and it seems to work.
