### ISSUE TITLE
test build fails on CentOS 7 and Ubuntu 15.04

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#138]
test build fails on CentOS 7 and Ubuntu 15.04

Hi,
I noticed that test build fails on CentOS 7 and Ubuntu 15.04.
While executing `./dist.sh` , I encountered the error below.

<pre>
...
  CC       netcat.o
  CC       socks.o
../../../apps/nc/socks.c:41:28: fatal error: readpassphrase.h: No such file or directory
 #include <readpassphrase.h>
                            ^
compilation terminated.
Makefile:404: recipe for target 'socks.o' failed
make[3]: *** [socks.o] Error 1
...
</pre>

readpassphrase.h does not exist in include/compat/.
It seems that libressl-2.3.0.tar.gz forgot to include `include/compat/readpassphrase.h` in it.

Thanks.

**Comment by busterb** [comment]
Thanks! The automated travis.ci builds should have caught this, but I it appears that 'make dist' is not a superset of 'make distcheck'.
