### ISSUE TITLE
compilation error ecdh/ech_key.c "#3143: arithmetic on pointer" on HP-UX with HP C/aC++

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#140]
Hi,
I encountered this now on HP-UX with C/aC++ compiler.
GCC was OK.
<pre>
...
  CC       ecdh/libcrypto_la-ech_err.lo
  CC       ecdh/libcrypto_la-ech_key.lo
"ecdh/ech_key.c", line 190: error #3143: arithmetic on pointer to void or
          function type
                        memset(out + buflen, 0, outlen - buflen);
                                   ^

1 error detected in the compilation of "ecdh/ech_key.c".
*** Error exit code 1

Stop.
*** Error exit code 1
</pre>
option `+O[no]signedpointers` seemed work well, but it didn't work.
I'm keeping to find the way to resolve this issue.

Thanks.

**Comment by busterb** [comment]
MSVC has the same issue with this. I think the correct fix is to cast the void* to something you can perform pointer arithmetic to, e.g.:

memset((void *)((size_t)out + buflen), 0, outlen - buflen);

**Comment by kinichiro** [comment]
Yes, and that cast worked well on HP-UX with C/aC++, too.
I wish that cast might apply to upstream.

**Comment by busterb** [comment]
Fixed in https://github.com/libressl-portable/openbsd/commit/66e7578c52325816698f3c656d2c1b3ab5e6ebcb

Thanks!
