### ISSUE TITLE
openssl(1) list-message-digest-commands still lists `sha`

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#141]
Hi,
digest `sha` was removed, but openssl(1) list-message-digest-commands still lists `sha`.

according to commit https://github.com/libressl-portable/openbsd/commit/a35c259729689f7960598492bb39baf404b4abbd ,
<pre>
...
    16  # define OPENSSL_NO_SHA0
...
</pre>

`OPENSSL_NO_SHA` of apps/openssl/openssl.c should be `OPENSSL_NO_SHA0` ?
<pre>
...
   229  #ifndef OPENSSL_NO_SHA
   230          { FUNC_TYPE_MD, "sha", dgst_main },
   231  #endif
...
</pre>
Thanks.

**Comment by busterb** [comment]
Thanks, seems like we have similar vestigial bits around md2 and others too.

**Comment by busterb** [comment]
Fixed in https://github.com/libressl-portable/openbsd/commit/4338d492e91310a4b0e60329e5197dd4e2c3cab7 , thanks.
