### ISSUE TITLE
ssl_print_tmp_key missing from s_cb.c

### ISSUE THREAD

**Issue by Safari77** [libressl-portable/portable#142]
libressl `openssl s_client` does not show this info (openssl 1.0.1+ does):
`Server Temp Key: ECDH, P-384, 384 bits`
`Server Temp Key: DH, 2048 bits`

**Comment by Safari77** [comment]
1.0.2 shows also "Peer signing digest"

**Comment by 4a6f656c** [comment]
LibreSSL now includes SSL_get_server_tmp_key() and openssl s_client displays the server ephemeral key details on connect.
