### ISSUE TITLE
NC does not build on MUSL

### ISSUE THREAD

**Issue by lluixhi** [libressl-portable/portable#144]
nc fails to build on MUSL-based linux because MUSL does not have a b64_ntop function.

**Comment by busterb** [comment]
Thanks. I thought it did, because I was testing using the ellcc.org toolchain. Ellcc appears to have its own patches on top of musl to add support.

**Comment by busterb** [comment]
resolved in a7f031ba55ac4a69263000357eb7f6d7fb88101a, thanks for the note.
