### ISSUE TITLE
libressl does not include _ECDSA_METHOD_new

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#145]
Origin of the problem:

https://www.dnssec-tools.org 
uses https://metacpan.org/pod/Crypt::OpenSSL::ECDSA 
uses _ECDSA_METHOD_new.

This is a blocker for those using DNSSEC with ECDSA, 
unless they use something else than dnssec-tools.

**Comment by 4a6f656c** [comment]
Are you able to provide further details? I'm not immediately seeing what is using Crypt::OpenSSL::ECDSA and why that is needing ECDSA_METHOD_new(). We'll probably look at bringing in the new API, but I'd like to understand the actual use case first.

**Comment by 4a6f656c** [comment]
Ah, is this just in the Crypt::OpenSSL::ECDSA tests?

**Comment by 4a6f656c** [comment]
Since there has not been any follow up to justify the use/addition, I'm going to close this issue.
