### ISSUE TITLE
Proposal: add tls_connect_fns and tls_accept_fns for 

### ISSUE THREAD

**Issue by krono** [libressl-portable/portable#146]
Currently, `libtls` supports establishing connections
 * directly (`tls_connect`/`tls_connect_servername`)
 * with given read/write-fds (`tls_connect_fds`/`tls_accept_fds`)
 * with a given socket (`tls_connect_socket`/`tls_accept_socket`) (which seems to be a shim for the fd ones)

I propose to add a new way: `tls_connect_fns` and `tls_accept_fns` that act similar to `SSL_set_bio` and provide a callback-based interface.

## Rationale

In some circumstances, the socket or file descriptor for the connection might not be directly available. One such scenario can be a custom networking implementation in a programming language.
This happens, for example, in Squeak/Smalltalk. A dedicated plugin is responsible for networking and _another_ plugin (currently using the openssl api) is responsible for encryption. However, the networking plugin allows a buffer-based access to the socket (without ever exposing their I/O fds or socket fds).
Hence, currently, a BIO-Based approach is used
(for example, in https://github.com/itsmeront/squeakssl/blob/master/src/unix/sqUnixOpenSSL.c , lines
 * 208 (connection, writing to the socket)
 * 291 (accepting a connection, writing to the socket)
 * 80 (setting the bio for a SSL context)
 Note how the functions are called with `src` and `dst` buffers that the SSL implementation has to interact with)

PS: If I should use other means of communication for this proposal, please direct me there.

**Comment by btrask** [comment]
I discussed this with Doug Hogan over email. Here was my proposal:

>     typedef ssize_t (*tls_read_cb)(void *_ctx, void *_buf, size_t _buflen);
>     typedef ssize_t (*tls_write_cb)(void *_ctx, const void *_buf,
>         size_t _buflen);
>     
>     int tls_accept_cbs(struct tls *_ctx, struct tls **_cctx,
>         tls_read_cb _cb_read, tls_write_cb _cb_write);
>     int tls_connect_cbs(struct tls *_ctx, tls_read_cb _cb_read,
>         tls_write_cb _cb_write, const char *_servername);
> 
> [...] The read and write cbs would work basically like `tls_read` and `tls_write` (but implemented by the user), and could either block or return poll in/out (only one each).

He sounded receptive and said they were doing to consider it. I offered to send a message to the mailing list but he said he wanted to keep bikeshedding to a minimum.

My use case is for talking to libuv. There is a hacky way to wait for readable, but no way to wait for writable. Currently I'm working around it with a timer.

**Comment by krono** [comment]
@btrask Thanks, that is interesting!

**Comment by markpotts123** [comment]
I would like to add my support for this proposal which I believe could be very useful.

**Comment by bbqsrc** [comment]
Has there been any movement on this proposal?

**Comment by bob-beck** [comment]
I would say the proposal for the cbs functions is sound. so I'd say in
principle we like your proposal.

So talk is cheap. show code. Got a diff?

**Comment by krono** [comment]
@btrask do you have some code ready you could show?

**Comment by btrask** [comment]
@krono This might help: https://github.com/btrask/stronglink/blob/master/src/http/Socket.c

All of the `async_*` calls are to a libuv wrapper. They generally mirror the underlying `uv_*` calls.

Improvements and bugfixes welcome. The code is MIT licensed.

**Comment by krono** [comment]
I finally came around to propose a way to have callback-based connect/accept.
I'm happy for feedback

**Comment by krono** [comment]
@bob-beck, do you have time to review this?

**Comment by bob-beck** [comment]
I haven't seen a diff yet ! :)   If you have something send to
tech@openbsd.org for us to have a look!

**Comment by krono** [comment]
@bob-beck The diff is in the pull request refferenced: https://github.com/libressl-portable/openbsd/pull/64/files 

I'm not sure the stuff is ready to sent it to your list…

**Comment by bob-beck** [comment]
Oh, I'm pretty sure it is..

It doesn't mean you won't make mistakes sending it.  and might get grumbled
at by some people, so be
prepared for criticism. You don't get to propose such a thing and not take
criticism ;) .It's how we do
things - and being able to deal with it is essential for working in this
area.

See, here's the thing, Yes, I can take your diff and post it myself and say
"this guy Tobias did this against portable"
or I can get *you* to post it and say "Hey I'm Tobias, I did this against
portable.  I'm sure it might need some
changes but what do you think - this is what I'm trying to solve..."

I would rather it take slightly longer and you to see some of our process,
learn how we work, and then maybe
keep contributing other things, than for me to just "do it for you" :)

go on, make a git diff --no-prefix of that and send it to tech@openbsd.org..
Introduce yourself, say what you're
trying to do, warn that the diff is against portable, and ask for some
people to look at it with you. Work with the
feedback you get..

**Comment by krono** [comment]
Ok. :)

**Comment by krono** [comment]
I think this can be closed now :)
