### ISSUE TITLE
Apache build fails centos 7

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [libressl-portable/portable#147]
CentOS 7 - apache 2.4.16 built just fine against 2.2.3

Now -

/builddir/build/BUILD/httpd-2.4.16/support/ab.c:2318: undefined reference to `SSLv3_client_method'

The full error :

    /usr/lib64/apr-1/build/libtool --silent --mode=link gcc -std=gnu99  -pthread  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -pie     -Wl,-z,relro,-z,now -o fcgistarter  fcgistarter.lo    -lselinux   /usr/lib64/libaprutil-1.la /usr/lib64/libapr-1.la
    ab.c: In function 'main':
    ab.c:2318:21: warning: implicit declaration of function 'SSLv3_client_method' [-Wimplicit-function-declaration]
                     meth = SSLv3_client_method();
                     ^
    ab.c:2318:26: warning: assignment makes pointer from integer without a cast [enabled by default]
                     meth = SSLv3_client_method();
                          ^
    ab.c:2372:5: warning: statement with no effect [-Wunused-value]
     CRYPTO_malloc_init();
     ^
    /usr/lib64/apr-1/build/libtool --silent --mode=link gcc -std=gnu99  -pthread  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -lssl -lcrypto -lpthread -ldl -pie \
        -Wl,-z,relro,-z,now -o ab  ab.lo    -lselinux   /usr/lib64/libaprutil-1.la /usr/lib64/libapr-1.la -lm
ab.o: In function `main':
    /builddir/build/BUILD/httpd-2.4.16/support/ab.c:2318: undefined reference to `SSLv3_client_method'
    collect2: error: ld returned 1 exit status

Apache is being compiled from src.rpm in a mock buildroot environment and the same src.rpm did build against libressl 2.2.3.

**Comment by AliceWonderMiscreations** [comment]
Damn I tried to get the markdown right...

**Comment by bob-beck** [comment]
You will need to get that nasty SSL3 support out of there.  2.3.0 removes
ssl3.. There are probably patches to do it
already in the OpenBSD ports tree, and they will be filtering upstream to
see if apache will take them.

**Comment by hogand** [comment]
The patch is listed on http://www.libressl.org/patches.html

It will be fixed upstream in Apache 2.4.17.

**Comment by AliceWonderMiscreations** [comment]
Thanks, quick question about a difference from Apache 2.5.0 and 2.4.6

https://svn.apache.org/viewvc/httpd/httpd/trunk/modules/ssl/ssl_engine_init.c?r1=1703952&r2=1703951&pathrev=1703952

    +#ifndef OPENSSL_NO_SSL3
         ssl_set_ctx_protocol_option(s, ctx, SSL_OP_NO_SSLv3,
                                     protocol & SSL_PROTOCOL_SSLV3, "SSLv3");
    +#endif

I assume that

    +#ifndef OPENSSL_NO_SSL3
        if (!(protocol & SSL_PROTOCOL_SSLV3)) {
           SSL_CTX_set_options(ctx, SSL_OP_NO_SSLv3);
        }
    +#endif

Is the proper equivalent?

**Comment by AliceWonderMiscreations** [comment]
It is building now, so thank you. I will assume that question above is correct, I'm just not an apache code guru.
