### ISSUE TITLE
"PATH_MAX" is undefined on HP-UX

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#148]
Hi,
I encountered this compilation error, now.
<pre>
  CC       x509.o
  CC       certhash.o
"certhash.c", line 477: error #2020: identifier "PATH_MAX" is undefined
        char target[PATH_MAX];
                    ^

1 error detected in the compilation of "certhash.c".
*** Error exit code 2
</pre>
How do you like using `_POSIX_PATH_MAX` instead of `PATH_MAX` ?

**Comment by hogand** [comment]
You don't want _POSIX_PATH_MAX.  That's the minimum value that an implementation accepts for a max pathname and is defined by POSIX.  Implementations are free to have higher values for PATH_MAX.  For instance, on OpenBSD:

    #define      _POSIX_PATH_MAX         256
    #define      PATH_MAX                1024   /* max bytes in pathname */

See http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html for POSIX 1003.1, 2013.  It's the same description for that section as POSIX 1003.1, 2001.

It looks like there are two problems on HP-UX:

1. they don't define PATH_MAX in limits.h except with certain #ifdefs, and
2. they are apparently not including the NUL character in the PATH_MAX value which is required by POSIX.

Python ran into this same situation: https://bugs.python.org/issue15835

I think we should add a #ifdef __hpux in the portable code similar to what Python has.

Is HP-UX's MAXPATHLEN 1023 or 1024?  Could you double check that the HP-UX PATH_MAX doesn't include the NUL?  Ideally we would want to define PATH_MAX per POSIX and count the NUL, but that may conflict with other software that assumes HP-UX doesn't include it.

**Comment by kinichiro** [comment]
I checked MAXPATHLEN and PATH_MAX of HP-UX.
* HP-UX's MAXPATHLEN is 1024 and defined in sys/param.h.
* HP-UX PATH_MAX doesn't include the NUL.
  in limit.h, it says "not including terminating null".
  PATH_MAX is enabled when -D_XOPEN_SOURCE less than 500.

**Comment by busterb** [comment]
Thanks, I included a portable shim for limits.h 1dd79f5d8f617afdb0f5d51ac0278d7b4f84b82f

**Comment by kinichiro** [comment]
Thanks, I could succeed to build on HP-UX 11.31 with both CC and GCC.
