### ISSUE TITLE
replace "timegm"

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#149]
Now, I've got this linker error on HP-UX 11i v3.
<pre>
...
  CC       cts128test.o
  CCLD     cts128test
ld: (Warning) Unsatisfied symbol "timegm" in file /tmp/work/CC/libressl-2.3.1/crypto/.libs/libcrypto.so.36
...
</pre>
`timegm` is used only in crypto/x509/x509_vfy.c like this.
<pre>
...
  1669          if ((time1 = timegm(&tm1)) == -1)
  1670                  goto out;
...
</pre>
Could you replace `timegm` with some more portable one, please ?

**Comment by kinichiro** [comment]
Same issue on Solaris 11.2 (i386).
<pre>
...
  CCLD     openssl
ld: warning: file ../../crypto/.libs/libcrypto.so: linked to /work/libressl-2.3.1/crypto/.libs/libcrypto.so: attempted multiple inclusion of file
Undefined                       first referenced
 symbol                             in file
timegm                              /work/libressl-2.3.1/crypto/.libs/libcrypto.so
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
</pre>

**Comment by busterb** [comment]
I first attempted a mktime based implementation based on the glibc manpage example, but it needed mutexes to be threadsafe around the getenv/setenv, and was pretty gross. It needed special Windows handling as well: 4298ac9305d89cadf90ebb01f0e85bb74fea2c1e

Other portable versions that I found int he wild were similarly either encumbered with bad licences, strangely written, or both. I finally found the musl version which looked saner and safer, so it is now included in libcompat https://github.com/libressl-portable/portable/commit/c02436645dafd0e97ee7e91ab8afd70bb997453c

**Comment by markokr** [comment]
AFAICS musl `__tm_to_secs()` does not have any kind of overflow protection.

Additionally, it does all computation in 'long long' which is good, but on last step it should check it against actual time_t limits.  musl may know that time_t is int64, but that cannot be assumed in libcompat.

**Comment by markokr** [comment]
Hm, sorry, I miscalculated - you don't need to check overflow for tm->longlong.

But check before cast to time_t should still be there.

**Comment by busterb** [comment]
Good point. I'll reopen this while this gets some refinement.

**Comment by kinichiro** [comment]
With current HEAD, I could succeed to build on both HP-UX 11.31 and Solaris 11.2 i386.
Thanks.

**Comment by busterb** [comment]
Are we good with this for release? I added the extra bounds checks to timegm before we cast the long long back to time_t on non-64-bit systems here: https://github.com/libressl-portable/portable/commit/3f79a49dd29be1ea2a227304a496269711eea4d9

We currently have one timegm call left in crypto//x509/x509_vfy.c

**Comment by busterb** [comment]
I think this is resolved for -portable now.
