### ISSUE TITLE
LibreSSL builds use installed headers rather than bundled headers

### ISSUE THREAD

**Issue by jeremyhu** [libressl-portable/portable#150]
The build system for libressl places include directives in CFLAGS instead of CPPFLAGS.  This results in the installed copies of headers being used instead of the bundled headers if the package is configured with CPPFLAGS set.  This is common practice by many package management systems, such as MacPorts.  This results in the newly built libcrypto incorrectly identifying itself as the previously installed version.  This can be made obvious by adding an #error line to the instaleld opensslv.h and building like:

CPPFLAGS=${prefix}/include ./configure --prefix=${prefix} && make

AM_CPPFLAGS (or per-target CPPFLAGS) appear before CPPFLAGS which appear before AM_CFLAGS (or per-target CFLAGS) which appear before CFLAGS.

The attached patch fixes the issue and is what we're using in MacPorts.

**Comment by jeremyhu** [comment]
--- Makefile.am.common.orig	2015-08-19 18:01:27.000000000 -0700
+++ Makefile.am.common	2015-10-11 16:05:26.000000000 -0700
@@ -1,2 +1,2 @@
-AM_CFLAGS = -I$(top_srcdir)/include -I$(top_srcdir)/include/compat
-AM_CPPFLAGS = -DLIBRESSL_INTERNAL
+AM_CFLAGS =
+AM_CPPFLAGS = -I$(top_srcdir)/include -I$(top_srcdir)/include/compat -DLIBRESSL_INTERNAL
--- crypto/Makefile.am.orig	2015-08-19 18:01:27.000000000 -0700
+++ crypto/Makefile.am	2015-10-11 16:10:26.000000000 -0700
@@ -1,8 +1,8 @@
 include $(top_srcdir)/Makefile.am.common
 
-AM_CFLAGS += -I$(top_srcdir)/crypto/asn1
-AM_CFLAGS += -I$(top_srcdir)/crypto/evp
-AM_CFLAGS += -I$(top_srcdir)/crypto/modes
+AM_CPPFLAGS += -I$(top_srcdir)/crypto/asn1
+AM_CPPFLAGS += -I$(top_srcdir)/crypto/evp
+AM_CPPFLAGS += -I$(top_srcdir)/crypto/modes
 
 lib_LTLIBRARIES = libcrypto.la
 
@@ -11,7 +11,8 @@ EXTRA_DIST += CMakeLists.txt
 
 libcrypto_la_LDFLAGS = -version-info @LIBCRYPTO_VERSION@ -no-undefined
 libcrypto_la_LIBADD = libcompat.la libcompatnoopt.la
-libcrypto_la_CPPFLAGS = -DLIBRESSL_INTERNAL
+libcrypto_la_CPPFLAGS = $(AM_CPPFLAGS)
+libcrypto_la_CPPFLAGS += -DLIBRESSL_INTERNAL
 libcrypto_la_CPPFLAGS += -DOPENSSL_NO_HW_PADLOCK
 if OPENSSL_NO_ASM
 libcrypto_la_CPPFLAGS += -DOPENSSL_NO_ASM
--- tls/Makefile.am	2015-10-11 16:10:59.000000000 -0700
+++ tls/Makefile.am	2015-10-11 16:20:16.000000000 -0700
@@ -5,7 +5,7 @@ lib_LTLIBRARIES = libtls.la
 EXTRA_DIST = VERSION
 EXTRA_DIST += CMakeLists.txt
 
-libtls_la_CPPFLAGS =
+libtls_la_CPPFLAGS = $(AM_CPPFLAGS)
 
 if OPENSSLDIR_DEFINED
 libtls_la_CPPFLAGS += -DOPENSSLDIR=\"@OPENSSLDIR@\"

**Comment by busterb** [comment]
This should be resolved now. Thanks for the patches.
