### ISSUE TITLE
rfc5280time fails on Solaris 11.2 i386

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#153]
Hi,
With current HEAD, rfc5280time test fails on Solaris 11.2 i386.
<pre>
$ ./rfc5280time
RFC5280 Invalid time tests...
RFC5280 GENERALIZEDTIME tests...
FAIL: test 0 - strings differ ('19691223021215Z' != '99991231235959Z')
FAIL: test 1 - strings differ ('20240112041144Z' != '21600218104000Z')
FAIL: test 2 - strings differ ('19131125173144Z' != '20500101000000Z')
RFC5280 UTCTIME tests...
FAIL: test 2 - failed to set time -1770359297
$
</pre>

On HP-UX 11.31 and CentOS7, rfc5280time test succeeds.
<pre>
RFC5280 Invalid time tests...
RFC5280 GENERALIZEDTIME tests...
RFC5280 UTCTIME tests...
</pre>

**Comment by busterb** [comment]
Thanks for the note. I've been working through these failures on 32-bit linux and Windows.

Systems with 32-bit time_t is one thing that will make some of these tests fail as-is, not to mention the compiler warnings building the test since the constants over/underflow time_t.

**Comment by bob-beck** [comment]
We should make sure if we expect the test to fail we sill warn about 32 bit time_t. 

The problem is we are well into the realm of post 2038 reality as far as the possibility for times in a certificate go,  and supporting times from certificates which the system time can't deal with is a mistake. 32 bit systems can be changed to have 64 bit time_t, and we should make people aware when they are using one that will have a problem... The regress tests point out that your system can't handle the times legally allowed in a certificate.

**Comment by busterb** [comment]
I added a warning to configure about this as late as possible in the output, so hopefully it will get noticed. Does that seem sufficient?
```
checking size of time_t... 4
 ** Warning, this system is unable to represent times past 2038
 ** It will behave incorrectly when handling valid RFC5280 dates
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/openssl/Makefile
config.status: creating crypto/Makefile
config.status: creating ssl/Makefile
config.status: creating tls/Makefile
config.status: creating tests/Makefile
config.status: creating apps/Makefile
config.status: creating apps/openssl/Makefile
config.status: creating apps/nc/Makefile
config.status: creating man/Makefile
config.status: creating libcrypto.pc
config.status: creating libssl.pc
config.status: creating libtls.pc
config.status: creating openssl.pc
config.status: executing depfiles commands
config.status: executing libtool commands
$
```

I also tried to add a warning to the check output, but it wasn't clear if it was possible to generate a soft failure. Will look at it more.

**Comment by bob-beck** [comment]
warning looks fine

**Comment by busterb** [comment]
I think this should be handled appropriately now. The test output will also show a warning about skipped tests now (I should go back and do this for other skipped tests as well):

```
PASS: pkcs7test
PASS: poly1305test
PASS: pq_test.sh
PASS: randtest
PASS: rc2test
PASS: rc4test
PASS: rfc5280time_small.test 1
SKIP: rfc5280time_small.test 2 - rfc5280time_64-bit # SKIP this system is unable to represent times past 2038
￼```

**Comment by bob-beck** [comment]
In general that's cool. but I wonder if we're being too agressive here and
I need an option to compare by tm if
the system can't deal properly..

I'll get the latest time cleanup in once joel reviews it and then consider
it.. we'll see how this flys.

**Comment by busterb** [comment]
I think we have all the bits we need to preserve the 64-bit conversion in portable on 32-bit time_t systems. The fallback code does everything with long long internally, the result is just getting truncated on its way out.

**Comment by busterb** [comment]
Or in other words, it would be nice to have a direct tm comparison :) On another note, I had to replace gmtime on Windows because it fails with negative time_t, at least with mingw.

**Comment by bob-beck** [comment]
Yeah, I'm considering tm comparison..  I'll think about it after the latest
round of things come in. If I do it I wanna do it
in base, sanely.

**Comment by kinichiro** [comment]
I checked with current HEAD on Solaris 11.2 i386.
This is just a report and it worked well.

I could see this warning while running configure.
<pre>
$ ./configure
...
checking if .gnu.warning accepts long strings... yes
checking size of time_t... 4
 ** Warning, this system is unable to represent times past 2038
 ** It will behave incorrectly when handling valid RFC5280 dates
checking that generated files are newer than configure... done
configure: creating ./config.status
...
</pre>

And rfc5280time_small.test 2 was skipped.
<pre>
$ make check
...
PASS: rc4test
PASS: rfc5280time_small.test 1
SKIP: rfc5280time_small.test 2 - rfc5280time_64-bit # SKIP this system is unable to represent times past 2038
PASS: rmdtest
...
============================================================================
Testsuite summary for libressl 2.3.1
============================================================================
# TOTAL: 54
# PASS:  53
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in man
</pre>

Thanks.
