### ISSUE TITLE
v2.2.x tls/Makefile.am requires changes to honor CPPFLAGS

### ISSUE THREAD

**Issue by jeremyhu** [libressl-portable/portable#154]
It looks like my CPPFLAGS changes were merged into v2.2 as well.  Unfortunately, additional changes are needed to make it work for v2.2.  master had prior changes to tls/Makefile.am that made this hunk no longer relevant, but it is now needed for v.2.2.4.  I'm sorry for any confusion that I may have caused with this.

<pre>
--- tls/Makefile.am	2015-10-19 00:00:25.000000000 -0700
+++ tls/Makefile.am	2015-10-19 00:01:14.000000000 -0700
@@ -5,7 +5,7 @@ lib_LTLIBRARIES = libtls.la
 EXTRA_DIST = VERSION
 EXTRA_DIST += CMakeLists.txt
 
-libtls_la_CPPFLAGS =
+libtls_la_CPPFLAGS = $(AM_CPPFLAGS)
 
 if OPENSSLDIR_DEFINED
 libtls_la_CPPFLAGS += -DOPENSSLDIR=\"@OPENSSLDIR@\"
</pre>

**Comment by busterb** [comment]
I'm not so sure. What base branch are you using for this diff?

tls/Makefile.am doesn't set libtls_la_CPPFLAGS, which I believe means it is already AM_CPPFLAGS by default. Am I wrong? I also see your patch setting OPENSSLDIR, which the upstream version does not do either for libtls.

**Comment by jeremyhu** [comment]
It's not off of any base branch.  It's off of your 2.2.4 tarball.  I couldn't figure out where you actually have that in git.

**Comment by busterb** [comment]
Sorry, I'm just not seeing it, but am certainly interested if you are seeing something different from your local mirror.

```
$ curl -O http://ftp5.usa.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.2.4.tar.gz                                           
$ curl -O http://ftp5.usa.openbsd.org/pub/OpenBSD/LibreSSL/SHA256.sig   
$ signify -C -p libressl.pub -x SHA256.sig libressl-2.2.4.tar.gz      
Signature Verified
libressl-2.2.4.tar.gz: OK
$ tar zxf libressl-2.2.4.tar.gz                                                                                                  
$ cat libressl-2.2.4/tls/Makefile.am                                                                                             
include $(top_srcdir)/Makefile.am.common

lib_LTLIBRARIES = libtls.la

EXTRA_DIST = VERSION
EXTRA_DIST += CMakeLists.txt

libtls_la_LDFLAGS = -version-info @LIBTLS_VERSION@ -no-undefined
libtls_la_LIBADD = ../crypto/libcrypto.la ../ssl/libssl.la $(PLATFORM_LDADD)

libtls_la_SOURCES = tls.c
libtls_la_SOURCES += tls_client.c
libtls_la_SOURCES += tls_config.c
libtls_la_SOURCES += tls_server.c
libtls_la_SOURCES += tls_util.c
libtls_la_SOURCES += tls_verify.c
noinst_HEADERS = tls_internal.h

if !HAVE_STRSEP
libtls_la_SOURCES += strsep.c
endif
```

**Comment by busterb** [comment]
Would you mind double-checking that your tarball contains the expected contents as above? If not, could you let us know what mirror you downloaded from?

**Comment by jeremyhu** [comment]
<pre>
$ openssl sha256 libressl-2.2.4.tar.gz 
SHA256(libressl-2.2.4.tar.gz)= 6b409859be8654afc3862549494e097017e64c8d167f12584383586306ef9a7e

$ tar xzf libressl-2.2.4.tar.gz 

$ cat libressl-2.2.4/tls/Makefile.am
include $(top_srcdir)/Makefile.am.common

lib_LTLIBRARIES = libtls.la

EXTRA_DIST = VERSION
EXTRA_DIST += CMakeLists.txt

libtls_la_LDFLAGS = -version-info @LIBTLS_VERSION@ -no-undefined
libtls_la_LIBADD = ../crypto/libcrypto.la ../ssl/libssl.la $(PLATFORM_LDADD)

libtls_la_SOURCES = tls.c
libtls_la_SOURCES += tls_client.c
libtls_la_SOURCES += tls_config.c
libtls_la_SOURCES += tls_server.c
libtls_la_SOURCES += tls_util.c
libtls_la_SOURCES += tls_verify.c
noinst_HEADERS = tls_internal.h

if !HAVE_STRSEP
libtls_la_SOURCES += strsep.c
endif
</pre>

**Comment by jeremyhu** [comment]
Yeah, this was actually added by an earlier patch in the MacPorts port package.  I'm embarrassed that I didn't notice that.  Sorry for the noise.
