### ISSUE TITLE
Build broken on Fedora 21

### ISSUE THREAD

**Issue by btrask** [libressl-portable/portable#155]
Hi guys,

When building over the past couple days, I've been getting errors like this:

```
asn1pars.c: In function ‘asn1parse_main’:
asn1pars.c:251:3: warning: implicit declaration of function ‘pledge’ [-Wimplicit-function-declaration]
   if (pledge("stdio rpath wpath cpath", NULL) == -1) {
   ^
```

And:

```
asn1pars.o: In function `asn1parse_main':
.../libressl-portable/apps/openssl/asn1pars.c:251: undefined reference to `pledge'
```

This is on Fedora 21.

Perhaps I'm missing something because I wouldn't expect something like this to go unnoticed.

Nonetheless thanks and keep up the good work!
Ben

**Comment by bcook-r7** [comment]
Strange; did you grab the latest portable tree with this commit? https://github.com/libressl-portable/portable/commit/e8c92100735f1e32d4b6f4a5a2670a0bf98ad1a8

**Comment by btrask** [comment]
Thanks! I cloned a fresh copy and now it seems to work. Perhaps there was a problem with the `update.sh` script?

**Comment by busterb** [comment]
update.sh currently only pulls in the latest code from the upstream openbsd repo. it doesn't update this repository itself. You may need to occasionally run 'git pull' to get the latest version if this repo.

**Comment by btrask** [comment]
Oh I see, my mistake. Sorry for the false alarm.
