### ISSUE TITLE
Please for the good of the humanity merge with openssl. 

### ISSUE THREAD

**Issue by LifeIsStrange** [libressl-portable/portable#157]
Why fork ? Why separate efforts, you have the same finality, the security of the humans, we all win if you merge with openssl.

**Comment by AliceWonderMiscreations** [comment]
Actually, it is good for there to be several distinct open source projects providing a TLS stack. It's the same concept as genetic diversity in biology. It allows us to adapt when one project no longer is the best "gene" for a particular application.

Being open source, quality improvements from one can always be merged into the other.

**Comment by 4a6f656c** [comment]
What problem is the existence of LibreSSL causing for you exactly?

**Comment by LifeIsStrange** [comment]
Oh i'm infinitely sorry for the late !! 
"Being open source, quality improvements from one can always be merged into the other."
But it's duplicates efforts, you make doublons, why not directly improve openssl instead of create a fork wich will be little used :/

"What problem is the existence of LibreSSL causing for you exactly?"
The same answer, I see a useless duplicates of work, you have really good improvements on libressl over openssl it's true but I think you should merge and directly improve openssl, your fork is little used and will probably always be, it's sad.

**Comment by steakknife** [comment]
[Long read draft I just wrote on thoughts of the tensions involved](https://gist.github.com/steakknife/ed37177352299b4ffd28)

**Comment by LifeIsStrange** [comment]
Wow I totally agree with you :)
