### ISSUE TITLE
[PATCH] libressl does not build on illumos

### ISSUE THREAD

**Issue by andy-js** [libressl-portable/portable#158]
libressl fails to build on illumos because libcrypto references libcompatnoopt as a dependency but this isn't getting built because it has no sources.

diff --git a/crypto/Makefile.am b/crypto/Makefile.am
index e1ced3c..62c8bbf 100644
--- a/crypto/Makefile.am
+++ b/crypto/Makefile.am
@@ -13,7 +13,10 @@ EXTRA_DIST += CMakeLists.txt
 EXTRA_DIST += compat/strcasecmp.c
 
 libcrypto_la_LDFLAGS = -version-info @LIBCRYPTO_VERSION@ -no-undefined
-libcrypto_la_LIBADD = libcompat.la libcompatnoopt.la
+libcrypto_la_LIBADD = libcompat.la
+if !HAVE_EXPLICIT_BZERO
+libcrypto_la_LIBADD += libcompatnoopt.la
+endif
 libcrypto_la_CPPFLAGS = $(AM_CPPFLAGS)
 libcrypto_la_CPPFLAGS += -DLIBRESSL_INTERNAL
 libcrypto_la_CPPFLAGS += -DOPENSSL_NO_HW_PADLOCK
@@ -31,13 +34,15 @@ else
 libcrypto_la_CPPFLAGS += -DOPENSSLDIR=\"$(sysconfdir)/ssl\"
 endif
 
-noinst_LTLIBRARIES = libcompat.la libcompatnoopt.la
+noinst_LTLIBRARIES = libcompat.la
 
 # compatibility functions that need to be built without optimizations
+if !HAVE_EXPLICIT_BZERO
+noinst_LTLIBRARIES += libcompatnoopt.la
+
 libcompatnoopt_la_CFLAGS = -O0
 libcompatnoopt_la_SOURCES =
 
-if !HAVE_EXPLICIT_BZERO
 if HOST_WIN
 libcompatnoopt_la_SOURCES += compat/explicit_bzero_win.c
 else

**Comment by busterb** [comment]
Fair enough, though I wonder why this does not show up as a problem with other OSes that have explicit_bzero. Also, could you say what illumos distribution / version you tested with?

**Comment by andy-js** [comment]
I could tell you but then I'd have to kill you.  What I can tell you are the versions of some of the things in my toolchain which might help:

awk - 4.1.3
autoconf - 2.64
automake - 1.15
libtool - 2.4.6
m4 - 1.4.16
make - 4.1
perl - 5.21.10

**Comment by andy-js** [comment]
I'm actually running autoconf 2.69, not 2.64.  I doubt that changes anything though.

**Comment by andy-js** [comment]
I just had a thought.  I'm building with --disable-static.  Could that be a factor?

**Comment by busterb** [comment]
Maybe, but your patch looks fine either way.
