### ISSUE TITLE
String length not being calculated correctly on Windows?

### ISSUE THREAD

**Issue by lifeofguenter** [libressl-portable/portable#159]
```
Country Name (2 letter code) [AU]:ZA
string is too long, it needs to be less than  2 bytes long
```

Most probably due to \r\n line endings?

**Comment by busterb** [comment]
Yeah, looks like it, since we account for the \n. Curious why I didn't see this with mingw's fgets, maybe it does an internal transformation. Were you testing the windows binaries we built, or your own? If your own, built with which Windows toolchain?

**Comment by lifeofguenter** [comment]
Using your windows binaries (http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.1-windows.zip)

**Comment by busterb** [comment]
Thanks; I put up a fix to review. It seems that we can manipulate the behavior of gets in mingw based on the environment flags, but I think it makes sense to wrap gets(3) on Windows so it generates what the code expects. Unfortunately fixing this revealed that other string input was also processing \r characters when they should have been stripped, such as password prompts.
