### ISSUE TITLE
libtls: override _PATH_SSL_CA_FILE at compile time

### ISSUE THREAD

**Issue by equalsraf** [libressl-portable/portable#160]
Cheers, I'm using libtls in systems where the CA certificate bundle is not installed in /etc/ssl/cert.pem (Linux-SuSe, Windows), the default value is defined in tls_internal.h as _PATH_SSL_CA_FILE.

Any chance we can get a way to override this default at compile time? Right now we can't even override it using CFLAGS because the #define is unguarded, a small patch

```diff
diff --git a/src/lib/libtls/tls_internal.h b/src/lib/libtls/tls_internal.h
index e21989c..2ce92f3 100644
--- a/src/lib/libtls/tls_internal.h
+++ b/src/lib/libtls/tls_internal.h
@@ -24,7 +24,9 @@
 
 #include <openssl/ssl.h>
 
-#define _PATH_SSL_CA_FILE "/etc/ssl/cert.pem"
+#ifndef _PATH_SSL_CA_FILE
+# define _PATH_SSL_CA_FILE "/etc/ssl/cert.pem"
+#endif
```

would enable the use of `make CFLAGS='-D_PATH_SSL_CA_FILE=\"/etc/ssl/ca-bundle.pem\"'`.

Also shouldn't the default value use OPENSSLDIR?

**Comment by busterb** [comment]
Thanks for the suggestion, I'll get that updated.

**Comment by busterb** [comment]
nc(1) needed updates, since it also embeds a path: 1988b8f65e4bfa2c9fb1fa13316f3c22ec59d298
