### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by Taiki-San** [libressl-portable/portable#161]
The documentation of EVP_PKEY_decrypt and EVP_PKEY_encrypt is incorrect, probably not updated when the API changed.
The exemple for two API show the use of ```RSA_OAEP_PADDING``` as an argument of ```EVP_PKEY_CTX_set_rsa_padding```. However, this isn't defined in the last version of either OpenSSL or LibreSSL.
The correct constant is probably ```RSA_PKCS1_OAEP_PADDING```.
However, I can't submit a formal pull request because the man/*.3 files aren't available in the tree on github.
The two affected files in the last release are
```
man/EVP_PKEY_decrypt.3
man/EVP_PKEY_encrypt.3
```

**Comment by busterb** [comment]
For documentation updates, I would suggest either PR to https://github.com/libressl-portable/openbsd , or email to tech@openbsd.org

**Comment by busterb** [comment]
I submitted a patch to fix this to tech@openbsd.org

**Comment by busterb** [comment]
Fixed here: https://github.com/libressl-portable/openbsd/commit/ebccdf272680afdb5386c23ed10ea3ee417a73fc

Thanks @Taiki-San

**Comment by Taiki-San** [comment]
No problem, thanks for fixing the issue!
