### ISSUE TITLE
Provide functionality for disabling SSLv2 handshakes

### ISSUE THREAD

**Issue by selecadm** [libressl-portable/portable#166]
After fixing "issue" https://github.com/libressl-portable/portable/issues/122, LibreSSL again has SSL2 compat.

Removing strings added in https://github.com/libressl-portable/openbsd/commit/59785c860c90ffae3a6bea20e2d52a0ce89e4ca3 didn't help. Also, compiling nginx 1.9.9 with LibreSSL 2.2.2 didn't help, while nginx 1.9.3 is fine. Strange.

I am asking LibreSSL team for two things:
1. If it's necessary to accept "no extensions" case, please remove SSL2 compat in the next public releases through other means.
Privacy concerns explained here: https://twitter.com/selecadm/status/674979088558399489
2. Please also provide instructions on how to reject "no extensions" regardless.

**Comment by bob-beck** [comment]
We would have similar concerns about the interop issues, obviously - Your tweet, being a tweet is a little terse on the details, and what you're asking us for..  effectively you'd like a knob to disable the initial handshake negotiation behaviour in the library. correct? 

If you can get us a little test case to show the certificate issue you allude to in the tweet, that would be of help - especially if we want to find a more intelligent way to solve this than a big frankenstein switch of a big hammer.

**Comment by 4a6f656c** [comment]
Uhm, do you actually understand what you're requesting here?

**Comment by selecadm** [comment]
@4a6f656c, yes, I am requesting LibreSSL rejecting ClientHello in SSL2 format, like LibreSSL 2.2.2 was doing.

**Comment by bob-beck** [comment]
Why?

**Comment by selecadm** [comment]
Misconfigured or outdated clients sending SSL2 handshakes don't specify SNI, having SSL2 compat makes them able to ignore certificate mismatch, and the information would be encrypted using a wrong public key.

Clients like Java 6 (potentially malicious or just unwanted bots) don't support strong Diffie-Hellman parameters. Having SSL2 compat results in a server doing its part of DH computation later rejected by client. Rejecting SSL2 handshakes means no waste of time and CPU cycles.

**Comment by bob-beck** [comment]
At the moment at least this has a pretty severe impact on compatibility
with clients that while older, are still capable
of negotiating an adequately secure handshake, assuming you've configured
the server to only negotiate reasonable
things.

So in order to either break a significant number of clients or add a knob
to the code, (I assume you simply want to reject anything that doesn't
support SNI) my criteria for supporting such a change would be that there's
a real issue from a real client to a properly set up server as you describe
- Got such an example for us where the client hasn't been hopelessly
misconfigured? (since the client can be misconfigured to simply ignore
certificate mismatches anyway) - We need to
consider the tradeoffs fully here.

**Comment by 4a6f656c** [comment]
There is no requirement for a client to include a server_name TLS extension - refusing to handle SSLv2 style client hellos is only going to break interop with no real benefit.

If you're concerned about DH computation overhead, you can disable DHE ciphersuites.

**Comment by 4a6f656c** [comment]
And for the record, we never actually removed/disabled SSLv2 client handshake support.

**Comment by selecadm** [comment]
Have made testing sites:

LibreSSL 2.2.2 without SSL2 compat
https://222.libretls.xyz

LibreSSL 2.2.3 with SSL2 compat
https://223.libretls.xyz

Other from this, completely the same configuration.

Test with Internet Explorer misconfigured such as:
— SSL 2 enabled
— TLS 1.2 disabled

For 2.2.2 there is a typical connection failure without possibility to continue.

For 2.2.3 there is cert mismatch.
My example uses revoked certificate, so to continue one needs revocation check disabled. This isn't a general case, but I can still make a point here: IE receives mismatched certificate, talks to a different CA about its status, shows "revoked" without even any clarification that it's __mismatched__ revoked certificate, makes people think their desirable site's cert is revoked. In reality, its client-side problem which is correctly handled by 2.2.2.

**Comment by AliceWonderMiscreations** [comment]
If you want the 2.2.2 behaviour it is pretty easy to patch 2.3.x to have the 2.2.2 behaviour (that's what I do) which I believe was a bug and not a feature, but a bug some of us liked. We can patch before building.

**Comment by 4a6f656c** [comment]
@selecadm So what do you plan on doing with TLS clients that do not include a server_name TLS extension?

**Comment by selecadm** [comment]
@4a6f656c in case it's an SSLv2 ClientHello because of misconfiguration, I want to reject such, don't let them get cert mismatch.
Also, it makes a server harder to guess what elliptic curves and signature algorithms a client supports.

I would like to accept clients that support at least renegotiation_info.
Problem with Android 2 was caused because of using TLS_EMPTY_RENEGOTIATION_INFO_SCSV cipher suite. As it may be a good workaround against extension intolerant servers, it's not smart from my point of view.

**Comment by AliceWonderMiscreations** [comment]
```
diff -ur libressl-2.2.3.orig/ssl/t1_lib.c libressl-2.2.3/ssl/t1_lib.c
--- libressl-2.2.3.orig/ssl/t1_lib.c	2015-08-28 10:42:03.000000000 -0700
+++ libressl-2.2.3/ssl/t1_lib.c	2015-09-04 04:08:49.935352232 -0700
@@ -2087,8 +2087,6 @@
 		return -1;
 
 	/* Now at start of extensions */
-	if (CBS_len(&session_id) == 0)
-		return 0;
 	if (!CBS_get_u16_length_prefixed(&session_id, &extensions))
 		return -1;
 
```

Just do that before building. Remove two lines.

**Comment by 4a6f656c** [comment]
@selecadm This was originally about an SSLv2 client getting a "cert mismatch", which will also equally happen with any TLS client that fails to send a server_name TLS extension. Now you've moved on to sigalgs and EC curves. The bottom line is that if a client is prepared to do SSLv2 it will most likely send a SSLv2 client hello. What it really seems that you're asking for is a way to reject connections from SSLv2 enabled clients, which effectively has nothing to do with extensions.

@AliceWonderMiscreations reintroducing bugs in the extension parsing code is not recommended - if you want to reject SSLv2 client hellos then I would strongly suggest that the relevant code be changed instead.

**Comment by bob-beck** [comment]
I am not averse to correctly rejecting SSL2 enabled clients.. but this is
probably not the way to do it.

**Comment by selecadm** [comment]
Can we have a special argument during building?

Something like:
> ./configure -DLIBRESSL_NO_SSL2_COMPAT

**Comment by AliceWonderMiscreations** [comment]
Just for the record, the build of LibreSSL I maintain for CentOS 7 - I did remove the patch that I had to remove the compatibility. I'll wait for the project to provide a proper way if it decided to do so.

**Comment by AliceWonderMiscreations** [comment]
I might be wrong about this, but from what I can tell, the only clients that benefit from SSL2 handshake are very old clients that do not support SNI or anything newer than TLS 1.0 or DH parameters bigger than the 1024-bit that are below recommended anyway.

**Comment by busterb** [comment]
The problem was originally reported on Android 2.x clients, so I think we could remove this if we removed TLS v1.0. Maybe it we could automatically reject SSLv2 handshake compat if nothing less than TLS v1.2 is enabled (e.g. the default libtls configuration).

**Comment by bob-beck** [comment]
After some discussion with Joel, I think the clients that benefit from still using this only support the old tls 1.0 stuff, so I think the correct solution is to disable the handshake unless tls 1.0 is enabled.  Probably sensisble and doesn't require a knob for most users of this configuration

**Comment by bob-beck** [comment]
Committed to OpenBSD-current. - We will refuse the ssl2 handshake unless you have TLS 1.0 turned on.

**Comment by hdatma** [comment]
Thank you! Refusing the SSLv2 handshake unless TLSv1.0 is enabled is the best solution to us. In fact, disabling SSLv2 handshakes as proposed by AliceWonderMiscreations results into fixing the web server while breaking the e-mail server. This other approach allows for testing different policies on different servers.
