### ISSUE TITLE
Windows: libtls does not call WSAStartup

### ISSUE THREAD

**Issue by equalsraf** [libressl-portable/portable#167]
I'm using libssl 2.3.1 in Windows (from the released binaries), when I try to use libtls the following error message is displayed

    Either the application has not called WSAStartup, or WSAStartup failed. : No error

It seems WSAStartup is not being called, the following test example is failing for me with that message. I've added a quick workaround that can be enabled with -DBUGFIX=1.

```C
// gcc -g -Ilibressl-2.3.1-windows\include test.c -ltls-9 -lws2_32
// Build with -DBUGFIX=1 and you should see a regular error message

#include <tls.h>
#include <stdio.h>
#include <winsock2.h>

int main()
{
  int err;

  if (tls_init() != 0) {
    fprintf(stderr, "Failed to init");
    return -1;
  }

#ifdef BUGFIX
  WSADATA wsaData;
  WORD version = MAKEWORD(2,2);
  err = WSAStartup(version, &wsaData);
  if (err != 0) {
    fprintf(stderr, "WSAStartup failed\n");
    return -1;
  }
#endif

  struct tls *ctx = tls_client();
  if (ctx == NULL) {
    fprintf(stderr, "tls_client: %s", tls_error(ctx));
    return -1;
  }

  err = tls_connect(ctx, "www.google.com", "443");
  if (err) {
    fprintf(stderr, "tls_client: %s", tls_error(ctx));
    return -1;
  }
  // It might not fail immediatly, force handshake
  tls_handshake(ctx);
  return 0;
}
```

Grepping the source code only reveals two occurrences of `WSAStartup` in [BIO_sock_init()](https://github.com/libressl-portable/portable/blob/a7f031ba55ac4a69263000357eb7f6d7fb88101a/crypto/compat/b_win.c#L20) which is only used in apps/openssl/openssl.c.

In Unix BIO_sock_init always [returns 1](https://github.com/libressl-portable/openbsd/blob/37759485f52993eb812898ccd70fc42cd92cdad5/src/lib/libssl/src/crypto/bio/b_posix.c#L71) one of the following should work

1. call `BIO_sock_init()` from either `tls_init()`, or maybe `SSL_library_init()` is the right place?
2. Remove `BIO_sock_init()` and `BIO_sock_cleanup()` and call `WSAStartup` from `SSL_library_init()`

**Comment by sodabrew** [comment]
Your code looks correct there, simply remove the `#ifdef BUGFIX` because this isn't a bug.

Your application should initialize the system as needed. Regular OpenSSL does not call WSAStartup for you, either, so it's not like LibreSSL removed something that was previously in the OpenSSL codebase.

**Comment by equalsraf** [comment]
Fair point about OpenSSL. But libtls is a new API, and completely independent from the rest, which is why I found this to be unexpected.

**Comment by busterb** [comment]
If you're using libtls, it makes sense to not need to call the libssl/crypto APIs directly. Calling BIO_sock_init() from tls_init() is probably the best thing to do:

```
Index: tls.c
===================================================================
RCS file: /cvs/src/lib/libtls/tls.c,v
retrieving revision 1.34
diff -u -p -u -p -r1.34 tls.c
--- tls.c       7 Oct 2015 23:25:45 -0000       1.34
+++ tls.c       3 Jan 2016 09:54:28 -0000
@@ -44,6 +44,9 @@ tls_init(void)
        SSL_load_error_strings();
        SSL_library_init();
 
+       if (BIO_sock_init() != 1)
+               return (-1);
+
        if ((tls_config_default = tls_config_new()) == NULL)
                return (-1);
```

Does this look ok @4a6f656c ?

**Comment by busterb** [comment]
Fixed here: https://github.com/libressl-portable/openbsd/commit/78b31f50849c1febd0065c06c52a18af1e5d508d

**Comment by sodabrew** [comment]
Alright! Nice convenience for the new tls api!
