### ISSUE TITLE
2.3.2 which version of chacha20 used ?

### ISSUE THREAD

**Issue by centminmod** [libressl-portable/portable#170]
From https://community.letsencrypt.org/t/chacha20-poly1305/9592/7

>  I just installed libressl-2.3.2 and found the available chacha20_poly1305 to use the old IDs 0xcc13–0xcc15 instead of 0xcca8–0xccaa.

```
$ openssl version
LibreSSL 2.3.2
$ openssl ciphers -V CHACHA20
      0xCC,0x14 - ECDHE-ECDSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=ECDSA Enc=ChaCha20-Poly1305 Mac=AEAD
      0xCC,0x13 - ECDHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=ECDH     Au=RSA  Enc=ChaCha20-Poly1305 Mac=AEAD
      0xCC,0x15 - DHE-RSA-CHACHA20-POLY1305 TLSv1.2 Kx=DH       Au=RSA  Enc=ChaCha20-Poly1305 Mac=AEAD
```

**Comment by busterb** [comment]
We are still using the pre-IETF version.

**Comment by Sp1l** [comment]
Any plans to update to the IETF release version?

Additional, the assembly version seems to be properly licensed to include in LibreSSL. Any plans to include this ASM code as well?

**Comment by centminmod** [comment]
thanks @busterb - hopefully updated soon !

**Comment by hdatma** [comment]
Last Updated:  2016-02-29
https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml

**Comment by 4a6f656c** [comment]
Both the pre-IETF and IETF ChaCha20-Poly1305 cipher suites are now supported in -current/master:

https://github.com/libressl-portable/openbsd/commit/01f65900b851ea55b938df9ea91a4bf4ec48d4f3

I would expect this to appear in the 2.4.x release.
