### ISSUE TITLE
Error with generating gost CA

### ISSUE THREAD

**Issue by zerocool1992** [libressl-portable/portable#173]
openssl req -newkey gost2001 -pkeyopt paramset:A -passout pass:aofvlgzm -subj  «/C=US/ST=SOMESTATEL=SOMECITYO=foo_bar/OU=foo_bar/CN=developer emailAddress=someMail@gmail.com» -new

I have got this error 
certificate_signing_request.csr Generating a 1024 bit GOST2001 private key Error Generating Key 140568465020576:error:32073073:GOST routines:PKEY_GOST01_PARAMGEN:no parameters set:gost/gostr341001_pmeth.c:193:

**Comment by 4a6f656c** [comment]
Both the "dgst" and "paramset" options need to be specified (the order is also important):

$ openssl genpkey -algorithm gost2001 -pkeyopt dgst:streebog256 -pkeyopt paramset:A -text

That said, It would be nice if the error was clearer (unfortunately that means adding new error codes/string) and we could potentially set a sane default digest algorithm...

**Comment by mikhailnov** [comment]
+1 for it being clearer. Thanks for the solution.
