### ISSUE TITLE
LibreSSL does not include SSL_get_server_tmp_key

### ISSUE THREAD

**Issue by lluixhi** [libressl-portable/portable#181]
This is in OpenSSL 1.0.2. Are there any plans on adding it?

It's used, at least in NodeJS, to check Diffie-Hellman keys so you can reject those keys which are less than a specified minDHSize, for example rejecting connections with a 1024 bit key, but accepting those with a 2048+ bit key.

**Comment by v4hn** [comment]
I believe this short-coming makes qt5.7 currently fail to build with libressl out of the box.
It would be nice to see this supported in libressl

**Comment by 4a6f656c** [comment]
SSL_get_server_tmp_key() now exists in LibreSSL.
