### ISSUE TITLE
Solaris 10 (coredumps)

### ISSUE THREAD

**Issue by mihailp** [libressl-portable/portable#191]
I need Solaris 10 support

0.
LibreSSL 2.3.3
solaris 10, 150400-24
gcc

1. compiled ok
2. failed to run
# ./openssl version
Segmentation Fault (core dumped)

3.
# ldd ./openssl 
        libssl.so.38 =>  /usr/local/libressl-mpech/lib/libssl.so.38
        libcrypto.so.37 =>       /usr/local/libressl-mpech/lib/libcrypto.so.37
        libnsl.so.1 =>   /lib/libnsl.so.1
        libsocket.so.1 =>        /lib/libsocket.so.1
        libresolv.so.2 =>        /lib/libresolv.so.2
        libdl.so.1 =>    /lib/libdl.so.1
        librt.so.1 =>    /lib/librt.so.1
        libc.so.1 =>     /lib/libc.so.1
        libgcc_s.so.1 =>         /opt/csw/lib/libgcc_s.so.1
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libscf.so.1 =>   /lib/libscf.so.1
        libaio.so.1 =>   /lib/libaio.so.1
        libdoor.so.1 =>  /lib/libdoor.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        libm.so.2 =>     /lib/libm.so.2
        /platform/SUNW,Sun-Blade-1000/lib/libc_psr.so.1
        /platform/SUNW,Sun-Blade-1000/lib/libmd_psr.so.1

4. all above works in Solaris 11 as mentioned.

**Comment by mihailp** [comment]
# dbx - core
Corefile specified executable: "/export/install/libressl-2.3.3/apps/openssl/.libs/openssl"
For information about new features see `help changes'
To remove this message, put `dbxenv suppress_startup_message 7.6' in your .dbxrc
Reading openssl
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
core file header read successfully
Reading ld.so.1
Reading libssl.so.38.0.0
Reading libcrypto.so.37.0.0
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9f)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
Reading libnsl.so.1
Reading libsocket.so.1
Reading libresolv.so.2
Reading libdl.so.1
Reading librt.so.1
Reading libc.so.1
Reading libgcc_s.so.1
Reading libaio.so.1
Reading libmd.so.1
Reading libc_psr.so.1
program terminated by signal SEGV (no mapping at the fault address)
0xffffffffffffffff:     <bad address 0xffffffffffffffff>
(dbx) Use `exit'
(dbx) exit
dbx: internal warning: td_ta_clear_event() failed -- debugger service failed
dbx: internal warning: td_ta_sync_tracking_enable(0) failed -- debugger service failed

# file .libs/openssl 
.libs/openssl:  ELF 32-bit MSB executable SPARC32PLUS Version 1, V8+ Required, dynamically linked, not stripped

**Comment by kinichiro** [comment]
Hi,

So, you are working on Solaris10(sparc), and what did you do ? like this ?
<pre>
./configure --prefix=/usr/local/libressl-mpech
make check
make install
</pre>

Did regression tests by `make check` pass all ?

Does your libssl.so.38 and libcrypto.so.37 exist in /usr/local/libressl-mpech/lib/ ?

Are you setting LD_LIBRARY_PATH=/usr/local/libressl-mpech/lib/ ?
Don't you set LD_LIBRARY_PATH on your Solaris11 ?

With dbx, you can use `where` command after reading core file, before exit soon.

Regards,

**Comment by mihailp** [comment]
> So,
>  you are working on Solaris10(sparc), and what did you do ? like this ?
> ./configure --prefix=/usr/local/libressl-mpech
> make check
> make install
yes, on solaris 10 and 11

> Did regression tests by make check pass all ?
Solaris 10
http://pastebin.com/bk7JttxK

Solaris 11
http://pastebin.com/N8aAGnVe

> Does your libssl.so.38 and libcrypto.so.37 exist in /usr/local/libressl-mpech/lib/ ?
Yes, of course, as use see ldd output

> Are you setting LD_LIBRARY_PATH=/usr/local/libressl-mpech/lib/ ?
> Don't you set LD_LIBRARY_PATH on your Solaris11 ?
should work out of box

>With dbx, you can use where command after reading core file, before exit soon.
# dbx - core 
Corefile specified executable: "/export/install/libressl-2.3.3/apps/openssl/.libs/./openssl"
For information about new features see `help changes'
To remove this message, put `dbxenv suppress_startup_message 7.6' in your .dbxrc
Reading openssl
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
core file header read successfully
Reading ld.so.1
Reading libssl.so.38.0.0
Reading libcrypto.so.37.0.0
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0xf2)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9f)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
dbx: warning: unknown location expression code (0x9e)
Reading libnsl.so.1
Reading libsocket.so.1
Reading libresolv.so.2
Reading libdl.so.1
Reading librt.so.1
Reading libc.so.1
Reading libgcc_s.so.1
Reading libaio.so.1
Reading libmd.so.1
Reading libc_psr.so.1
program terminated by signal SEGV (no mapping at the fault address)
0xffffffffffffffff:     <bad address 0xffffffffffffffff>
(dbx) where
  [1] 0x0(0x0, 0x892a0, 0x892d8, 0x0, 0x0, 0x0), at 0x0 
  [2] CRYPTO_new_ex_data(0x0, 0x892a0, 0x892d8, 0x0, 0xff292a00, 0xff26a4d8), at 0xff15181c 
  [3] BIO_set(0x892a0, 0xff26a790, 0xea6e8, 0x0, 0x892d8, 0xfef4c5d8), at 0xff170a20 
  [4] BIO_new(0x892a0, 0x0, 0x0, 0x0, 0x0, 0x892a0), at 0xff170a88 
  [5] BIO_new_fp(0x890a0, 0x0, 0x0, 0x0, 0x0, 0x87f58), at 0xff174c64 
  [6] main(0x1, 0xffbffd0c, 0x88000, 0x8922c, 0xff290180, 0x89000), at 0x59140 
(dbx)

**Comment by kinichiro** [comment]
Hi,

You said "1.compiled ok" at your first post,
but almost regression tests by `make check` fail with core dumped on your Solaris10(sparc).

only 8 tests passed.
(arc4randomforktest, explicit_bzero, ideatest, optionstest,
 poly1305test, randtest, timingsafe, utf8test)

I think you should check why regression tests fail with segmentaion fault
before thinking of `./openssl version` core dumped on your Solaris10(sparc) 150400-24 .

below is part of your solaris10 log. ( http://pastebin.com/bk7JttxK )
<pre>
...
FAIL: aeadtest.sh
FAIL: aes_wrap
PASS: arc4randomforktest.sh
../test-driver: line 107:  3908 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: asn1test
FAIL: asn1time
../test-driver: line 107:  3946 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: base64test
FAIL: bftest
../test-driver: line 107:  3984 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: bntest
FAIL: bytestringtest
../test-driver: line 107:  4022 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: casttest
FAIL: chachatest
../test-driver: line 107:  4060 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: cipher_list
../test-driver: line 107:  4079 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: cipherstest
../test-driver: line 107:  4098 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: clienttest
FAIL: cts128test
FAIL: destest
../test-driver: line 107:  4155 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: dhtest
../test-driver: line 107:  4174 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: dsatest
../test-driver: line 107:  4193 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: ecdhtest
../test-driver: line 107:  4212 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: ecdsatest
../test-driver: line 107:  4231 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: ectest
../test-driver: line 107:  4250 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: enginetest
FAIL: evptest.sh
PASS: explicit_bzero
../test-driver: line 107:  4294 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: exptest
FAIL: gcm128test
../test-driver: line 107:  4332 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: gost2814789t
../test-driver: line 107:  4351 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: hmactest
PASS: ideatest
FAIL: igetest
../test-driver: line 107:  4408 Bus Error               (core dumped) "$@" > $log_file 2>&1
FAIL: md4test
../test-driver: line 107:  4427 Bus Error               (core dumped) "$@" > $log_file 2>&1
FAIL: md5test
../test-driver: line 107:  4446 Bus Error               (core dumped) "$@" > $log_file 2>&1
FAIL: mont
PASS: optionstest
../test-driver: line 107:  4484 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: pbkdf2
../test-driver: line 107:  4503 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: pkcs7test
PASS: poly1305test
FAIL: pq_test.sh
PASS: randtest
FAIL: rc2test
../test-driver: line 107:  4585 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: rc4test
ERROR: rfc5280time_small.test - too few tests run (expected 2, got 0)
ERROR: rfc5280time_small.test - exited with status 1
../test-driver: line 107:  4614 Bus Error               (core dumped) "$@" > $log_file 2>&1
FAIL: rmdtest
../test-driver: line 107:  4633 Bus Error               (core dumped) "$@" > $log_file 2>&1
FAIL: sha1test
../test-driver: line 107:  4652 Bus Error               (core dumped) "$@" > $log_file 2>&1
FAIL: sha256test
../test-driver: line 107:  4671 Bus Error               (core dumped) "$@" > $log_file 2>&1
FAIL: sha512test
FAIL: ssltest.sh
FAIL: testdsa.sh
FAIL: testenc.sh
FAIL: testrsa.sh
PASS: timingsafe
PASS: utf8test
../test-driver: line 107:  4752 Segmentation Fault      (core dumped) "$@" > $log_file 2>&1
FAIL: verifytest
============================================================================
Testsuite summary for libressl 2.3.3
============================================================================
# TOTAL: 54
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  44
# XPASS: 0
# ERROR: 2
...
</pre>

Sorry, I don't have Solaris10 environment.

Regards,

**Comment by mihailp** [comment]
I found it.
installing latest 10recommended first.
stay tuned.

**Comment by mihailp** [comment]
1. it was local problem
2. works on new installed solaris 10, out of box
3. update list, it works on solaris 10 too
# ./openssl version && uname -a
LibreSSL 2.3.3
SunOS ramona 5.10 Generic_150400-35 sun4u sparc SUNW,Sun-Fire-V210

**Comment by kinichiro** [comment]
Hi,
It is good to hear that.

BTW, could you try 64bit build on your new installed Solaris10(sparc), please ?
If you could have a time to try on.

<pre>
./configure 'CFLAGS=-m64' 'LDFLAGS=-ldl'
make check
</pre>

Does it succeed ?
Or fail with "undefined symbol dl_iterate_phdr" ?

I would like to know if `dl_iterate_phdr` is available on Solaris10(sparc) in 64-bit mode.

Regards,

**Comment by mihailp** [comment]
failed some way
http://pastebin.com/NKUnwEbp

**Comment by kinichiro** [comment]
@mihailp Thanks. It helps a lot for me.
