### ISSUE TITLE
libtls man page misses 4 functions in FUNCTIONS section

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#193]
Hi,

These 4 libtls APIs are listed in SYNOPSIS section, but not described in FUNCTIONS section.
- `tls_config_set_dheparams`
- `tls_config_set_ecdhecurve`
- `tls_config_set_verify_depth`
- `tls_reset`

It is good that we could read how they work or parameters (ex. "auto", "legacy", "none", etc.) in man page.

Thanks.

**Comment by kinichiro** [comment]
Hi,
These are small things, though,

"(Server and client)" and "(Client and server)" could be unified to "(Client and Server)",
if case-sensitive and case-insensitive doesn't have special meaning.

>・ tls_config_clear_keys() clears any secret keys from memory. (Server)

- I feel `private` is better than `secret`, isn't it ?
- This function is used by both "(Client and Server)", no ?

>・ tls_peer_cert_hash()

- misses "(Client and Server)"

>・ tls_conn_version()

- misses "(Client and Server)"

Best regards,

**Comment by 4a6f656c** [comment]
All of these functions are now documented.
