### ISSUE TITLE
Memory leak in arc4random_win.h

### ISSUE THREAD

**Issue by mad-rain** [libressl-portable/portable#200]
Hi,

We're seeing two memory leaks in our project on Windows. There are two calloc calls in arc4random_win.h in _rs_allocate, but there're no free calls at all. This is no a critical bug, but a bit annoying.

```
static inline int
_rs_allocate(struct _rs **rsp, struct _rsx **rsxp)
{
	*rsp = calloc(1, sizeof(**rsp));
	if (*rsp == NULL)
		return (-1);

	*rsxp = calloc(1, sizeof(**rsxp));
	if (*rsxp == NULL) {
		free(*rsp);
		return (-1);
	}
	return (0);
}
```

**Comment by 4a6f656c** [comment]
They're not really memory leaks - the arc4random code calls _rs_allocate() once in order to allocate memory for the internal data structures. They can only be freed when arc4random is no longer going to be used (i.e. when the process is exiting), at which point they're going to be freed anyway.

**Comment by busterb** [comment]
On Tue, Jun 28, 2016 at 9:24 AM, Joel Sing <notifications@github.com> wrote:

> They're not really memory leaks - the arc4random code calls _rs_allocate()
> once in order to allocate memory for the internal data structures. They can
> only be freed when arc4random is no longer going to be used (i.e. when the
> process is exiting), at which point they're going to be freed anyway.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libressl-portable/portable/issues/200#issuecomment-229064919>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD6xbnFdn-_DfH_-sgX7ogSkd8Zdq5KLks5qQS6ZgaJpZM4I82jR>
> .
>
​Maybe something like this (VirtualAlloc is more akin to the mmap calls in
the other ports anyway). This should avoid flagging as a memory leak in the
heap checker.

​
RCS file: /cvs/src/lib/libcrypto/crypto/arc4random_win.h,v
retrieving revision 1.5
diff -u -p -r1.5 arc4random_win.h
--- arc4random_win.h    15 Jan 2015 06:57:18 -0000      1.5
+++ arc4random_win.h    29 Jun 2016 08:42:30 -0000
@@ -52,13 +52,16 @@ _getentropy_fail(void)
 static inline int
 _rs_allocate(struct _rs **rsp, struct _rsx **rsxp)
 {
-       *rsp = calloc(1, sizeof(**rsp));
+       *rsp = VirtualAlloc(NULL, sizeof(**rsp),
+                       MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);
        if (*rsp == NULL)
                return (-1);

-       *rsxp = calloc(1, sizeof(**rsxp));
+       *rsxp = VirtualAlloc(NULL, sizeof(**rsxp),
+                       MEM_RESERVE | MEM_COMMIT, PAGE_READWRITE);
        if (*rsxp == NULL) {
-               free(*rsp);
+               VirtualFree(*rsp, 0, MEM_RELEASE);
+               *rsp = NULL;
                return (-1);
        }
        return (0);

**Comment by bob-beck** [comment]
Does VirtualAlloc zero the memeory?

**Comment by busterb** [comment]
Yes it does!

**Comment by bob-beck** [comment]
then this sounds like the right approach

**Comment by 4a6f656c** [comment]
This should be addressed via r1.6 of crypto/arc4random_win.h.
