### ISSUE TITLE
FR: QUIC Crypto support

### ISSUE THREAD

**Issue by DigiAngel** [libressl-portable/portable#205]
Topic says it..thank you.

**Comment by donny-dont** [comment]
Hey @busterb is there any chance there's an update for this on the LibreSSL side?

**Comment by 4a6f656c** [comment]
The next LibreSSL release will have support for QUIC via the `SSL_QUIC_METHOD` interface, which BoringSSL and quictls provide.

**Comment by wlallemand** [comment]
@4a6f656c the HAProxy project is interested to test the QUIC stack with libressl, we already have an implementation which works with quictls, do you know when the libressl-portable respository will inherit this API? thanks.

**Comment by 4a6f656c** [comment]
This API is available in the LibreSSL 3.6.0 release.
