### ISSUE TITLE
Note on ASN1_STRING_get0_data

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#221]
Hello, 

OpenSSL 1.1.0 defines ASN1_STRING_get0_data, used by DANE in the new postfix 3.1.2. 
LibreSSL 2.4.2 does not define the same, and thus postfix fails to compile. 

Attached is my patch to compile postfix 3.1.1 with libressl 2.4.2 without errors. 

[tls.h.patch.txt](https://github.com/libressl-portable/portable/files/444657/tls.h.patch.txt)

**Comment by hdatma** [comment]
"set link library dependencies with MSVC, fixes #221"

Already included in release v2.4.2. 
OP uses v2.4.2

**Comment by 4a6f656c** [comment]
In the attached patch, I only see X509_up_ref() - am I missing something?

**Comment by 4a6f656c** [comment]
@hdatma ping?

**Comment by 4a6f656c** [comment]
Closing due to lack of response.
