### ISSUE TITLE
Undefined PATH_MAX with Visual Studio 2015

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#224]
Hi,
I noticed latest apps.c and ca.c using PATH_MAX, and this causes compilation error on Visual Studio 2015.
Seeing include/compat/dirent_msvc.h, PATH_MAX is equivalent to MAX_PATH, and MAX_PATH is defined 260 in minwindef.h.

How about adding PATH_MAX definition in `include/compat/limits.h` rather than including dirent_msvc.h ?

```
...
#endif

#ifdef _MSC_VER
#ifndef PATH_MAX
#define PATH_MAX 260
#endif
#endif

#ifdef __hpux
...
```

Thanks.

**Comment by kinichiro** [comment]
Hi,

I found another solution for this issue.
I would like to suggest adding below to include/compat/limits.h .

```diff
diff --git include/compat/limits.h include/compat/limits.h
index a3a04a5..754f80a 100644
--- include/compat/limits.h
+++ include/compat/limits.h
@@ -5,6 +5,10 @@

 #ifdef _MSC_VER
 #include <../include/limits.h>
+#include <windows.h>
+#ifndef PATH_MAX
+#define PATH_MAX MAX_PATH
+#endif
 #else
 #include_next <limits.h>
 #endif
```

I think including windows.h is fair to use MAX_PATH.

Thanks.

**Comment by Johnex** [comment]
Inside include/compat/dirent_msvc.h there is already a definition for PATH_MAX:
https://github.com/libressl-portable/portable/blob/8131b377bffdacb8789c78ef31160b3bf4ee054b/include/compat/dirent_msvc.h#L59

The problem seems to be that the file is only included in include/Makefile.am for AutoMake , but not in the CMakeLists for CMake, so we need some more includes in the CMakeLists.

**Comment by kinichiro** [comment]
I think that CMakeLists.txt only controls INSTALL process and does not
affect while building.

**Comment by Johnex** [comment]
Well CMake is the one that creates the projects, it adds the files to build into the project. If the dirent_msvc.h file is added to the projects that have PATH_MAX missing then they will build just fine.

**Comment by Johnex** [comment]
Well CMake does generate the projects, but it just adds all the C files, not the headers. So yeah either dirent_msvc.h should be included somewhere, or your suggestion :)

**Comment by Johnex** [comment]
With any include of windows.h, you should also #define WIN32_LEAN_AND_MEAN to avoid including a lot of junk:

```c++
#ifndef WIN32_LEAN_AND_MEAN
    #include <cderr.h>
    #include <dde.h>
    #include <ddeml.h>
    #include <dlgs.h>
    #ifndef _MAC
        #include <lzexpand.h>
        #include <mmsystem.h>
        #include <nb30.h>
        #include <rpc.h>
    #endif
    #include <shellapi.h>
    #ifndef _MAC
        #include <winperf.h>
        #include <winsock.h>
    #endif
    #ifndef NOCRYPT
        #include <wincrypt.h>
        #include <winefs.h>
        #include <winscard.h>
    #endif

    #ifndef NOGDI
        #ifndef _MAC
            #include <winspool.h>
            #ifdef INC_OLE1
                #include <ole.h>
            #else
                #include <ole2.h>
            #endif /* !INC_OLE1 */
        #endif /* !MAC */
        #include <commdlg.h>
    #endif /* !NOGDI */
#endif /* WIN32_LEAN_AND_MEAN */
```

So i would recommend this:

```diff
diff --git include/compat/limits.h include/compat/limits.h
index a3a04a5..754f80a 100644
--- include/compat/limits.h
+++ include/compat/limits.h
@@ -5,6 +5,10 @@

 #ifdef _MSC_VER
 #include <../include/limits.h>
+#define WIN32_LEAN_AND_MEAN
+#include <windows.h>
+#ifndef PATH_MAX
+#define PATH_MAX MAX_PATH
+#endif
 #else
 #include_next <limits.h>
 #endif
```

**Comment by kinichiro** [comment]
If we build in Win64 mode, "#define WIN32_LEAN_AND_MEAN" brings many redefinition messages (C4005).

```
cmake -G "Visual Studio 14 2015 Win64" ..
```

I don't think "#define WIN32_LEAN_AND_MEAN" is not needed here.

**Comment by Johnex** [comment]
Ok i see it too. I changed it to this:

```diff
diff --git include/compat/limits.h include/compat/limits.h
index a3a04a5..754f80a 100644
--- include/compat/limits.h
+++ include/compat/limits.h
@@ -5,6 +5,10 @@

 #ifdef _MSC_VER
 #include <../include/limits.h>
+#ifndef WIN32_LEAN_AND_MEAN
+#define WIN32_LEAN_AND_MEAN
+#endif
+#include <windows.h>
+#ifndef PATH_MAX
+#define PATH_MAX MAX_PATH
+#endif
 #else
 #include_next <limits.h>
 #endif
```

And then its fine :)

**Comment by Johnex** [comment]
Ah, but we have lean and mean set in CMake...

```cmake
if(WIN32)
	add_definitions(-Drestrict)
	add_definitions(-D_CRT_SECURE_NO_WARNINGS)
	add_definitions(-D_CRT_DEPRECATED_NO_WARNINGS)
	add_definitions(-D_REENTRANT -D_POSIX_THREAD_SAFE_FUNCTIONS)
-->	add_definitions(-DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0501) <--
	add_definitions(-DCPPFLAGS -DOPENSSL_NO_SPEED -DNO_SYSLOG -DNO_CRYPT)
endif()
```

So you can just make a pull with your diff 😄. I hadn't seen it before, i searched for it in the headers but not in CMake 😸.

**Comment by kinichiro** [comment]
I could verified that commit https://github.com/libressl-portable/portable/commit/cb63e633708e41d5b524962202977585ab8c1267 solved this issue.
I checked this with Visual Studio 2015.
And it worked fine with Intel C++ Compiler 17.0, too.
