### ISSUE TITLE
Use regex expressions to list sources in CMake

### ISSUE THREAD

**Issue by egorpugin** [libressl-portable/portable#226]
Hi,

Is there any reason to keep all files explicitly listed in `CMakeLists.txt`.
Maybe it's possible to replace them with `file(GLOB src "*.c" "*.h")` or something like that?
Also it's possible to exclude unneeded files after this command.

**Comment by kinichiro** [comment]
IMHO, Makefile should describe source files explicitly to indicate obvious what files are processed.
I think Using regular expression or file blog might bring unwanted file inclusion.
