### ISSUE TITLE
Download section on website not updated

### ISSUE THREAD

**Issue by KAMiKAZOW** [libressl-portable/portable#229]
http://www.libressl.org/releases.html is outdated. Maybe link to https://github.com/libressl-portable/portable/releases instead.

**Comment by bcook-r7** [comment]
It should be updated soon. Linking to github doesn't work because you can't directly build those auto-generated tarballs.

**Comment by bcook-r7** [comment]
It should be updated soon. Linking to github doesn't work because you can't directly build those auto-generated tarballs.

**Comment by 4a6f656c** [comment]
It's not really "outdated" - the releases have not been finalised/announced yet. There's also the release notes which are linked from the http://www.libressl.org/releases.html page (and not from github).
