### ISSUE TITLE
bn_print(3) conflicts with BN_print(3) on case-insensitive file system

### ISSUE THREAD

**Issue by 0-wiz-0** [libressl-portable/portable#231]
bn_print(3) (symlink to bn_dump(3)) conflicts with BN_print(3) (symlink to bn(3)) on case-insensitive file systems. OS X still defaults to a case-insensitive file system, so only the second symlink survives.
I'm not sure how to solve this, since both bn_print and BN_print exist and should be documented, but I wanted to report this, perhaps you have a smart idea.

**Comment by busterb** [comment]
theoretically running 'makewhatis' with the right arguments should still cause the right links to be created. See #429

**Comment by busterb** [comment]
Fixed in 1ea79d2a9fec76720158499f208258a43f57dbd8
