### ISSUE TITLE
"Make check" => "No rule to make target `/crypto/libcrypto.la', needed by `libssl.la'."

### ISSUE THREAD

**Issue by jkbullard** [libressl-portable/portable#232]
Sorry for what may just be noob ignorance, but I am having a problem building LibreSSL on OS X. I’m trying to build the libssl and libcrypto libraries as OpenSSL replacements to static-link into OpenVPN for [Tunnelblick](https://tunnelblick.net), a free/libre OpenVPN GUI for OS X.

I'm using OS X 10.11.6 and have the prerequisites described in portable-2.5.0/README.md. (My understanding is that I should use libressl-portable, not libressl-openbsd to build, since it is not for use on OpenBSD.)

Executing autogen.sh in libressl-portable appears to download the LibreSSL master branch source code (from where?), patch some files in that source code, and then do other fiddling that I assume is related to getting the source code prepared for building on OS X.

First, **a question**: Is there a way to skip the download, and use a copy of the LibreSSL source that is already on the build computer? (That is, a copy that I downloaded from ‘libressl-openbsd’ separately?)

Second, **the problem**: What am I doing wrong:
1. I created ‘target_folder’ in /Users/USERNAME/Desktop to hold the libraries.
2. I downloaded portable-2.5.0.tar.gz, expanded it, cd-ed to the expanded folder, and ran autogen.sh. The output from that looked OK.
3. I executed "./configure --prefix=/Users/USERNAME/Desktop/target_folder" and the output from that looked OK, too.

But when "make check" finished, target_folder was empty and ‘make check’ had ended with the following error:

```
make[1]: *** No rule to make target `/crypto/libcrypto.la', needed by `libssl.la'.  Stop.
make: *** [check-recursive] Error 1
```

Thanks in advance for any help.

**Comment by kinichiro** [comment]
Hi,

Release tar.gz and github repository are different in their structures.
github repository libressl-portable is structured to generate Release
tar.gz.
Maybe you downloaded this github repository.

To work with github repository libressl-portable,
Run dist.sh in your libressl-portable, then you can obtain
libressl-2.5.0.tar.gz.
Expand that libressl-2.5.0.tar.gz in your desired directory, then
"./configure", next "make check".

Or download Release tar.gz from here.
http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

Best regards,

**Comment by busterb** [comment]
I do not recommend using the tarballs from github - please use the release versions instead. It would be good if there was some way to disable them.
