### ISSUE TITLE
getentropy_linux.c: sysctl() fallback not that useful?

### ISSUE THREAD

**Issue by dwatteau** [libressl-portable/portable#238]
Hi,

I'm wondering whether there is any point in the sysctl() fallback in getentropy_linux.c.

It looks like most supported Linux distributions either have the new getrandom() API, or ``SYS__sysctl`` has already been fully disabled (i.e. ``CONFIG_SYSCTL_SYSCALL=n`` in the kernel, and thus syscall() returns ``ENOSYS``).  Debian 8 is in the particular case of neither having sysctl() nor getrandom(), for example.

Moreover, unless I'm mistaken, ``RANDOM_UUID`` isn't an excellent source of randomness, as it looks lile some of its bytes are hardcoded (well, I don't know if getentropy_fallback() is any better):
https://github.com/torvalds/linux/blob/5924bbecd0267d87c24110cbe2041b5075173a25/lib/uuid.c

Actually: I'm using some chrooted applications with LibreSSL on Debian 8. Although it doesn't have getrandom(), I though I was OK because of the sysctl() fallback. But actually it returns ``ENOSYS`` and so it uses getentropy_fallback(). If I reenable ``CONFIG_SYSCTL_SYSCALL``, sysctl() will work, but it doesn't look that random.

Am I right thinking that my best options are 1) having an OS where getrandom() is available or 2) bind ``/dev/urandom`` in the chroot? Because getentropy_sysctl() and getentropy_fallback() look a bit risky to me.

Thanks.

**Comment by bob-beck** [comment]
A sane linux should probably have getrandom() or syssctl() available. 

fallback exists exactly because sometimes people configure linux systems insanely.

**Comment by dwatteau** [comment]
> A sane linux should probably have getrandom() or syssctl() available. 

> sane linux ... syssctl() available

> sane ... sysctl()

And so here was my question again: is the sysctl() fallback _sane_ in the first place?

Because it looks like it's querying a UUID _which has some hardcoded bytes_ (maybe we are avoiding those bytes, or maybe we don't care for them, I don't know).

Then, in case it's not that sane, do we really want to keep it?

**Comment by bob-beck** [comment]
for the usage here we do not care.
