### ISSUE TITLE
undefined reference to `SSL_set_min_proto_version'

### ISSUE THREAD

**Issue by rofl0r** [libressl-portable/portable#247]
today lynx-2.8.9-dev10 came out but it fails to link against libressl 2.4.x series:

```
.././WWW/Library/Implementation/libwww.a(HTTP.o): In function `HTLoadHTTP':
HTTP.c:(.text.HTLoadHTTP+0x3d8): 
undefined reference to `SSL_set_min_proto_version'
collect2: error: ld returned 1 exit status
```
the code in question looks like:
```c
#if OPENSSL_VERSION_NUMBER >= 0x10100000L
            SSL_set_min_proto_version(handle, TLS1_1_VERSION);
#else
            SSL_set_options(handle, SSL_OP_NO_TLSv1);
#endif
```

**Comment by AliceWonderMiscreations** [comment]
Change first line to

    #if OPENSSL_VERSION_NUMBER >= 0x10100000L && !defined (LIBRESSL_VERSION_NUMBER)

**Comment by chdiza** [comment]
This worked for me, in lynx 2.8.9dev11.  Thanks!

**Comment by 4a6f656c** [comment]
The SSL{,_CTX}_set_{min,max}_proto_version() functions have been added to LibreSSL's libssl.

**Comment by hasufell** [comment]
@4a6f656c which version will have it? 2.5.4 still fails
