### ISSUE TITLE
panic error from dovecot 2.2.27 using libressl 2.4.4

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#252]
The following results from applying the well-known patch for dovecot 2.2.26.0, adapted to the line numbers of 2.2.27. The configuration is clean (no errors, no warnings). The compilation is also clean, apart from a minor issue with var-expand.c. The runtime crashes and burns. This is a test:

[...]
test_load_v1_public_key .............................................. : ok
Panic: file randgen.c: line 21 (random_fill): assertion failed: (init_refcount > 0)
Error: Raw backtrace: 2   libdcrypt_openssl.so                0x0000000105cddd24 default_fatal_finish + 36 -> 3   libdcrypt_openssl.so                0x0000000105cddafd default_fatal_handler + 61 -> 4   libdcrypt_openssl.so                0x0000000105cde069 i_panic + 169 -> 5   libdcrypt_openssl.so                0x0000000105d0b10c random_fill + 220 -> 6   libdcrypt_openssl.so                0x0000000105cd463d dcrypt_openssl_store_private_key + 1037 -> 7   test-crypto                         0x0000000105c51f54 test_load_v2_key + 580 -> 8   test-crypto                         0x0000000105c5390e test_run + 142 -> 9   test-crypto                         0x0000000105c50921 main + 81 -> 10  libdyld.dylib                       0x00007fff95dc0255 start + 1 -> 11  ???                                 0x0000000000000001 0x0 + 1
/bin/sh: line 1: 24043 Abort trap: 6           ./$bin
make[2]: *** [check-test] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
~

**Comment by 4a6f656c** [comment]
Again, I'm not sure what it is that you're wanting libressl-portable to do here - while we aim to provide API compatibility with OpenSSL 1.0, some software still needs to be modified in order to work correctly with LibreSSL (especially if it has been changed to work with OpenSSL 1.1). But this is generally outside the scope of the LibreSSL project, unless there is a specific change that you're proprosing we make to the libssl/libcrypto APIs.

**Comment by 4a6f656c** [comment]
Closing due to lack of response.

**Comment by hdatma** [comment]
Did you read the OP?

**Comment by sthen** [comment]
Dovecot 2.2.27 works fine with the patches that are in the OpenBSD ports repo.

If you're going to try to use an old patch directly against new code, you'll need to check for any new instances of what the patch is trying to fix. Relative to 2.2.26.0 there was a new "#if OPENSSL_VERSION_NUMBER >= 0x10100000L\nOPENSSL_cleanup()\n#endif" that also needs modifying.

**Comment by hdatma** [comment]
I am not on OpenBSD. 
I am the author of the 2.2.26.0 patch.
The OP still holds.

**Comment by hdatma** [comment]
This issue is still open!!!

**Comment by 4a6f656c** [comment]
@hdatma - I read the original comment and replied, however you never responded. You applied an old patch to a new version of postfix and it broke, which means you get to keep both halves. I'm still not sure what you expect the LibreSSL project to do about this - if you do not wish to reuse appropriate patches (the references to the OpenBSD ports tree were simply to point you in the direction of known working code), or do not want to fix the software to work with LibreSSL yourself, you may be better off using a platform that provides ports of the packages that you wish to use.
