### ISSUE TITLE
libcrypto/ec/ecp_nistp256.c etc. are not available in the portable version.

### ISSUE THREAD

**Issue by chenshuo** [libressl-portable/portable#259]
When doing ECDHE_RSA handshaking with P-256 on x86-64, there is a 30% performance difference:

541.8 handshakes/s (with `EC_GFp_nistp256_method`) vs. 412.7 handshakes/s (generic EC methods).

Note, the flag to turn it on in upstream OpenSSL is `enable-ec_nistp_64_gcc_128`.

**Comment by busterb** [comment]
Hmm, I believe this is just an oversight. Checking it out.

**Comment by busterb** [comment]
Addressed in 91f771f, thanks.

**Comment by chenshuo** [comment]
FYI, there are further improvements of P-256 in upstream 1.1.0 and 1.0.2 branches, eg. https://github.com/openssl/openssl/commit/4d3fa06fce52682bfbc503c7ded2d0289e3f8cde .
The performance benchmark results look promising: https://boringssl.googlesource.com/boringssl/+/18954938684e269ccd59152027d2244040e2b819
