### ISSUE TITLE
libssl won't build on Windows because strsep.c is not referenced

### ISSUE THREAD

**Issue by vsajip** [libressl-portable/portable#265]
While `strsep.c` is included with the tarball, the `CMakeLists.txt` for `ssl` doesn't mention it (it's in the `tls` subtree). Hence `libssl.dll` can't be built because of a linker error, due to the `strsep` reference (in `t1_lib.obj`).

Adding `../tls/strsep.c` to the source set for `ssl` resolves the problem, but I'm not sure if that's the correct fix.

**Comment by busterb** [comment]
we're working on it already in https://github.com/libressl-portable/portable/pull/264 , thanks

**Comment by kinichiro** [comment]
Now this issue is solved, and I could build with Visual Studio 2015.

**Comment by kinichiro** [comment]
Thanks for your report. I will close this issue since this was resolved.
