### ISSUE TITLE
Hybrid RSA and ECDSA certificates with NginX (and libressl)

### ISSUE THREAD

**Issue by tohn** [libressl-portable/portable#267]
As explained in [this article](https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/), one can now use multiple certificates in nginx (since [1.11.0](https://nginx.org/en/CHANGES)).
So far it works only with openssl >= 1.0.2.
If this is not yet available in libressl (I couldn't find any hint that it's already implemented), are there plans for this?
Thanks in advance! :)

**Comment by lukvdborne** [comment]
For what it's worth: it worked for me with nginx 1.12, though it seems to send all intermediate CA certs twice. I'm not sure if this is caused by nginx or by libressl, as I've never used it with openssl and it was just a brief experiment.

**Comment by mnordhoff** [comment]
@lukvdborne To support different chains, Nginx uses `SSL_CTX_add0_chain_cert()` added in OpenSSL 1.0.2. Otherwise they're mashed together.

**Comment by O2Graphics** [comment]
Any idea when SSL_CTX_add0_chain_cert() will also be added to LibreSSL?

**Comment by 4a6f656c** [comment]
These APIs are now in LibreSSL and will be available in the upcoming 2.9.1 release.
