### ISSUE TITLE
tls_handshake segfaults if socket not set up properly

### ISSUE THREAD

**Issue by vsajip** [libressl-portable/portable#270]
My program called `tls_handshake()` after I accidentally commented out a line that did a `tls_connect_socket()`. This resulted in a crash (segfault / access violation) where it should have returned a more meaningful error. The beginning of `tls_handshake_client()`:

```C
int
tls_handshake_client(struct tls *ctx)
{
	X509 *cert = NULL;
	int ssl_ret;
	int rv = -1;

	if ((ctx->flags & TLS_CLIENT) == 0) {
		tls_set_errorx(ctx, "not a client context");
		goto err;
	}

	ERR_clear_error();
	if ((ssl_ret = SSL_connect(ctx->ssl_conn)) != 1) {
		rv = tls_ssl_error(ctx, ctx->ssl_conn, ssl_ret, "handshake");
		goto err;
	}
```

If no socket has been set up, `ctx->ssl_conn` is `NULL`, but there is no check for this. `SSL_connect` dereferences the `NULL` pointer.

I realise my usage was incorrect, but IMO a crash should not be the result.

**Comment by 4a6f656c** [comment]
tls_handshake() now ensures that a client context has been connected prior to attempting a TLS handshake.
