### ISSUE TITLE
tls_load_file() allocates memory, but there's no safe way provided to free it

### ISSUE THREAD

**Issue by vsajip** [libressl-portable/portable#273]
`tls_load_file()` allocates memory using `malloc()` / `calloc()`, and this memory is returned to the caller. However, there seems to be no way for the caller to free the memory using the same allocator which was used to allocate it. In theory the caller could just call `free()` on the returned value, but this can't always be relied on. It can be a problem in any environment where an application using `libtls` is not using the same allocator as `libtls`, perhaps because it was linked differently. This is a not uncommon problem on Windows, where an application's heap can be different from a shared library's heap.

A `tls_free_file()` or similar should be provided in the API which calls `free()`.

**Comment by 4a6f656c** [comment]
I've just added a tls_unload_file() function that can be used for this purpose.
