### ISSUE TITLE
Failure in update.sh

### ISSUE THREAD

**Issue by vsajip** [libressl-portable/portable#279]
I just downloaded the 2.5.1 release tarball from here and unpacked it into a folder. Running `./autogen.sh` fails in `update.sh`:
```
...
copying libssl source
copying tests
patching file tests/aeadtest.c
patching file include/openssl/bio.h
patching file apps/nc/netcat.c
Hunk #1 succeeded at 65 with fuzz 2.
Hunk #3 FAILED at 154.
Hunk #7 succeeded at 865 (offset 17 lines).
Hunk #8 succeeded at 882 (offset 17 lines).
Hunk #9 succeeded at 956 (offset 17 lines).
Hunk #10 succeeded at 980 (offset 17 lines).
Hunk #11 succeeded at 1442 (offset 17 lines).
Hunk #12 succeeded at 1485 (offset 17 lines).
Hunk #13 succeeded at 1689 (offset 17 lines).
1 out of 13 hunks FAILED -- saving rejects to file apps/nc/netcat.c.rej
```
Here's the failing hunk:
```
--- apps/nc/netcat.c.orig	Sat Nov  5 14:00:01 2016
+++ apps/nc/netcat.c	Sat Nov  5 15:28:35 2016
@@ -154,7 +160,7 @@
 	struct servent *sv;
 	socklen_t len;
 	struct sockaddr_storage cliaddr;
-	char *proxy;
+	char *proxy = NULL;
 	const char *errstr, *proxyhost = "", *proxyport = NULL;
 	struct addrinfo proxyhints;
 	char unix_dg_tmp_socket_buf[UNIX_DG_TMP_SOCKET_SIZE];
```

It appears that the patch is out of date, because `update.sh` doesn't checkout the OpenBSD sources as they were at the time of release, but rather the latest sources. This seems bound to fail from time to time.

The same thing happens if you download the latest sources rather than 2.5.1 (`portable-master.zip`).

**Comment by vsajip** [comment]
The fix for #280 is welcome, as it means downloads from master or clones will work - thanks very much. But that doesn't appear to fix the problem described here long-term. For example, the next time the `openbsd` code diverges sufficiently from the time when a particular release is done, the unpacked tarball from that release will also fail to update with the same problem, if `patch` fails - as well it might, if the divergence is too great.

Wouldn't it be better to do the following? Just before a release is tagged, create/update a file `OPENBSD_REVISION` which contains the Git hash of the `openbsd` repo. Then, in `update.sh`, instead of doing
```
(cd openbsd
 git checkout $openbsd_branch
 git pull --rebase)
```
You could effectively do `git checkout` referencing the contents of `OPENBSD_REVISION`. Don't want to change the workflow when you're working not with a download, but with a repo? Just gate the above logic with whether there is a `.git` directory present - it won't be there in an unpacked tarball. So people working with a repo continue to get the current logic (get the latest `openbsd` code). That can fail, too, but at least release tarballs won't be broken.

**Comment by busterb** [comment]
This already happens when the release is put into stable branches and it points to unchanging tags. I'd really rather not introduce the overhead of constantly bumping OPENBSD_REVISION in master, when it's not supposed to be stable.

What tarball are you talking about? Official release tarballs do not contain the development 'update.sh' script, and should not updated. Ignore the github release tarballs, they are bogus, and I would disable them if I could.

If you want time-synced checkouts between portable and openbsd, a variant of the code in gen-openbsd-tags.sh might do the trick.

**Comment by vsajip** [comment]
> Official release tarballs do not contain the development 'update.sh' script, and should not updated. Ignore the github release tarballs, they are bogus, and I would disable them if I could.

Ah, that's the bit I was missing / misunderstanding. Thanks. I was just trying to build 2.5.1 on a older machine to see if I could build it successfully there, and picked the tarball from GitHub. I will use https://www.libressl.org/releases.html in future - I assume those are the official tarballs.

**Comment by busterb** [comment]
That's right, thanks.
