### ISSUE TITLE
tls.h - missing size_t/ssize_t with Intel compiler

### ISSUE THREAD

**Issue by Johnex** [libressl-portable/portable#282]
Hi!
So using the latest libressl-2.5.1 zip from releases, i managed to compile all the libraries fine, but when i try to use them, then there is a problem.

I tried just including TLS.h in a project and i get:

```
tls.h(75): error : expected a type specifier
    typedef ssize_t (*tls_read_cb)(struct tls *_ctx, void *_buf, size_t _buflen,
                     ^

tls.h(75): error : function returning function is not allowed
    typedef ssize_t (*tls_read_cb)(struct tls *_ctx, void *_buf, size_t _buflen,
                                   ^

tls.h(77): error : function returning function is not allowed
    typedef ssize_t (*tls_write_cb)(struct tls *_ctx, const void *_buf,
                      ^

tls.h(160): error : identifier "tls_read_cb" is undefined
        tls_read_cb _read_cb, tls_write_cb _write_cb, void *_cb_arg);
        ^

tls.h(167): error : identifier "tls_read_cb" is undefined
    int tls_connect_cbs(struct tls *_ctx, tls_read_cb _read_cb,
                                          ^

tls.h(170): error : function returning function is not allowed
    ssize_t tls_read(struct tls *_ctx, void *_buf, size_t _buflen);
            ^

tls.h(171): error : function returning function is not allowed
    ssize_t tls_write(struct tls *_ctx, const void *_buf, size_t _buflen);
            ^

```

Any ideas what could be wrong?

CMake'd libraries using:

`cmake -G"Visual Studio 14 2015" -T"Intel C++ Compiler 17.0" ..`

And Compiled as Multi-threaded (/MT)

**Comment by busterb** [comment]
Try adding:
`#include <stdlib.h>`
before you include tls.h

**Comment by Johnex** [comment]
Tried it now, same errors. I tried adding #include <stdlib.h> into TLS.h even, and it still gives me the same errors even in the editor:

![screenshot 2017-02-08 23 39 58](https://cloud.githubusercontent.com/assets/7826974/22760762/1ff6d012-ee58-11e6-880c-96225d4dc3f6.png)

**Comment by kinichiro** [comment]
You can refer to tests/tlstest.c.
https://github.com/libressl-portable/openbsd/blob/master/src/regress/lib/libtls/tls/tlstest.c

It includes stdio, string and unistd before tls.h.

**Comment by Johnex** [comment]
Ok so i found the problem. TLS requires that unistd.h but only for ssize_t, so i did:

```
#define ssize_t int
#include <tls.h>
```

And now it works. Is there a reason for using ssize_t in the first place? Seems unnecessary?

**Comment by busterb** [comment]
The underlying type of ssize_t depends on the CPU and OS, so hardcoding this is incorrect.

ssize_t is used to return either a number of bytes or an error (-1). While it may seem implausible to process > 2GB in a single callback, it is defined in the POSIX spec that the underlying read/recv calls return ssize_t:

http://pubs.opengroup.org/onlinepubs/009695399/functions/read.html

True, Windows only expect to recv/read a max of 'int' bytes, but this is intended to be a portable interface, hence ssize_t.

**Comment by Johnex** [comment]
Mm ok, that is clear :)
So we need to add a ifndef just for windows then?

**Comment by Johnex** [comment]
I see that NodeJS had the same issue, they fixed it like so:

https://github.com/nodejs/node-v0.x-archive/commit/eaf76648a6ba05932465fdb2478a16ca4b6c17a6

**Comment by kinichiro** [comment]
This issue appears not be specific for Intel compiler.
This occurs with Visual Studio compiler, too.

On Windows with Visual Studio, `size_t` is defined in vcruntime.h, but there is no definiton of `ssize_t`.
When building LibreSSL portable on Windows, include/compat/sys/types.h provides `ssize_t`.
So, I believe this PR (https://github.com/libressl-portable/portable/issues/284) to LibreSSL portable will ease to use libtls on Windows.

Any comments are appreciated.

**Comment by Johnex** [comment]
I see that ssize_t exists here:
https://github.com/libressl-portable/portable/blob/master/include/compat/sys/types.h

Maybe just include that file into TLS?

**Comment by kinichiro** [comment]
That include file is only for LibreSSL build, and it is not installed when
you perform build INSTALL.
User of libtls can't include that file.
You can see that since you are a half LibreSSL builder.

**Comment by busterb** [comment]
Correct, we can't rely on the environment that the build system provides for headers.

**Comment by Johnex** [comment]
Ok i see, well then in that case kinichiro nails it with the proposed pull request :)

**Comment by kinichiro** [comment]
#284 is merged, and I will close this.
Thanks for your reporting :-)
