### ISSUE TITLE
API: Postfix 3.1.4 (OpenSSL) and Libressl 2.4.5

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#283]
Warning when compiling postfix with libressl. 
Postfix patch is attached. 

```
tls_server.c:685:42: warning: incompatible pointer types passing 'SSL_SESSION *(SSL *, session_id_t, int, int *)' (aka 'struct ssl_session_st *(struct ssl_st *, const unsigned char *, int, int *)') to parameter of type 'SSL_SESSION *(*)(struct ssl_st *, unsigned char *, int, int *)' (aka 'struct ssl_session_st *(*)(struct ssl_st *, unsigned char *, int, int *)') [-Wincompatible-pointer-types]
            SSL_CTX_sess_set_get_cb(server_ctx, get_server_session_cb);
                                                ^~~~~~~~~~~~~~~~~~~~~
/opt/libressl/include/openssl/ssl.h:931:20: note: passing argument to parameter 'get_session_cb' here
    SSL_SESSION *(*get_session_cb)(struct ssl_st *ssl, unsigned char *data,
                   ^
1 warning generated.
```

[tls.h.patch.txt](https://github.com/libressl-portable/portable/files/764438/tls.h.patch.txt)

**Comment by kinichiro** [comment]
Resolution by checking LIBRESSL_VERSION_NUMBER, and this issue is alike to https://github.com/libressl-portable/portable/issues/247.

**Comment by 4a6f656c** [comment]
Everywhere OPENSSL_VERSION_NUMBER is checked, the Postfix code may need to be modified to include a LIBRESSL_VERSION_NUMBER check. In this case Postfix is trying to use the OpenSSL 1.1 API, rather than the OpenSSL 1.0 API.
