### ISSUE TITLE
tls_accept_socket accepts -1 as a socket fd

### ISSUE THREAD

**Issue by vsajip** [libressl-portable/portable#285]
calling `tls_accept_socket(server_context, &accepted_context, -1)` returns 0 (success) and a new context in `accepted_context`. This doesn't seem right. Shouldn't some rudimentary checking be done on the input socket fd?

**Comment by 4a6f656c** [comment]
I think this falls into the category of GIGO. While we could add a check to ensure that it is a positive value, that still allows you to pass in an invalid file descriptor. And even if you pass in an open file descriptor, we have no way of knowing if we are going to be able to read/write to it. At some point we have to rely on the caller doing sensible things...
