### ISSUE TITLE
glibc 2.25 SIGKILL problem with getentropy

### ISSUE THREAD

**Issue by cujanovic** [libressl-portable/portable#290]
When I installed glibc version 2.25 on CentOS 7, LibreSSL gets always killed. Reading the glibc changelog pointed me to the new getentropy feature.

Here is a gdb output of command /usr/local/libressl-2.4.5-test-feb/bin/openssl s_client -connect www.ssllabs.com:443

#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff78e7cba in _getentropy_fail () from /usr/local/libressl-2.4.5-test-feb/lib/libcrypto.so.38
#2  0x00007ffff78e7ec9 in _rs_stir () from /usr/local/libressl-2.4.5-test-feb/lib/libcrypto.so.38
#3  0x00007ffff78e7f8d in _rs_stir_if_needed () from /usr/local/libressl-2.4.5-test-feb/lib/libcrypto.so.38
#4  0x00007ffff78e80da in _rs_random_buf () from /usr/local/libressl-2.4.5-test-feb/lib/libcrypto.so.38
#5  0x00007ffff78e82d8 in arc4random_buf () from /usr/local/libressl-2.4.5-test-feb/lib/libcrypto.so.38
#6  0x00007ffff7bb2cf4 in SSL_CTX_new () from /usr/local/libressl-2.4.5-test-feb/lib/libssl.so.39
#7  0x0000000000440bac in s_client_main ()
#8  0x00000000004306b6 in do_cmd ()
#9  0x00000000004304ba in main ()

It seems like LibreSSL gets killed by glibc code in file: sysdeps/unix/sysv/linux/getentropy.c
#else
int
getentropy (void *buffer, size_t length)
{
  __set_errno (ENOSYS);
  return -1;
}
#endif

I'm surprised that this didn't get noticed by now.

If I alter the configure file so the getentropy test fails on purpose, everything is working fine.
I have tried this with a CentOS 3.10 kernel and a Vanila 4.9 kernel + grsec and results are the same.

**Comment by busterb** [comment]
Can you point to the latest Centos package for glibc 2.25? They seem to only be on 2.17 currently: http://mirror.centos.org/centos/7/os/x86_64/Packages/

I have tried it with Ubuntu's latest testing package for glibc 2.25, and it worked as expected. It it is failing in your environment, then it is also working as designed - your implementation is returning that your kernel fails to implement the syscall.

**Comment by AliceWonderMiscreations** [comment]
CentOS 7 is on glibc 2.17

On an up to date system:

[alice@localhost phone]$ rpm -q glibc
glibc-2.17-157.el7_3.1.x86_64
glibc-2.17-157.el7_3.1.i686

That being said - http://vault.centos.org/7.3.1611/ is the current link that should be used.

Packages in current 7.3 when released are in

http://vault.centos.org/7.3.1611/os/

When there are updates, those are in

http://vault.centos.org/7.3.1611/updates/

**Comment by busterb** [comment]
I'm not sure what 'Vanilla 4.9 kernel + grsec' is configured as, it doesn't appear to be a Centos package either. So, I'm going to assume that you build both libc and kernels from scratch, or at least used non-standard packages.

It sounds like your glibc is built against the 3.10 kernel headers rather than the 4.9, and as a result, glibc has inserted a broken stub rather than letting software detect the lack of a working getentropy call.

getentropy is not defined as returning ENOSYS on any other platform, to my knowledge. It should either always succeed, or there is a bug.

```
ERRORS
     getentropy() will succeed unless:

     [EFAULT]           The buf parameter points to an invalid address.

     [EIO]              Too many bytes requested, or some other fatal error
                        occurred.
```

**Comment by cujanovic** [comment]
yes, everything is builded from scratch. I will close then this issue and investigate this further. Thanks for your time! :)

**Comment by busterb** [comment]
Try building glibc against newer kernel headers. You may need to tweak some build flags as well.
