### ISSUE TITLE
Set latest release

### ISSUE THREAD

**Issue by Vanhecke** [libressl-portable/portable#293]
Hey guys,

The "latest release" on this repo is still v2.2.3.
This makes the API / Download URL unusable: https://github.com/libressl-portable/portable/releases/latest

Cheers

**Comment by csmk** [comment]
Do not use the release from github. See https://github.com/libressl-portable/portable/issues/232#issuecomment-251860683 and https://github.com/libressl-portable/portable/issues/229#issuecomment-249920867.

**Comment by Vanhecke** [comment]
@csmk Thank you for clarifying.
Still, it would be nice to be able to tell what the latest release is programmatically.
Now I'm doing `curl -s https://www.libressl.org/ | grep "latest stable release is" | grep -Po '\d{1,2}\.\d{1,2}\.\d{1,2}'`

**Comment by busterb** [comment]
I removed the release bit from v2.2.3 to remove any confusion - not sure how that happened!
