### ISSUE TITLE
Netiquette

### ISSUE THREAD

**Issue by hdatma** [libressl-portable/portable#303]
Problem: 
You (the OP) raise an issue and someone else closes the same in less than 12 hours. 

Why this is a problem?
Since the OP raised an issue, and we all value each other's time, then the issue raised is there to be discussed. This means that the OP has an interest in the possible answers, aiming at resolving the issue. This also means that the OP is likely to interact with possible responders. This ultimately means that the underlying infrastructure and management of issues must, and I mean must, allow for this exchange to take place. I think this makes good sense, and we can all agree on this. However, if the OP raises the issue at, say, 10PM and someone else closes the same after three hours, then neither the OP nor other participants have the chance to read and participate. The OP will find an e-mail in the morning saying that the issue has been closed, with no chance to interact overnight, and no actual solution to the issue raised. This is OK if the content of the issue raised is controversial, offensive, and the likes. This is not OK if the issue is legitimate, and especially so if the issue received a single response that ignores the full content of the issue. 

This is not the first time that I see this happening. 
Latest case: https://github.com/libressl-portable/portable/issues/302

To solve this problem, I propose the following, that applies to github in general: 

hardcode a watchdog mechanism that forbids closing an issue in less than 24h from the original posting.

**Comment by 4a6f656c** [comment]
This is an issue tracker, not a discussion forum.

In #302, you assert that there are "missing bits" from a release, however it is evident that there has been little to no effort made to research the situation or identify if there is an actual issue - another person points you at a quote from a previous issue, which clearly explains/answers one of your assertions (the other assertion can also be answered with some research).

You mention that you value other's time, however many of the issues raised lack information, make incorrect assertions or fail to explain what you expect from raising the issue - it takes time from the LibreSSL team to read, respond and ultimately close out these issues.

We have no issue with legitimate issues being raised on github (even better if they provide diffs or sufficient details to fix things) - some references that might be beneficial:

  http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

  http://www.openbsd.org/report.html

That said, if you want to have a discussion, the mailing lists are a more appropriate place than github issues.

**Comment by hdatma** [comment]
The problem with you is, that you do not read the OP and the qualifications, and yet pretend to be right with your answers while inflaming the discussion. What can I do with you? I hope you will eventually grow up and understand your out-of-topic mistakes by yourself.
