### ISSUE TITLE
Consider adding const to PEM_write_bio() arguments

### ISSUE THREAD

**Issue by toralf** [libressl-portable/portable#317]
full story:  https://bugs.gentoo.org/show_bug.cgi?id=621776

--- Comment #8 from Alon Bar-Lev <alonbl@gentoo.org> ---
libressl:
int PEM_write_bio(BIO*, const char*, char*, unsigned char*, long int)

openssl:
int PEM_write_bio(BIO *bp, const char *name, const char *hdr,
                  const unsigned char *data, long len);

Please work with libressl upstream to re-add the const to argument#4.

**Comment by 4a6f656c** [comment]
This is not something that LibreSSL removed, rather this is the API that OpenSSL had in 1.0.1:

int PEM_write_bio(BIO *bp, const char *name, char *header, unsigned char *data,
             long len)

This was changed between OpenSSL 1.0.1 and 1.0.2 via commit edf92f1c41d. We can however investigate bringing these in.

**Comment by 4a6f656c** [comment]
This was done some time ago.
