### ISSUE TITLE
Consider using submodules for libressl-portable

### ISSUE THREAD

**Issue by andy-js** [libressl-portable/portable#320]
Consider using submodules for libressl-portable.  This would allow you to simplify the update.sh script and do away with OPENBSD_BRANCH.  You'd have to push updates the to refs periodically, but it protects you against sporadic build failures that can occur when the two repos are not in sync.

**Comment by busterb** [comment]
main problem is the hashes in the openbsd git mirror are not static, since they are synced from cvs. The best we can do is tag-based checkouts.

**Comment by andy-js** [comment]
That sounds odd.  Is it creating a new repo each time?

**Comment by busterb** [comment]
yes, it is.
