### ISSUE TITLE
Use GNUInstallDirs to get correct target lib directory

### ISSUE THREAD

**Issue by d3x0r** [libressl-portable/portable#321]
for CMake building 

https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html

include( GNUInstallDirs )
and then use ${CMAKE_INSTALL_LIBDIR} to get the correct name of library to install to.  (lib64 vs lib)
and ${CMAKE_INSTALL_BINDIR} for target binary directory (although that seems to always be 'bin' anyway)

**Comment by busterb** [comment]
care to submit a PR for it?
