### ISSUE TITLE
cmake failes to find version files

### ISSUE THREAD

**Issue by smasherprog** [libressl-portable/portable#345]
CMake Error at CMakeLists.txt:15 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/smash/Documents/GitHub/portable/ssl/VERSION

CMake Error at CMakeLists.txt:16 (string):
  string sub-command STRIP requires two arguments.

CMake Error at CMakeLists.txt:17 (string):
  string sub-command REPLACE requires at least four arguments.

CMake Error at CMakeLists.txt:18 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error at CMakeLists.txt:20 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/smash/Documents/GitHub/portable/crypto/VERSION

CMake Error at CMakeLists.txt:21 (string):
  string sub-command STRIP requires two arguments.

CMake Error at CMakeLists.txt:22 (string):
  string sub-command REPLACE requires at least four arguments.

CMake Error at CMakeLists.txt:23 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

CMake Error at CMakeLists.txt:25 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/smash/Documents/GitHub/portable/tls/VERSION

CMake Error at CMakeLists.txt:26 (string):
  string sub-command STRIP requires two arguments.

CMake Error at CMakeLists.txt:27 (string):
  string sub-command REPLACE requires at least four arguments.

CMake Error at CMakeLists.txt:28 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

Using [MSVC] compiler
CMake Error at crypto/CMakeLists.txt:806 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/smash/Documents/GitHub/portable/crypto/crypto.sym

CMake Error at crypto/CMakeLists.txt:808 (string):
  string sub-command REPLACE requires at least four arguments.

CMake Error at cmake_export_symbol.cmake:8 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/smash/Documents/GitHub/portable/ssl/ssl.sym
Call Stack (most recent call first):
  ssl/CMakeLists.txt:53 (export_symbol)

CMake Error at cmake_export_symbol.cmake:8 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/smash/Documents/GitHub/portable/tls/tls.sym
Call Stack (most recent call first):
  tls/CMakeLists.txt:32 (export_symbol)

Configuring incomplete, errors occurred!
See also "C:/Users/smash/Documents/GitHub/portable/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/smash/Documents/GitHub/portable/build/CMakeFiles/CMakeError.log".

The error is because there are missing version files and .sym files.

**Comment by smasherprog** [comment]
I am using cmake 3.8.2 
windows 10 
git checkout v2.6.0

**Comment by smasherprog** [comment]
Never mind, I found the issue. This repo is not for building the library. 
For those who keep running into this, download the tar ball from here,
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/
 then  build

The read.me isnt helpfull on this repo. It would be helpfull if it mentioned that you cannot simply checkout the repo and build.

**Comment by jkbullard** [comment]
> The read.me isnt helpfull on this repo. It would be helpfull if it mentioned that you cannot simply checkout the repo and build.

👍  -- that info should be much more visible.

**Comment by 4a6f656c** [comment]
@jkbullard @smasherprog pull requests or diffs to update documentation are always welcome.

**Comment by busterb** [comment]
The Readme says you have to run a script if you get the code from git:

https://github.com/libressl-portable/portable#prerequisites-when-building-from-git

Not sure how I can make it more clear, but if there's a way to make it pop out more, sure.

**Comment by busterb** [comment]
I made the prerequisite section more dire in its recommendations, hopefully it helps! 

https://github.com/libressl-portable/portable#building-libressl

**Comment by jkbullard** [comment]
@busterb - That's great. Thanks!
