### ISSUE TITLE
DTLS handshake error

### ISSUE THREAD

**Issue by DucTM31** [libressl-portable/portable#349]
Hi guys,

I try to implement a SSL server with LibreSSL on Ubuntu 14.04.
TLS works fine. But when I tried to connect using DTLS, I got this error:
![image](https://user-images.githubusercontent.com/31943921/30409892-08b20c48-9932-11e7-879e-fb66e31e135b.png)

Trying to debug, I found out that the reason of this problem might be the way the library read packet from socket. As in the function "dtls1_get_record(SSL *s)" (file d1_pkt.c)
- Firstly, the lib read the record header from IO: (13 bytes) - then extract the header information (type, length...)
![image](https://user-images.githubusercontent.com/31943921/30410248-10e9cc50-9934-11e7-92c4-72371241acd6.png)

- Secondly, it uses the length info to read the rest of the packet (as I understand from the library code - correct me if I'm wrong)
![image](https://user-images.githubusercontent.com/31943921/30410470-6edadab0-9935-11e7-925d-ae63f01d3c1b.png)
But since DTLS uses UDP, then the second read actually get the next packet which contains another record header. 
After that, the lib try to parse the handshake header from result of the second read which is actually the record header. And it leads to the error I mentioned above.

Is there any solution for this? or Did I misunderstand somethings?
Thank you!

**Comment by kinichiro** [comment]
Hi,
Are you implementing server with libtls ? Since your first error message was `tls_read: handshake failed`.
And are you trying to connect your server with `openssl s_client` command or something like that supports DTLS connection ?
I don't think libtls support DTLS.

**Comment by DucTM31** [comment]
Thank you for your reply.
Yep, I'm trying to use libtls to implement my ssl server and I use the openssl s_client to test.

After I read the s_server example code, it turns out that I have to set the read ahead option so the unread bytes of the UDP datagram will not be discarded.
And then, with some other modifications, at least the normal/simple DTLS connection works.

So in the beginning, the lib does not support DTLS. Then, modifying it to work with DTLS might not be a good idea. 
And instead of using tls_read/ tls_write, should I use the dtls1_listen/ ssl_read/ ssl_write to handle the handshake/ data exchange?

**Comment by kinichiro** [comment]
IMHO, if you need to use DTLS, you should use libssl functions.

**Comment by DucTM31** [comment]
Problem solved. Thank you!
