### ISSUE TITLE
CMake only produces static libs on macOS

### ISSUE THREAD

**Issue by DevSidious** [libressl-portable/portable#351]
Most likely related to: #129 . 

Any plans to actually fixing this instead of disabling shared library building via CMake on macOS ?

Optionally, regardless of the existence or absence of the aforementioned plans, an update to the docs mentioning this issue  would be really great.

**Comment by kinichiro** [comment]
On travis-ci OSX environment, I could build shared with this modification of CMakeLists.txt.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9814356..e2b5d68 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -269,7 +269,7 @@ if(ENABLE_ASM)
        endif()
 endif()

-if(NOT (CMAKE_SYSTEM_NAME MATCHES "(Darwin|CYGWIN)"))
+if(NOT (CMAKE_SYSTEM_NAME MATCHES "(CYGWIN)"))
        set(BUILD_SHARED true)
 endif()
```

I just had got this warning message.

```
CMake Warning (dev):

  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:
   crypto-shared
   ssl-shared
   tls-shared

This warning is for project developers.  Use -Wno-dev to suppress it.
```

I don't have my own OSX environment, and I just could verify on travis-ci environment though, is this still an issue ?
And should we fix warning for MACOSX_RPATH ?

**Comment by busterb** [comment]
I think #406 might also address this.

**Comment by kinichiro** [comment]
@busterb 
Well then, how about merging #406 ?
After that, I would try to find the method for building tests against shared library in the future.

**Comment by busterb** [comment]
I believe we resolved this, closing.
