### ISSUE TITLE
Is this an issue?

### ISSUE THREAD

**Issue by d3x0r** [libressl-portable/portable#352]
(Sorry for the bad title, just found this while getting it to compile on windows using mingw64; a few msvc flags should actually be win32 instead...)

https://github.com/libressl-portable/portable/blob/master/apps/ocspcheck/CMakeLists.txt#L23

That line is the same test as above that is 
	check_function_exists(inet_ntop HAVE_INET_NTOP)

(the line mentioned)
	check_function_exists(inet_ntop HAVE_MEMMEM)

Shouldn't that either be a different function or simply merged into the single check of the first inet_ntop?

**Comment by kinichiro** [comment]
Yes, second check should be memmem.
Could you post pull-request for this ?

**Comment by kinichiro** [comment]
This issue was fixed by #355.
