### ISSUE TITLE
how to run "tests" on WINDOWS

### ISSUE THREAD

**Issue by bagajjal** [libressl-portable/portable#356]
I followed the below steps,
1) Downloaded the source code from "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.2.tar.gz".
2) Created the visual studio solution by running the 
"C:\Program Files\CMake\bin\cmake.exe" -G"Visual Studio 14 2015" .. -DENABLE_VSTEST=ON
3) The RUN_TESTS_force.rule has just one comment line (but no tests),
(# generated from CMake)

4) The visual studio solution includes all the test projects (total 73 projects) and the build was successful.
5) We are interested in crypto. Output of the crypto project looks like this,
![image](https://user-images.githubusercontent.com/23668037/31155930-91696354-a866-11e7-8821-a0c2ca5c604c.png)

But the[  official windows release ](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.5.5-windows.zip)has different binary names and it looks like this,
![image](https://user-images.githubusercontent.com/23668037/31155990-fa8e308a-a866-11e7-9117-f71afd065652.png)

I have few questions,
a) why the binary names (.lib, .exp, .dll) are different between my build output and official release?
b) crypto.lib, crypto-42.ilk is not present in the "official windows release". Are they really required?
c) can I assume that the generated crypto-42.lib, crypto-42.dll, crypto-42.exp are same as official release binaries i.e., libcrypto-42.lib, libcrypto-42.exp, libcrypto-42.dll?
If yes, what is the importance of crypto.lib, crypto-42.ilk and how they are used?
d) Is there a way to generate a single static lib file so that we can avoid the run time dependency of having libcrypto-41.dll?
e) how to run the tests after the successful build?

fyi, We have a restriction to build the crypto binaries on our secured machines.

**Comment by yupi2** [comment]
I believe the official binaries are built with MinGW which adds a `lib` prefix.
`<name>.lib` is a static library you can use to link to your program.
`<name>-<number>.lib` is for linking to `<name>-<number>.dll`
`*.ilk` does something for incremental linking and `*.exp` does something for... something. They aren't needed after building.

Tests can be ran with something like `cmake --build ./ --target RUN_TESTS`

**Comment by bagajjal** [comment]
Thanks for your quick reply..

If I understand correctly, we can either use 
name.lib as static library that avoids further need for dll

Or

Use the Name-number.lib for static link to Name-number.dll

If yes, what is the advantage of 2nd option (static lib and dll)?

**Comment by yupi2** [comment]
There's not a big advantage either way in this case except for not having to distribute a dll if you static link.
Using DLLs can possibly allow you to use an old version of the program and be able to update the DLLs if a patch is released without having to recompile the program. That will only be possible if the API is the same between versions though.

**Comment by bagajjal** [comment]
I have few follow up questions,

1) I was able to run the tests using "cmake.exe  --build ./ --target RUN_TESTS".
We have a secured environment where we can't use the third party software so is there a way to run the tests from the command line or from the visual studio?

2) I tried to use the static library (<name>.lib) but unfortunately I am getting many errors and warning messages (3653 warning messages).

unresolved external symbol __imp___stdio_common_vsscanf referenced in function sscanf
unresolved external symbol __imp__getpid
unresolved external symbol __imp_close
unresolved external symbol __imp_feof
unresolved external symbol __imp_fwrite
unresolved external symbol __imp_getpid
unresolved external symbol __imp_open
unresolved external symbol __imp_read
unresolved external symbol __imp_strdup
unresolved external symbol __imp_write

Please note that the combination of static library, dll (<name>-<number>.lib, <name>-<number>.dll) works fine.

Appreciate your help.

**Comment by kinichiro** [comment]
To run the tests from Visual Studio, build RUN_TESTS.

**Comment by bagajjal** [comment]
RUN_TESTS has only one file, RUN_TESTS_force.rule which has just one comment line (but no tests),
(# generated from CMake)

I build the RUN_TESTS but tests doesn't run.

Also could you please help me with the static library (crypto.lib)..

**Comment by kinichiro** [comment]
>RUN_TESTS has only one file, RUN_TESTS_force.rule which has just one comment line (but no tests),
>(# generated from CMake)

It is same as my environment, and I don't think it is the matter.

For running test, my process is like this;
1. Download tar.gz and spread it
2. Create 'build' dir in libressl-2.x.x and cd to 'build' dir
3. Run CMake
   cmake -G "Visual Studio 15 2017 Win64" -DENABLE_VSTEST=on ..
4. Double click the LibreSSL.sln file to run the Visual Studio.
5. Build the solution
6. Right click 'RUN_TESTS' on Solution Explorer and build it.

I could run all the tests like below screen shot.
![test](https://user-images.githubusercontent.com/4927823/31313713-ea993450-ac25-11e7-9e61-219cf017fc16.png)

For the problem of your linking static library build, I have no idea since I could build openssl.exe.
I think you also could build openssl.exe with static library linking.
I think you can check the CMakeLists.txt under the 'apps/openssl/' to get the hint.

**Comment by bagajjal** [comment]
@yupi2 - Could you please help me with resolving the build errors while trying to use the static library alone (crypto.lib). FYI, I have the mentioned the type of errors in my previous posts.

@kinichiro - Thanks, I was able to run the tests.

FYI, I am trying to build to the win32-openssh portable with libressl on our secured machines.

**Comment by yupi2** [comment]
I don't get those errors and I don't know why you do.

**Comment by kinichiro** [comment]
@bagajjal It seems that you could run the tests.
Can you close this issue ?

**Comment by bagajjal** [comment]
Yes please.
