### ISSUE TITLE
why is the version number part of the binary name? (libcrypto-version.lib/.dll,etc)

### ISSUE THREAD

**Issue by bagajjal** [libressl-portable/portable#357]
We are using libressl in Win32-openssh project (we are porting openssh to windows so majority of the code is same). 

The windows barinaries from [here](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/) have libcrypto-version.lib, libcrypto-version.dll. I have few questions related to version number,

1) why the version number is included as part of the binary name (libcrypto-version.lib / .dll, etc)?
Isn't the version number should be part of meta data?

2) I see multiple releases using the same version number so just curious to know when the version number gets changed?

3) can we use different versions of .lib and .dll?
Can I compile our project using .lib **only once** and keep updating the .dll? 

fyi, since the version number is part of the .dll, I need to rename the .dll version to match with the .lib version used earlier during compilation. This doesn't look good (renaming .dll) so what is the reason for having the version as part of the binary name?

Will there be a situation where we need to **re-compile** our project with the latest .lib to use the latest .dll?

I compared the .lib file between different versions and it clearly has differences. so can we use different versions of .lib and .dll?

FYI, For compiling our project, we are using the crypto-version.lib and the include folder (that has all the header files). To execute our binaries we need to have crypto-version.dll (same version number) in the PATH environment variable.

**Comment by kinichiro** [comment]
That version number shows ABI version, and it is incremented when API is added or removed or changed.
In case API is not modified between multiple releases, version number is not changed.
I do not want to recommend mixing the dll version between releases.
