### ISSUE TITLE
Support for TLS_FALLBACK_SCSV

### ISSUE THREAD

**Issue by johansglock** [libressl-portable/portable#36]
I took the effort to make a start on adapting the OpenSSL patch for TLS_FALLBACK_SCSV to LibreSSL. The original patch was taken from:
http://marc.info/?l=openssl-dev&m=141333049205629&q=p6

The adapted patch is currently available at:
https://github.com/johansglock/poudriere.d/blob/master/local-patches/libressl-fallback-scsv.patch

This patch is based on the tarball of the 2.1.0 release. I have this patch running on my private server and seems to functioning in some basic testing. If other people would be willing to test some more that would be great.

Any feedback on potential issues or style to get this included would be great.

Update:
Just fixed a stupid bug which I overlooked. Including my test results now. OpenSSL 1.0.1j connecting to LibreSSL host:
[SUCCESS] openssl s_client -tls1 -connect myhost.nl:443
[SUCCESS] openssl s_client -tls1_1 -connect myhost.nl:443
[SUCCESS] openssl s_client -tls1_2 -connect myhost.nl:443
[SUCCESS] openssl s_client -fallback_scsv -connect myhost.nl:443
[SUCCESS] openssl s_client -fallback_scsv -tls1_2 -connect myhost.nl:443
[FAIL] openssl s_client -fallback_scsv -tls1_1 -connect myhost.nl:443
[FAIL] openssl s_client -fallback_scsv -tls1 -connect myhost.nl:443

LibreSSL connecting to Google:
[SUCCESS] openssl s_client -fallback_scsv -tls1_2 -connect google.com:443
[FAIL] openssl s_client -fallback_scsv -tls1 -connect google.com:443
[SUCCESS] openssl s_client -fallback_scsv -connect google.com:443

These results are all as expected.

**Comment by 4a6f656c** [comment]
Server-side TLS_FALLBACK_SCSV support has reluctantly been added to LibreSSL.
