### ISSUE TITLE
CMakeLists.txt shouldn't use CMAKE_SYSTEM_PROCESSOR for asm

### ISSUE THREAD

**Issue by blueness** [libressl-portable/portable#361]
The new cmake build system makes use of CMAKE_SYSTEM_PROCESSOR which looks at the processor's architecture to decide whether to build x86_64 or i386 assembly code.  This is a very bad practice because you may want to build 32-bit asm on a 64-bit system, either in a chroot, or as part of cross compiling, or for multilib systems where one invokes gcc -m32.  This leads to a downstream issue in Gentoo as reported in

https://bugs.gentoo.org/636836

The problem line is at

https://github.com/libressl-portable/portable/blob/master/CMakeLists.txt#L262

**Comment by blueness** [comment]
A related question: I've reverted downstream to gnu autotools build.  Is libressl-portable going to continue to support both build systems?

**Comment by kinichiro** [comment]
IMHO, autotool should be primary build system for LibreSSL,
and CMake is for native Windows build without cygwin nor mingw.
Now, CMake build works on all platforms though ...

**Comment by busterb** [comment]
What's the CMake solution then?

**Comment by kinichiro** [comment]
I think we can use CMAKE_TOOLCHAIN_FILE, 
as `cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain_xxx.cmake` .

And the toolchain file will be like this,
```
SET(CMAKE_SYSTEM_PROCESSOR xxx)
SET(CMAKE_SYSTEM_NAME yyy)
SET(CMAKE_C_COMPILER /usr/bin/cross-compiler-path)
```

Toolchain file should be written by library user since there are many platforms and targets.

**Comment by kinichiro** [comment]
@blueness Can you close this issue ? Original ticket appears to be closed already.

**Comment by busterb** [comment]
I think I'd like to avoid the extra complexity that comes with coaxing cmake into cross-compiling properly. It's unfortunate that it cannot be done easily as it is with autotools.
