### ISSUE TITLE
Invalid command 'SSLOpenSSLConfCmd' in Apache 2.4 with LRE 2.6.3 for Windows

### ISSUE THREAD

**Issue by long76** [libressl-portable/portable#367]
Lines(in httpd-ssl.conf file):
SSLOpenSSLConfCmd ECDHParameters prime256v1
SSLOpenSSLConfCmd Curves brainpoolP512r1:secp521r1:brainpoolP384r1:secp384r1:brainpoolP256r1:prime256v1
does't work,
how i can set for all vhosts ECDHParameters and Curves?
thanks.
Apache was downloaded from Apachehaus.

**Comment by kinichiro** [comment]
SSLOpenSSLConfCmd is available in httpd 2.4.8 and later, if using OpenSSL 1.0.2 or later.
https://httpd.apache.org/docs/trunk/mod/mod_ssl.html#sslopensslconfcmd

LibreSSL forked from OpenSSL 1.0.1, and doesn't have SSL_CONF_cmd(3).
 I don't think that directive does not work with LibreSSL.

**Comment by long76** [comment]
but how i can setup ECDHParameters and Curves?

**Comment by 4a6f656c** [comment]
The normal way of doing this is for the software to call [SSL_{,CTX}_set1_{curves,groups}_list()](http://man.openbsd.org/man3/SSL_CTX_set1_groups.3) - other web servers such as nginx and OpenBSD's httpd provide configuration options that use this functionality and I would have expected mod_ssl to do the same...

**Comment by kinichiro** [comment]
@long76 Can you close this issue ? I think this issue should be resolved by Apache rather than SSL/TLS library.
