### ISSUE TITLE
https://www.libressl.org/ shows 2.6.3 not 2.6.4 as latest stable

### ISSUE THREAD

**Issue by ilovezfs** [libressl-portable/portable#370]
https://www.libressl.org/ says, "The latest stable release is 2.6.3" despite also saying, "LibreSSL 2.6.4 released December 19th, 2017"

Does that imply 2.6.4 is not latest stable?

**Comment by busterb** [comment]
> On Dec 20, 2017, at 2:26 PM, ilovezfs <notifications@github.com> wrote:
> 
> https://www.libressl.org/ <https://www.libressl.org/> says, "The latest stable release is 2.6.3" despite also saying, "LibreSSL 2.6.4 released December 19th, 2017"
> 
> Does that imply 2.6.4 is not latest stable?
> 
> 

No, it implies that I forgot to update that line.

**Comment by ilovezfs** [comment]
@busterb sorry for the impatience :blush:

**Comment by ilovezfs** [comment]
Looks fixed! Thanks

**Comment by busterb** [comment]
No worries :heart:
