### ISSUE TITLE
Extra space in openssl CLI output for notAfter/enddate

### ISSUE THREAD

**Issue by nikolaiderzhak** [libressl-portable/portable#382]
I am getting extra space in enddate output of this command:

```
$ export IP=google.com;  nc -z -w 3 $IP 443 && (echo | openssl s_client -connect $IP:443 2>/dev/null | openssl x509 -noout -enddate)
Connection to google.com port 443 [tcp/https] succeeded!
notAfter=Apr  4 09:40:00 2018 GMT
```

Note two spaces between Apr and 4 in notAfter= line.

That is the case for both versions I have on laptop and on linux server:

```
$ openssl version
LibreSSL 2.2.7
$ openssl version
OpenSSL 1.0.1f 6 Jan 2014
```

https://stackoverflow.com/questions/48328163/extra-space-in-openssl-cli-output-for-notafter-enddate

OpenSSL has the same issue: https://github.com/openssl/openssl/issues/5107

**Comment by kinichiro** [comment]
This question was answered in https://github.com/openssl/openssl/issues/5107
.
Can you close this issue ?

**Comment by 4a6f656c** [comment]
This is pretty much how dates work on Unix and C - the day is formatted as two digits with leading padding, hence a single digit day will be formatted as ' 4'. This is the same date(1) and ctime(3):

```shell
$ date -r 1516500000 
Sun Jan 21 13:00:00 AEDT 2018
$ date -r 1515000000 
Thu Jan  4 04:20:00 AEDT 2018
```

(Or `date -d @1515000000` on a Linux system).

Is there a reason why you consider this to be a problem?

**Comment by nikolaiderzhak** [comment]
We using enddate string to confirm SSL certificate is taking care of and visually stings with one and two spaces looks the same while we get them different in process. Thank you for explanations !
