### ISSUE TITLE
Removing source paths from library

### ISSUE THREAD

**Issue by Johnex** [libressl-portable/portable#387]
Hi!
So i noticed an issue. When i compile my programs using libressl and open them with BinText to view all the strings, i can see the full paths to all the libressl source files!

Compiling with Visual Studio 15.5.5 using:

cmake -G"Visual Studio 15 2017" ..

Compiling and opening ssl.lib in the release folder with notepad++ shows all the source strings :(

![screenshot 2018-02-13 15 45 00](https://user-images.githubusercontent.com/7826974/36155525-df8b1574-10d4-11e8-85a2-bfaa67462dab.png)

That is the result after building the final exe as Release with /pdbaltpath:%_PDB%  set to remove the full path from the pdb link. Seems like something in this specific library is writing the paths to the string table, as i don't have this issue with other libraries such as turbro-jpeg and webp.

There is also a "standard" certificate link too, how can we remove that also?

![screenshot 2018-02-13 15 47 22](https://user-images.githubusercontent.com/7826974/36155669-40cd50fe-10d5-11e8-974e-b196a4821348.png)

**Comment by Johnex** [comment]
So i found another library that had the same issue:
https://stackoverflow.com/questions/30139852/why-does-the-executable-binary-file-contain-paths-of-included-header-files

Is there some kind of debug setting in LibreSSL i don't know about too? Like they had:
#define wxDEBUG_LEVEL 0

**Comment by lanodan** [comment]
CMake defaults to "RelWithDebInfo", meaning Release with Debug Info. Not sure why you would want to remove debug symbols as it’s often a bad idea but you can with ``-DCMAKE_BUILD_TYPE=Release`` or ``-DCMAKE_BUILD_TYPE=MinSizeRel`` in your cmake arguments.
btw if you want to easily see the available options you can use ``ccmake`` instead for the ncurses interface (there is also a Qt5 one but I haven’t used it).

**Comment by Johnex** [comment]
This is not correct because i compile the libraries using:

```bash
msbuild /m /p:Configuration=Release ALL_BUILD.vcxproj
```

Which changes to release without debugging. Some strings are still being set statically inside the library for whatever reason, which is not good. Compiling as Release should remove all the strings with paths, but it didn't.

**Comment by lanodan** [comment]
Removing /etc/ssl/cert.pem will just leave you with a half-broken LibreSSL.
It is used for certificate verification with x.509 and it needs to exist for almost everything <del>SSL/</del>TLS.

**Comment by Johnex** [comment]
From what i can see the cert,.pem only exists in linux. On Windows it was not present in any of the source paths. Downloading and using a certificate store like the one from firefox or another source is better either way, as it will be more up to date.

Having the hard coded path is not needed, and is the main issue here. Users can set the path manually so why hard code it.
