### ISSUE TITLE
Year 2038 problems with libressl-portable's use of time_t in X509_cmp_time_internal on 32-bit Linux

### ISSUE THREAD

**Issue by mkrautz** [libressl-portable/portable#389]
Hi,

We've had multiple people report X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD errors from LibreSSL in Murmur, the server component of Mumble. (https://github.com/mumble-voip, https://www.mumble.info).

Mumble, and its server component Murmur generate self-signed certs with long lifetimes. It just so happens that certs generated in 2018 have a notAfter date in 2038.

We narrowed down these errors to 32-bit Linux machines, as in `sizeof(time_t) == 4`.

LibreSSL has a sanity check where an ASN1 time MUST be convertible back to a time_t to be considered valid. I assume that is what's causing the failures for Murmur users. Code is at:
https://github.com/libressl-portable/openbsd/blob/libressl-v2.6.4/src/lib/libcrypto/x509/x509_vfy.c#L1891-L1897

It seems to me that this path needs to be changed for -portable, since it assumes that all platforms have OpenBSD's 64-bit time_t.

**Comment by bob-beck** [comment]
What version of LibreSSL are you seeing these errors with?  Earlier
versions would fail there? the latest should not.

**Comment by mkrautz** [comment]
The user was running LibreSSL 2.5.5 on Void Linux, arm 32-bit. I reproduced the issue on a 32-bit x86 Void Linux (same LibreSSL version). That seems to be what they ship in their stable tree.

**Comment by mkrautz** [comment]
Aha, I see the “clamp notAfter” in the code block above. I suppose that was the “fix”?

My aplogies for not bring clearer about the versions in my report — and linking to a 2.6.4 tree that supposedly already has a workaround.

Thanks!

**Comment by mkrautz** [comment]
Here's the commit for any onlookers:
https://github.com/libressl-portable/openbsd/commit/362ffef32c0fcae703d57838e9f5704240a63213

Closing.

**Comment by bob-beck** [comment]
Thanks Mikkel!
