### ISSUE TITLE
build fails on arm when gcc is targeted for older CPUs

### ISSUE THREAD

**Issue by rofl0r** [libressl-portable/portable#41]
```
/tmp/ccLdfLLF.s:356: Error: selected processor does not support ARM mode `rev r9,r9'
/tmp/ccLdfLLF.s:392: Error: selected processor does not support ARM mode `rev r3,ip'
/tmp/ccLdfLLF.s:452: Error: selected processor does not support ARM mode `rev r3,r9'
make[1]: *** [modes/libcrypto_la-ctr128.lo] Error 1
```
it's caused by this command:
```
gcc -std=gnu99 "-DPACKAGE_NAME=\"libressl\"" "-DPACKAGE_TARNAME=\"libressl\"" "-DPACKAGE_VERSION=\"2.1.1\"" "-DPACKAGE_STRING=\"libressl 2.1.1\"" "-DPACKAGE_BUGREPORT=\"\"" "-DPACKAGE_URL=\"\"" "-DPACKAGE=\"libressl\"" "-DVERSION=\"2.1.1\"" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 "-DLT_OBJDIR=\".libs/\"" -DNO_REALLOCARRAY=1 -DNO_TIMINGSAFE_BCMP=1 -DNO_TIMINGSAFE_MEMCMP=1 -DNO_ARC4RANDOM_BUF=1 -DNO_GETENTROPY=1 -DNO_STRTONUM=1 -DNO_EXPLICIT_BZERO=1 -DHAVE_VA_COPY=1 -DHAVE_GETAUXVAL=1 -DHAVE_ERR_H=1 -I. -I../include -DHAVE_CRYPTODEV -DLIBRESSL_INTERNAL -I../crypto/asn1 -I../crypto/evp -I../crypto/modes -D_GNU_SOURCE -std=gnu99 -g -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -Wno-pointer-sign  -DOPENSSL_NO_HW_PADLOCK -fdata-sections -ffunction-sections -Os -g0 -fno-unwind-tables -fno-asynchronous-unwind-tables -Wa,--noexecstack -ftree-dce -Wall -std=gnu99 -g -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_SOURCE -D_GNU_SOURCE -Wno-pointer-sign -MT modes/libcrypto_la-ctr128.lo -MD -MP -MF modes/.deps/libcrypto_la-ctr128.Tpo -c modes/ctr128.c  -fPIC -DPIC -o modes/.libs/libcrypto_la-ctr128.o
```

the code in question is 
```
@ 210 "modes/ctr128.c" 1
        ctr32 = GETU32(ivec+12);
```
which expands to
```
 ctr32 = ({ u32 ret; asm ("rev %0,%1" : "=r"(ret) : "r"((u32)(*(const u32 *)(ivec+12)))); ret; });
   ctr32 = 0;
```
via crypto/modes/modes_lcl.h BSWAP8 and BSWAP4 macros
```c
# elif (defined(__arm__) || defined(__arm)) && !defined(__STRICT_ALIGNMENT)
#  define BSWAP8(x) ({  u32 lo=(u64)(x)>>32,hi=(x);     \
                        asm ("rev %0,%0; rev %1,%1"     \
                        : "+r"(hi),"+r"(lo));           \
                        (u64)hi<<32|lo;                 })
#  define BSWAP4(x) ({  u32 ret;                        \
                        asm ("rev %0,%1"                \
                        : "=r"(ret) : "r"((u32)(x)));   \
                        ret;                            })
```
i was told that the rev instructions is only supported by some new arm cpus, thus the error trying to use it on not-latest-arm-cpu

**Comment by frozeus** [comment]
I get the same issu when i tried to compile LibRessl 2.1.3.
Using -march=armv5te, My libC is newlib nano. 

@jbarlow83 My toolchain is similar to this one : https://launchpad.net/gcc-arm-embedded/

**Comment by jbarlow83** [comment]
@frozeus A summary of the long thread above is basically that the code relies on an ARMv6 instruction and cannot detect or supply an alternative when only ARMv5 is available (yet). The other part of the discussion is that the compiler doesn't seem kind enough to define a platform for us.

A short term fix that should get compilation working on <ARMv6 would be to insert the line
```C
#undef BSWAP4
```

at line 57 of modes_lcl.h (i.e. disable the inline assembly macro).

Or use --disable-asm if you don't want to mess with code.

**Comment by frozeus** [comment]
@jbarlow83  thanks for the summary i compile it also for other arch.
I will try something like:
```
#if defined(__ARM_ARCH__) && (__ARM_ARCH__ < 6)
#undef BSWAP4
#endif 
```
--disable-asm also removed other optimzations that work for ARMv5 no ? So mess with code is the best option i suppose.

**Comment by busterb** [comment]
I finally got around to coding a compile-time check for this 933820a0f525c5b36ef4f41459cff2084671c853, sorry for the delay

**Comment by sstruchtrup** [comment]
I am seeing the compile-time check in configure pass successfully, but compiling fails anyway.

The problem seems to be triggered by setting an optimization level in CFLAGS when configure runs. This will optimize away the BSWAP4, giving the assembler no chance to complain about the unsupported instructions.

Hence, the configure test passes, compilation still fails.
Using `asm volatile` instead of `asm` in the definition of BSWAP4 seems to solve the issue - although this might not be desired for building the actual code.

A quick and somewhat hackish fix would be to `#define asm asm volatile` in the AC_TRY_COMPILE block in configure.ac before `#include "$srcdir/crypto/modes/modes_lcl.h`

**Comment by sstruchtrup** [comment]
The configure test will also incorrectly pass when building with `-fLTO`. The unsupported assembler instruction will then only be detected during the link stage, which is not executed by the configure test.

**Comment by busterb** [comment]
Thanks. Reopening so this update doesn't get lost.

**Comment by busterb** [comment]
I disabled the BSWAP macros as @frozeus did for ARM_ARCH <= 5 : a9332cc

**Comment by 8ohmh** [comment]
Hi,

have the same problem but on compiling toolchain on a ARM Marvell machine and error occured in GMP - I can NOT compile ANY toolchain - Please tell what's solution

**Comment by JL2210** [comment]
Why not just use `__builtin_bswap32`?
