### ISSUE TITLE
Build on i386 libcrypto fails

### ISSUE THREAD

**Issue by AmarOk1412** [libressl-portable/portable#415]
I'm currently trying to build libressl-portable on a i386 vm (cause it's the only build failing).

I build with `mkdir build && cd build && $(CMAKE) -DDESTDIR=$(PREFIX) .. && $(MAKE) && $(MAKE) install` or with `-DCMAKE_C_FLAGS='-m32'`

It tried to build libcrypto (in both case) in `x86_64`... so:
```
libressl/crypto/aes/aes-elf-x86_64.S: Assembler messages:
libressl/crypto/aes/aes-elf-x86_64.S:7: Error: bad register name `%r15)'
libressl/crypto/aes/aes-elf-x86_64.S:8: Error: bad register name `%r15)'
libressl/crypto/aes/aes-elf-x86_64.S:9: Error: bad register name `%r15)'
...
```

**Comment by busterb** [comment]
i386 VM running what OS?

**Comment by busterb** [comment]
Oh, are you actually running a 32-bit host OS, or is itt 64-bit and you're trying to use a multi-arch compiler instead. If the later, it's is a pain to support, since the build tuple will lie.

**Comment by AmarOk1412** [comment]
The build fails for a `ubuntu_17.10` and a `ubuntu_16.04` 32 bits (docker) on a 64 bits system.

And yeap I understand why it's a pain. The better workaround is to use the xxxxxssl version from the packages of the 32 bits OS.

**Comment by busterb** [comment]
Not sure what you mean by that, but this works:

`linux32 cmake -DCMAKE_C_FLAGS='-m32'`

Prefixing with the `linux32` command allows cmake to detect the host system as 32-bit so the targets are configured correctly.

**Comment by busterb** [comment]
```
$ linux32 uname -a
Linux toaster 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) i686 GNU/Linux
$ uname -a
Linux toaster 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux
```

**Comment by busterb** [comment]
I'm going to close this. It looks like more of an issue setting up cross-compilation. Thanks.

**Comment by AmarOk1412** [comment]
yeap `linux32` will work too.

Ok! Have a nice day.
