### ISSUE TITLE
TLS session serialization

### ISSUE THREAD

**Issue by fwsGonzo** [libressl-portable/portable#422]
Is it possible to serialize a TLS session in any way? Assume that every byte of physical memory will be replacedin a few microseconds and then restored by deserializing the most useful bits, effectively live updating the whole machine. TCP is already preserved. How can I preserve an ongoing TLS session?

Example API call:
```
int SSL_do_serialize_tls_session(this->m_ssl, pointer_to_storage);
SSL* SSL_do_deserialize_tls_session(SSL_CTX*, void* pointer_to_storage, int length);
```

**Comment by kinichiro** [comment]
Does openssl s_client -sess_out and -sess_in options solve your issue ?

**Comment by fwsGonzo** [comment]
From reading https://github.com/openssl/openssl/blob/master/apps/s_client.c it seems to me all it does is serialize SSL_SESSIONs, which are only used to save some time when *reopening* new TLS sessions to clients the server has already seen before.

http://www.umich.edu/~x509/ssleay/session.html it's an old document, but it explicitly says that SSL_SESSION cannot be used to restore an already opened TLS session. Is this still the case?

**Comment by fwsGonzo** [comment]
Thanks for the confirmation, I will close this.

**Comment by rrusinov** [comment]
> @fwsGonzo as per your last update, there is no existing functional way to serialize and deserialize the state of an active SSL session - you'd need to save and restore the SSL_CTXs, SSLs and SSL_SESSIONS underlying BIOs (and probably others). The opaque aspects of current OpenSSL and parts of LibreSSL will make this near impossible from outside of the library. Overall, while it is a neat idea I'd question the usefulness and fragility of it.

It is useful in multiprocess applications, ie. one process is accepting connections (+tls) and distributing work to other processes using file descriptor transfer over unix domain sockets.
