### ISSUE TITLE
No windows.zip at https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

### ISSUE THREAD

**Issue by DarwinJS** [libressl-portable/portable#423]
Looks like 2.5.5 was the last version published in this way for Windows?

Is the zip file on the github releases page for Windows?  (https://github.com/libressl-portable/portable/releases)

**Comment by csmk** [comment]
> Is the zip file on the github releases page for Windows?

No, see https://github.com/libressl-portable/portable/issues/232#issuecomment-251860683

**Comment by DarwinJS** [comment]
I'm not sure how that thread helps - does this project still compile binaries for windows?

**Comment by kinichiro** [comment]
Last part of this announcement had told the reason why.
https://marc.info/?l=libressl&m=149994708421035&w=2

**Comment by RussellHaley** [comment]
Crappy looking 32 bit msi installer here: https://github.com/WinLua/bin/. I'll work on cleaning it up and getting a 64 bit version working for the next tagged release. I've adorned it with OpenBSD icons and so forth. Not sure if that's cool or not?

**Comment by busterb** [comment]
Going to close this. If someone wants to make a stab at updating the appveyor config file to automatically artifact binaries from build tags, that would be a reasonable solution. There are just too many Windows ABI variants for pre-built libraries built by me personally to be of much use.
