### ISSUE TITLE
Windows 10 VS 2017 - Multiple Architectures

### ISSUE THREAD

**Issue by RussellHaley** [libressl-portable/portable#425]
Hi, 

I've tried adding x64 architecture to the VS 2017 solution generated by cmake. I used the standard configuration manager in VS and it all went pretty smootly but I get endless linker errors because my architectures aren't lining up. I've surmised that perhaps I need to generate a 64 bit solution via cmake but I'm unsure where to go from here (or if I'm even correct)?

Any advice would be grand. 
Thanks!

**Comment by kinichiro** [comment]
If you need to generate 64 bit solution for VS 2017 via cmake, you can try this.

```
cmake -G "Visual Studio 15 2017 Win64" ..
```

Does this solve your issue ?

**Comment by RussellHaley** [comment]
Yes, thank you it does. I confirmed the output is 64 bit using this hack here:
https://superuser.com/questions/358434/how-to-check-if-a-binary-is-32-or-64-bit-on-windows#889267

Thank you for your support!
