### ISSUE TITLE
Release file of libressl-2.7.4.tar.gz is broken

### ISSUE THREAD

**Issue by catatsuy** [libressl-portable/portable#436]
cf: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

```
libressl-2.7.3-relnotes.txt                        02-May-2018 21:53                1014
libressl-2.7.3.tar.gz                              02-May-2018 21:50             3364724
libressl-2.7.3.tar.gz.asc                          05-May-2018 02:52                 801
libressl-2.7.4-relnotes.txt                        13-Jun-2018 11:39                 827
libressl-2.7.4.tar.gz                              13-Jun-2018 10:58             3359012
libressl-2.7.4.tar.gz.asc                          13-Jun-2018 11:32                 801
```

The file size of `libressl-2.7.4.tar.gz` is smaller than one of `libressl-2.7.3.tar.gz`.  The file of `libressl-2.7.4.tar.gz` can not be extracted with `tar`.

```
libressl-2.7.4/man/BIO_new.3
libressl-2.7.4/man/BIO_printf.3
libressl-2.7.4/man/BIO_push.3
libressl-2.7.4/man/BIO_read.3
gzip: (stdin): unexpected end of file
libressl-2.7.4/man/BIO_s_accept.3
libressl-2.7.4/man/BIO_s_bio.3
libressl-2.7.4/man/BIO_s_connect.3
libressl-2.7.4/man/BIO_s_fd.3
libressl-2.7.4/man/BIO_s_file.3
libressl-2.7.4/man/BIO_s_mem.3
libressl-2.7.4/man/BIO_s_null.3
libressl-2.7.4/man/BIO_s_socket.3
libressl-2.7.4/man/BIO_set_callback.3
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

Please recreate the release file.

**Comment by botovq** [comment]
On what system with what tools?

Works fine on OpenBSD, both with GNU tar and BSD tar. Did you verify the
signature of the file before extracting it? What is the checksum of the
archive you can't extract? I get:

SHA256 (libressl-2.7.4.tar.gz) = 1e3a9fada06c1c060011470ad0ff960de28f9a0515277d7336f7e09362517da6

The differences between the extracted archives of the 2.7.3 and 2.7.4
releases are exactly as expected.  Nothing seems amiss.

**Comment by busterb** [comment]
Works fine here with GNU tar on Linux as well. We'll definitely need more info.

**Comment by catatsuy** [comment]
Oh, sorry. I had failed to download in my environment. I tried again and succeeded.

**Comment by busterb** [comment]
Glad it worked out, thanks!
