### ISSUE TITLE
Unexpected TLS 1.2 Alert [length 0002], fatal handshake_failure

### ISSUE THREAD

**Issue by czechxteam** [libressl-portable/portable#437]
Hi,
I am newbie in LibreSSL. I've built latest LibreSSL 2.8.0 on macOS 10.13.6 successfully.
Unfortunatelly while testing/using it I found one webserver where LibreSSL BIO_do_connection failed.
I am trying using LibreSSL to create TLS connection and using webrequest download image from https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/68dd54ca-60cf-4ef7-898b-26d7cbe48ec7/10-dithering-opt.jpg.
But LibreSSL BIO_do_connection failed (handshake error -> [LibreSSL logs.txt](https://github.com/libressl-portable/portable/files/2270293/LibreSSL.logs.txt) )
 despite the fact that Firefox/Chrome/Safari and also curl can download the image successfully without any handshake issue.

Are there any posibilities to ingnore this handshake error and create connection using BIO_do_connection(b) function.

Thank you

**Comment by kinichiro** [comment]
This site uses SNI, Qualys SSL Server Test tells us about it.
So, it requires servername to give the certificate you request.
I think you can connect with using `-servername` option, like below

```
$ openssl s_client -connect cloud.netlifyusercontent.com:443 -msg -servername cloud.netlifyusercontent.com
```

**Comment by czechxteam** [comment]
Thank you your command works 👍 
But now I need to realize successfull connection via BIO_do_connection.

**Comment by 4a6f656c** [comment]
In order to specify SNI with libssl, you want [`SSL_set_tlsext_host_name()`](http://man.openbsd.org/SSL_set_tlsext_host_name). That said, if this is new code you probably want to consider looking at [libtls](http://man.openbsd.org/tls_config_new), rather than libssl, since it will handle many of these types of things for you.

**Comment by czechxteam** [comment]
Solved for me, thank you, for your time.
