### ISSUE TITLE
Renegotiation is broken with specific changes in cipher suite

### ISSUE THREAD

**Issue by Sp1l** [libressl-portable/portable#443]
I received a request to verify if renegotiation was working with LibreSSL from one of the Apache httpd devs.
With a bit of checking, I found out that it neither worked client- nor server-side.

* cURL 7.61.0
   * libcurl/7.61.0 LibreSSL/2.7.4 zlib/1.2.11 brotli/1.0.5 nghttp2/1.32.1
   * libcurl/7.61.0 OpenSSL/1.0.2o zlib/1.2.11 nghttp2/1.32.1
* Apache httpd
   * 2.4.34 LibreSSL 2.7.4
   * 2.5.1 (20180710 snapshot) OpenSSL 1.1.1pre9

cURL | Apache | Result
---- | ----- | -----
OpenSSL| LibreSSL | SSL_read: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac, errno 0
LibreSSL | LibreSSL | SSL_read: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac, errno 0
LibreSSL | OpenSSL | SSL_read: error:1401E3FC:SSL routines:CONNECT_CR_FINISHED:sslv3 alert bad record mac, errno 0
OpenSSL | OpenSSL | HTTP/1.1 200 OK

In all cases, the initial connection is OK, `SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384`, the errors appear in the renegotiation when the /renegotiate/cipher/ is requested.

Tested with `curl -ks --connect-timeout 5 -v --http1.1 https://test.brnrd.eu:42002/renegotiate/cipher`
Config in Apache httpd:
```
LoadModule ssl_module libexec/apache24/mod_ssl.so
LoadModule socache_shmcb_module   libexec/apache24/mod_socache_shmcb.so

Listen 42002 https

SSLHonorCipherOrder on
#SSLPolicy modern
# TLSv1.2 config
SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA"

SSLSessionCache         "shmcb:/var/run/apache24/ssl_scache(512000)"
SSLSessionCacheTimeout  300

SSLUseStapling          on
SSLStaplingResponderTimeout 5
SSLStaplingReturnResponderErrors off
SSLStaplingCache        "shmcb:/var/run/apache24/ocsp(128000)"

SSLCACertificateFile    "share/certs/ca-root-nss.crt"

<VirtualHost _default_:42002>
DocumentRoot www/apache24/data

SSLEngine On
SSLCertificateFile    /etc/ssl/certs/brnrd.eu.pem
SSLCertificateKeyFile /etc/ssl/priv/brnrd.eu.key

<Location /renegotiate/cipher>
   SSLCipherSuite ECDHE-RSA-AES128-SHA256
</Location>
</VirtualHost>
```

**Comment by icing** [comment]
Thanks, @Sp1l. If there is any clarification needed from httpd, please let me know.

**Comment by kinichiro** [comment]
With openssl(1) s_server and s_client, it seems that renegotiation succeeds.
I had confirmed that after s_client connecting to s_server, type "r" on s_server terminal.
I tested this with LibreSSL 2.7 and OpenSSL 1.0.2 on OpenBSD 6.3.

**Comment by icing** [comment]
@kinichiro thanks, however it is curious that this combination fails when curl talks to httpd. What can we do to track this down? A wireshark session?

**Comment by Sp1l** [comment]
@4a6f656c So I actually created this issue in the wrong repo... Since there's a non-published patch for this already, I'd think I just leave this here and link the commit in libressl-portable/openbsd when it lands there. Thanks!

**Comment by 4a6f656c** [comment]
This has been fixed via https://github.com/openbsd/src/commit/f1abf68627e51bc3621a614ccccf1e70315337bb.
