### ISSUE TITLE
What happened to the support for non-blocking sockets?

### ISSUE THREAD

**Issue by nillith** [libressl-portable/portable#444]
It was mentioned in the early history ([here](https://wiki.freebsd.org/LibreSSL/History#LibreSSL_2.1.3) and [here](https://wiki.freebsd.org/LibreSSL/History#LibreSSL_2.2.0)) and nowhere to be found anymore. Is it discarded or have another name? Can anyone give me a direction where I can find how to use it?

**Comment by bob-beck** [comment]
Please see the man page for tls_read and tls_write where this is explained in detail
