### ISSUE TITLE
Intermittent SSL connection failures with Apache 2.4.34 & LibreSSL 2.7.4

### ISSUE THREAD

**Issue by seanthingee** [libressl-portable/portable#445]
Recently upgraded to Apache 2.4.34 and LibreSSL 2.7.4. A day after updating Pingdom began reporting of sporadic connection errors. This is happening on at least 3 similarly configured servers (same OS, packages, configs).

Doesn't seem to be well correlated to load, as it also happens during relatively dead times overnight. Only lasts 1-3 minutes approximately. It can also be seen in the browser: sometimes the connection would fail, sometimes the CSS would fail to load, but most of the time it works.

The only way I've been able to reliably trigger it is to use apache bench and hammer the server until it cries about an SSL issue. When I do, it shows this:

```
34398214872:error:04FFF06A:rsa routines:CRYPTO_internal:block type is not 01:rsa/rsa_pk1.c:103:
34398214872:error:04FFF072:rsa routines:CRYPTO_internal:padding check failed:rsa/rsa_eay.c:680:
34398214872:error:1400907B:SSL routines:CONNECT_CR_KEY_EXCH:bad signature:ssl_clnt.c:1502:
SSL handshake failed (1).
```

Restarting Apache clears the issue for approximately 1-2 hours. We're running FreeBSD 10.4-RELEASE-p11. Built all packages with poudriere. 

I've just swapped and installed the latest OpenSSL from ports and my ab test comes back clean now after many thousands of requests.

I don't know much about this stuff, but I thought I should report what I know in case there are others having trouble.

----

**Pingdom's error:**

`32189:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:607:GET /sign-in HTTP/1.0`

**Apache debug log for SSL:**

The failures look like this:
```
[Tue Sep 25 12:23:57.043705 2018] [ssl:info] [pid 826:tid 34494061568] [client xxx.xxx.xxx.xxx:46180] AH01964: Connection to child 146 established (server xxxx.com:443)
[Tue Sep 25 12:23:57.044308 2018] [ssl:debug] [pid 826:tid 34494061568] ssl_engine_kernel.c(2139): [client xxx.xxx.xxx.xxx:46180] AH02043: SSL virtual host for servername xxxx.com found
[Tue Sep 25 12:23:57.079012 2018] [ssl:info] [pid 826:tid 34494061568] [client xxx.xxx.xxx.xxx:46180] AH02008: SSL library error 1 in handshake (server xxxx.com:443)
[Tue Sep 25 12:23:57.079035 2018] [ssl:info] [pid 826:tid 34494061568] SSL Library Error: error:1403741B:SSL routines:ACCEPT_SR_KEY_EXCH:tlsv1 alert decrypt error (SSL alert number 51)
[Tue Sep 25 12:23:57.079041 2018] [ssl:info] [pid 826:tid 34494061568] [client xxx.xxx.xxx.xxx:46180] AH01998: Connection closed to child 146 with abortive shutdown (server xxxx.com:443)
```

The successes look like this:
```
[Tue Sep 25 12:24:06.683529 2018] [ssl:info] [pid 858:tid 34494066688] [client xxx.xxx.xxx.xxx:46724] AH01964: Connection to child 215 established (server xxxx.com:443)
[Tue Sep 25 12:24:06.686780 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_kernel.c(2139): [client xxx.xxx.xxx.xxx:46724] AH02043: SSL virtual host for servername xxxx.com found
[Tue Sep 25 12:24:06.702202 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0xbc -> subcache 28)
[Tue Sep 25 12:24:06.702217 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(847): AH00847: insert happened at idx=1, data=(221:253)
[Tue Sep 25 12:24:06.702222 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=0/2, data_pos/data_used=0/442
[Tue Sep 25 12:24:06.702225 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Tue Sep 25 12:24:06.702236 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_kernel.c(2064): [client xxx.xxx.xxx.xxx:46724] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Tue Sep 25 12:24:06.710332 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_kernel.c(370): [client xxx.xxx.xxx.xxx:46724] AH02034: Initial (No.1) HTTPS request received for child 215 (server xxxx.com:443)
[Tue Sep 25 12:24:06.710410 2018] [authz_core:debug] [pid 858:tid 34494066688] mod_authz_core.c(817): [client xxx.xxx.xxx.xxx:46724] AH01626: authorization result of Require all granted: granted
[Tue Sep 25 12:24:06.710415 2018] [authz_core:debug] [pid 858:tid 34494066688] mod_authz_core.c(817): [client xxx.xxx.xxx.xxx:46724] AH01626: authorization result of <RequireAny>: granted
[Tue Sep 25 12:24:06.713317 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_io.c(1099): [client xxx.xxx.xxx.xxx:46724] AH02001: Connection closed to child 215 with standard shutdown (server xxxx.com:443)
[Tue Sep 25 12:24:06.731603 2018] [ssl:info] [pid 858:tid 34494066688] [client xxx.xxx.xxx.xxx:46728] AH01964: Connection to child 215 established (server xxxx.com:443)
[Tue Sep 25 12:24:06.731768 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_kernel.c(2139): [client xxx.xxx.xxx.xxx:46728] AH02043: SSL virtual host for servername xxxx.com found
[Tue Sep 25 12:24:06.763863 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(493): AH00831: socache_shmcb_store (0x22 -> subcache 2)
[Tue Sep 25 12:24:06.763884 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(847): AH00847: insert happened at idx=2, data=(442:474)
[Tue Sep 25 12:24:06.763890 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(850): AH00848: finished insert, subcache: idx_pos/idx_used=0/3, data_pos/data_used=0/663
[Tue Sep 25 12:24:06.763894 2018] [socache_shmcb:debug] [pid 858:tid 34494066688] mod_socache_shmcb.c(515): AH00834: leaving socache_shmcb_store successfully
[Tue Sep 25 12:24:06.763902 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_kernel.c(2064): [client xxx.xxx.xxx.xxx:46728] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
[Tue Sep 25 12:24:06.771991 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_kernel.c(370): [client xxx.xxx.xxx.xxx:46728] AH02034: Initial (No.1) HTTPS request received for child 215 (server xxxx.com:443)
[Tue Sep 25 12:24:06.772073 2018] [authz_core:debug] [pid 858:tid 34494066688] mod_authz_core.c(817): [client xxx.xxx.xxx.xxx:46728] AH01626: authorization result of Require all granted: granted
[Tue Sep 25 12:24:06.772078 2018] [authz_core:debug] [pid 858:tid 34494066688] mod_authz_core.c(817): [client xxx.xxx.xxx.xxx:46728] AH01626: authorization result of <RequireAny>: granted
[Tue Sep 25 12:24:06.775691 2018] [ssl:debug] [pid 858:tid 34494066688] ssl_engine_io.c(1099): [client xxx.xxx.xxx.xxx:46728] AH02001: Connection closed to child 215 with standard shutdown (server xxxx.com:443)
```

**Comment by kinichiro** [comment]
I tried to see this and focused on this error message.

```
34398214872:error:04FFF06A:rsa routines:CRYPTO_internal:block type is not 01:rsa/rsa_pk1.c:103:
```

It appears to fail with RSA certificate decryption by padding problem.
LibreSSL is expecting RSA_PKCS1_PADDING, but client (ab or Pingdom) maybe use other padding.
But I can't tell why this happens sometimes.

Do you have any other information around these things ?

**Comment by seanthingee** [comment]
@kinichiro Sorry, I don't have anymore information, I tried to provide all the information I had at the time. It wasn't just ab or Pingdom, the SSL failures were occasionally seen in the browser (Chrome, at least), and it was experienced in a browser by a few others as well.

However, I did make a backup of the server. I could restore it to investigate it further, especially if there is more debug logging that could be enabled or something specific I could look for. I am willing to do that, but I would need some direction from someone.

What I can report is that we've had zero issues since swapping LibreSSL 2.7.4 for OpenSSL 1.0.1u.

**Comment by kinichiro** [comment]
Hi @seanthingee,

>I've just swapped and installed the latest OpenSSL from ports and my ab test comes back clean now after many thousands of requests.

What is the version of your swapped OpenSSL from ports ? 1.0.2 ? 1.1.0 ?

>What I can report is that we've had zero issues since swapping LibreSSL 2.7.4 for OpenSSL 1.0.1u.

And, before Apache 2.4.34, what version of Apache did you use with OpenSSL 1.0.1u ?

I'm not sure though, I suspect this might be a problem handling multi thread.
We can see the same kind of report on ML.
https://marc.info/?t=153884939500002&r=1&w=2

LibreSSL had forked from OpenSSL 1.0.1, and I believe the way of handling multi thread is not changed.

OpenSSL 1.1.0 has changed threading API.
Below is from https://www.openssl.org/news/cl110.txt

```
OpenSSL now uses a new threading API. It is no longer necessary to
set locking callbacks to use OpenSSL in a multi-threaded environment
```

I wonder that application adapted to OpenSSL 1.1.0 or later using with LibreSSL might cause multi threading issue.

Regards,

**Comment by Sp1l** [comment]
Recently worked on a [threading issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=62668) with Apache httpd team when using OpenSSL 1.1.1. That was specific to new functionality in Apache httpd's trunk combined with iirc.

Other Apache httpd instances I run with LibreSSL 2.7 haven't been problematic. They don't have much load either though. 

Hope that helps a bit.

**Comment by kinichiro** [comment]
I copied mttest.c from OpenSSL 1.0.2 codebase and modified to build with LibreSSL 2.8.1.
Here is the soure file.
https://gist.github.com/kinichiro/13cd81520c9b9442286fcc8fe68c8487

This requires ca.pem and server.pem, and I copied them from tests/ directory.

Just running this with no option, it succeeds.
With `-nolock` option, it sometimes fails, like below.

```
$ ./mttest -nolock
reaping
ERROR in CLIENT
25414570648096:error:04FFF06A:rsa routines:CRYPTO_internal:block type is not 01:/work/libressl-2.8.1/crypto/rsa/rsa_pk1.c:103:
25414570648096:error:04FFF072:rsa routines:CRYPTO_internal:padding check failed:/work/libressl-2.8.1/crypto/rsa/rsa_eay.c:680:
25414570648096:error:1400907B:SSL routines:CONNECT_CR_KEY_EXCH:bad signature:/work/libressl-2.8.1/ssl/ssl_clnt.c:1555:
error[3] 25414570648096 - 1
pthreads threads done
cleanup
       0:<<ERROR>>
       0:err
       0:ex_data
       0:x509
       0:x509_info
       0:x509_pkey
       0:x509_crl
       0:x509_req
       0:dsa
       0:rsa
       0:evp_pkey
       0:x509_store
       0:ssl_ctx
       0:ssl_cert
       0:ssl_session
       0:ssl_sess_cert
       0:ssl
       0:ssl_method
       0:rand
       0:rand2
       0:debug_malloc
       0:BIO
       0:gethostbyname
       0:getservbyname
       0:readdir
       0:RSA_blinding
       0:dh
       0:debug_malloc2
       0:dso
       0:dynlock
       0:engine
       0:ui
       0:ecdsa
       0:ec
       0:ecdh
       0:bn
       0:ec_pre_comp
       0:store
       0:comp
       0:fips
       0:fips2
done cleanup
Client SSL_CTX stats then free it
   0 items in the session cache
  94 client connects (SSL_connect())
  93 client connects that finished
   0 server connects (SSL_accept())
   0 server connects that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
Server SSL_CTX stats then free it
   0 items in the session cache
   0 client connects (SSL_connect())
   0 client connects that finished
  94 server connects (SSL_accept())
  93 server connects that finished
   0 session cache hits
   0 session cache misses
   0 session cache timeouts
done free
```

Using `-threads 100` option will increase the chance to show above.

By `-nolock` option, `CRYPTO_THREADID_set_callback()` and `CRYPTO_set_locking_callback()` are removed.
So, I think application that suffers this issue might forget to call these functions.

**Comment by kinichiro** [comment]
It appears that mod_ssl remove thread locking by this commit, since OpenSSL 1.1.0 has it as builtin.
https://svn.apache.org/viewvc?view=revision&revision=1735875

Those removed code is wrapped by #if like this.

```
#if APR_HAS_THREADS
#if OPENSSL_VERSION_NUMBER < 0x10100000L
```

OPENSSL_VERSION_NUMBER of LibreSSL is 0x20000000L (in opensslv.h).

I believe this disables thread locking with LibreSSL and Apache and causes this issue.

**Comment by kinichiro** [comment]
Last comment was by taking a look at the old commit.

Latest 2.4 uses this #if to enable or disable thread locking functions in ssl_util.c,

```
#if APR_HAS_THREADS && MODSSL_USE_OPENSSL_PRE_1_1_API
```

MODSSL_USE_OPENSSL_PRE_1_1_API is defined as (1) when `LIBRESSL_VERSION_NUMBER < 0x2070000f` in ssl_private.h.
This causes MODSSL_USE_OPENSSL_PRE_1_1_API will be (0) with LibreSSL 2.7.4.
Latest trunk changes this to `LIBRESSL_VERSION_NUMBER < 0x2080000f` in ssl_private.h

I think other define (say, MODSSL_USE_OPENSSL_THREAD_API etc.) should be needed to enable/disable thread locking functions, than using MODSSL_USE_OPENSSL_PRE_1_1_API for this purpose.

**Comment by busterb** [comment]
We should look at switching to the automatic locking methods as well. One of the blockers to making libcrypto/ssl depend on threading from the OS unconditionally was with lacking pthread stub support in the OpenBSD installer images, but IIRC that was resolved in the 2.7 time-frame when libtls gained thread-safe initialization support.

**Comment by 4a6f656c** [comment]
@seanthingee - this is almost certainly an issue in the modssl code - I'd suggest raising this with upstream and having them reinstate the locking initialisation for LibreSSL, at least for the time being. We're working on implementing automated lock initialisation, but it is not available in current versions.

**Comment by busterb** [comment]
Automated lock initialization is now in the tree and should be implemented in LibreSSL 2.9.0, but not earlier versions.

**Comment by busterb** [comment]
Going to close this since we know the root issue and the initial fix went out with 2.9.0.

**Comment by whande1992** [comment]
I have the same problem ..

First I noticed that the server was receiving nonsense requests, with random addresses and ips, so I put a block on port 80 and left it only at 443, this is really a ssl problem or will it be some kind of brute force trying to break into the server or simply overloading?

[Thu Apr 01 20:14:43.952552 2021] [ssl:info] [pid 5922:tid 140192614668032] SSL Library Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (SSL alert number 46)
[Thu Apr 01 20:14:43.952572 2021] [ssl:info] [pid 5922:tid 140192614668032] [client 192.168.254.1:50001] AH01998: Connection closed to child 11 with abortive shutdown (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:43.955257 2021] [ssl:info] [pid 5922:tid 140192480483072] [client 177.155.139.190:9246] AH01964: Connection to child 18 established (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:45.867246 2021] [ssl:info] [pid 5922:tid 140192673416960] [client 192.168.254.1:64320] AH01964: Connection to child 4 established (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:47.747086 2021] [ssl:info] [pid 5922:tid 140192463697664] [client 192.168.254.1:36779] AH01964: Connection to child 20 established (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:47.752240 2021] [ssl:info] [pid 5922:tid 140192463697664] [client 192.168.254.1:36779] AH02008: SSL library error 1 in handshake (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:47.752311 2021] [ssl:info] [pid 5922:tid 140192463697664] SSL Library Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (SSL alert number 46)
[Thu Apr 01 20:14:47.752341 2021] [ssl:info] [pid 5922:tid 140192463697664] [client 192.168.254.1:36779] AH01998: Connection closed to child 20 with abortive shutdown (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:48.109834 2021] [ssl:info] [pid 5922:tid 140192698595072] [client 100.67.154.239:60091] AH01964: Connection to child 1 established (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:50.122680 2021] [ssl:info] [pid 5922:tid 140192782345984] [client 192.168.254.1:49029] AH01964: Connection to child 0 established (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:50.128216 2021] [ssl:info] [pid 5922:tid 140192782345984] [client 192.168.254.1:49029] AH02008: SSL library error 1 in handshake (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:50.128273 2021] [ssl:info] [pid 5922:tid 140192782345984] SSL Library Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (SSL alert number 46)
[Thu Apr 01 20:14:50.128305 2021] [ssl:info] [pid 5922:tid 140192782345984] [client 192.168.254.1:49029] AH01998: Connection closed to child 0 with abortive shutdown (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:51.973206 2021] [ssl:info] [pid 5923:tid 140192589489920] [client 192.168.254.1:44371] AH01964: Connection to child 78 established (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:51.980660 2021] [ssl:info] [pid 5923:tid 140192589489920] [client 192.168.254.1:44371] AH02008: SSL library error 1 in handshake (server time.autmaster.com.br:443)
[Thu Apr 01 20:14:51.980726 2021] [ssl:info] [pid 5923:tid 140192589489920] SSL Library Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (SSL alert number 46)
[Thu Apr 01 20:14:51.980760 2021] [ssl:info] [pid 5923:tid 140192589489920] [client 192.168.254.1:44371] AH01998: Connection closed to child 78 with abortive shutdown (server time.autmaster.com.br:443)

**Comment by busterb** [comment]
As noted above, I believe we fixed this 2 years ago. Are you unable to update to a newer version than 2.7.4 @whande1992 ? If you're not using that version, please do open a new issue, thanks.
