### ISSUE TITLE
Autogen isn't building on local windows system because user's name has space

### ISSUE THREAD

**Issue by phrocker** [libressl-portable/portable#449]
This occurs in a windows build that is a dependency ( via ExternalProject ) because of the spaces when running the commands to build the version files. I corrected this with the following changes, where I surrounded the command with quotes. Happy to submit a simple PR if this is okay to the maintainers. 

+. "$libcrypto_src/shlib_version"
+. "$libssl_src/shlib_version"
+. "$libtls_src/shlib_version"

**Comment by kinichiro** [comment]
Could you post your PR to see all the build succeed, please ?
If you post, travis-ci and appveyor will test all the build.

**Comment by busterb** [comment]
I'll just add this on. Thanks!

**Comment by busterb** [comment]
See 156cdf6d19933ea60496d150764286c7fed5d2d8
