### ISSUE TITLE
"ssl_clnt.c:173:10: fatal error: ssl_sigalgs.h: No such file or directory" during compilation in Linux

### ISSUE THREAD

**Issue by neerajpal09** [libressl-portable/portable#457]
Hi there,

I am facing the issue of one header file called  "`ssl_sigalgs.h`".
I have done the following steps on Fedora 29 ( Linux Kernel: 4.19.0 ): 

1. git clone https://github.com/libressl-portable/portable.git libressl
2. cd libressl && sh autogen.sh
3. ./configure --prefix="${HOME}/opt/libressl"
4. make (also tried make -j4)

Output of `./configure --prefix="${HOME}/opt/libressl"` script:
[xxx@localhost libressl]$ ./configure --prefix="${HOME}/opt/libressl"
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking if gcc supports "-fno-strict-overflow"... yes
checking if gcc supports "-D_FORTIFY_SOURCE=2"... no
checking if /usr/bin/ld -m elf_x86_64 supports "-Wl,-z,relro"... yes
checking if /usr/bin/ld -m elf_x86_64 supports "-Wl,-z,now"... yes
checking if gcc supports "-fstack-protector-strong"... yes
checking whether AS supports .note.GNU-stack... yes
checking dependency style of gcc... gcc3
checking if compiling with clang... no
checking whether CC supports -Wno-pointer-sign... yes
checking for symlink... yes
checking for funopen... no
checking err.h usability... yes
checking err.h presence... yes
checking for err.h... yes
checking readpassphrase.h usability... no
checking readpassphrase.h presence... no
checking for readpassphrase.h... no
checking for asprintf... yes
checking for freezero... no
checking for memmem... yes
checking for readpassphrase... no
checking for reallocarray... yes
checking for recallocarray... no
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for strnlen... yes
checking for strsep... yes
checking for strtonum... no
checking for timegm... yes
checking for _mkgmtime... no
checking for getpagesize... yes
checking for accept4... yes
checking for pipe2... yes
checking for pledge... no
checking for poll... yes
checking for socketpair... yes
checking for arc4random... no
checking for arc4random_buf... no
checking for arc4random_uniform... no
checking for explicit_bzero... yes
checking for getauxval... yes
checking for getentropy... yes
checking for timingsafe_bcmp... no
checking for timingsafe_memcmp... no
checking for getauxval... (cached) yes
checking for library containing dl_iterate_phdr... none required
checking for dl_iterate_phdr... yes
checking for library containing clock_gettime... none required
checking for clock_gettime... yes
checking whether va_copy exists... yes
checking whether __va_copy exists... yes
checking for library containing b64_ntop... no
checking for library containing __b64_ntop... -lresolv
checking for b64_ntop... yes
checking if BSWAP4 builds without __STRICT_ALIGNMENT... no
checking if .gnu.warning accepts long strings... yes
checking size of time_t... 8
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/openssl/Makefile
config.status: creating crypto/Makefile
config.status: creating ssl/Makefile
config.status: creating tls/Makefile
config.status: creating tests/Makefile
config.status: creating apps/Makefile
config.status: creating apps/ocspcheck/Makefile
config.status: creating apps/openssl/Makefile
config.status: creating apps/nc/Makefile
config.status: creating man/Makefile
config.status: creating libcrypto.pc
config.status: creating libssl.pc
config.status: creating libtls.pc
config.status: creating openssl.pc
config.status: executing depfiles commands
config.status: executing libtool commands

If there anything I have forgotten to download then please let me know.
Thanks

**Comment by kinichiro** [comment]
Now, many changes are going on in upstream.
I think we should keep from building from this repository, now.
Soon, portable build will be fine, again.
You can download release tarball from https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/ .

**Comment by mikemadden42** [comment]
I had a similar issue on macOS.  I found I had to checkout a specific tag.  The following gist documents what worked for me.

https://gist.github.com/mikemadden42/67c7ba9d855775545fe4bc1cd5134de1

**Comment by busterb** [comment]
We're currently in active development, so expect as bleeding-edge bits are checked into the tree to have occasional breakage for the next several days as -portable syncs up.

More to come. https://www.openbsd.org/hackathons.html
