### ISSUE TITLE
libressl used to cross-compile until the last day or two :(

### ISSUE THREAD

**Issue by hydra3333** [libressl-portable/portable#462]
https://github.com/libressl-portable/portable
libressl used to build until the last day or two :(

now a cross-compile aborts with the error below.
(ubuntu mingw64 target windows x86_64)

Suggestions would be welcomed.

```
config:

	'libressl' : {
		'repo_type' : 'git',
		'url' : 'https://github.com/libressl-portable/portable.git',
		#'branch' : '',
		'folder_name' : 'libressl_git',
		'configure_options': '--host={target_host} --prefix={target_prefix} --disable-shared --enable-static ',
		'patches' : [
			( 'https://raw.githubusercontent.com/hydra3333/h3333_python_cross_compile_script/master/patches/libressl/libressl-0001-ignore-compiling-test-and-man-module.patch', '-Np1' ),
		],
		'_info' : { 'version' : 'git (master)', 'fancy_name' : 'libressl' },
	},

```

Error:
```
patching file tests/ocsp_test.c
patching file apps/openssl/openssl.c
Hunk #1 succeeded at 350 (offset -46 lines).
patching file tests/rfc5280time.c
patching file ssl/ssl_txt.c
patching file include/tls.h
patching file libtls-standalone/include/tls.h
patching file tls/tls_config.c
patching file tls/tls_util.c
patching file tests/tlsexttest.c
patching file include/openssl/dtls1.h
patching file include/openssl/opensslconf.h
patching file include/openssl/ossl_typ.h
patching file include/openssl/pkcs7.h
patching file include/openssl/x509.h
copying manpages
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:29: installing './compile'
configure.ac:20: installing './config.guess'
configure.ac:20: installing './config.sub'
configure.ac:21: installing './install-sh'
configure.ac:21: installing './missing'
apps/nc/Makefile.am: installing './depcomp'
automake: error: cannot open < crypto/Makefile.am.elf-arm: No such file or directory
autoreconf: automake failed with exit status: 1

```

**Comment by hydra3333** [comment]
I wonder, this does not seem right ?
`automake: error: cannot open < crypto/Makefile.am.elf-arm: No such file or directory`

given that we're in ubuntu under mingw64, cross-compiling for a windows x64 target.

It use to work until recently.

**Comment by busterb** [comment]
Wow, a lot more people seem to constantly build on `master` than I thought. I just forgot to add a file, try again: 3172a42c45776e570d5157d19c175314a6948308

**Comment by busterb** [comment]
Note, if you're always grabbing `master` from github for your production builds, you probably want to reconsider using releases instead. This is the development branch and it might be occasionally broken.

If you're just testing, go ahead, and thanks for the report (I woke up this morning and realized the file was missing too).

**Comment by busterb** [comment]
As as a post-script, as I write this, there are a couple of other things that -portable has to catch up with in the tree on the openbsd side, since we're in the middle of a hackathon. Fixing those now.

**Comment by hydra3333** [comment]
Thanks.
Backtracking my ffmpeg build script to use release 2.8.2.
Cheers
