### ISSUE TITLE
msbuild lots of warnings (libressl-2.8.2.tar.gz)

### ISSUE THREAD

**Issue by Dravion** [libressl-portable/portable#465]
Hi,
After downloading and unzipping to folder "libressl" and running CMake with untouched default settings,
CMake configures and generates a Makefile for msbuild. However: After running msbuild libressl.sln i get a long list of Warnings but no Errors, see attached log
[msbuild-11-15-2018-VisualC++2013.log](https://github.com/libressl-portable/portable/files/2584472/msbuild-11-15-2018-VisualC%2B%2B2013.log)

**Comment by busterb** [comment]
Almost all of them are a benign warning about a type definition in parenthesis in a header file:

8): warning C4115: 'timespec' : named type definition in parentheses [C:\Users\Dravion\Documents\Visual Studio 2013\Pro

$ grep -c "in parentheses" msbuild-11-15-2018-VisualC++2013.log
855
$ grep -c "warning" msbuild-11-15-2018-VisualC++2013.log
912

**Comment by busterb** [comment]
Looks like we need an additional include to get the struct timespec definition here, will take a look.

**Comment by Dravion** [comment]
Would be awesome. I regulary use LibreSSL for our Windows OpenSource Project (hMailServer) because OpenSSL 1.1.x has a lot of API changes. Regarding the Warnings, yeah i think thats the way to go. If you commited it somewhere, i will test it and report back.

**Comment by busterb** [comment]
This fixes 95% of the warnings, the rest will need to be addressed upstream:

4f1c9507b6c434f2e85ae8de49dea09e8fa97c78

**Comment by busterb** [comment]
I'll pull this specific fix into the 2.8.x branch and close this out. Not going to fix all of the warnings in 2.8 but this should take care of most of them.

**Comment by Dravion** [comment]
Ok, i copy and pasted your time.h fix and it really reduced most of the msbuild stdout warnnings. Strange that CMake doesnt include the remaining 41 Warnings for 2.8.2 in its own build logs - maybe it counts only real errors?

Ok, here are the buildlogs for Compiler Visual C/C++ 2013 Update 5 for 
arch  i386, amd64 and ARM

[ERROR_msbuild-11-16-2018-VisualC++2013_win32_arm.log](https://github.com/libressl-portable/portable/files/2590094/ERROR_msbuild-11-16-2018-VisualC%2B%2B2013_win32_arm.log)
[msbuild-11-16-2018-VisualC++2013_win32_i386.log](https://github.com/libressl-portable/portable/files/2590096/msbuild-11-16-2018-VisualC%2B%2B2013_win32_i386.log)
[msbuild-11-16-2018-VisualC++2013_win64_amd64.log](https://github.com/libressl-portable/portable/files/2590097/msbuild-11-16-2018-VisualC%2B%2B2013_win64_amd64.log)
