### ISSUE TITLE
Android build failure with CMake

### ISSUE THREAD

**Issue by tux3** [libressl-portable/portable#471]
Hello,

For Android versions prior to API Level 21, `getpagesize` is defined inline in `unistd.h` and is not detected properly by the CMakeLists.txt, resulting in a re-definition that breaks the build.

Currently LibreSSL looks for functions using [`check_function_exists`](https://cmake.org/cmake/help/v3.13/module/CheckFunctionExists.html), but as the doc mentions it can't find inline functions and should be replaced by [`check_symbol_exists`](https://cmake.org/cmake/help/v3.13/module/CheckSymbolExists.html#module:CheckSymbolExists)

This issue seems to be similar to #354, but this time the problem is with CMake.
I can confirm that replacing just the 
`check_function_exists(getpagesize HAVE_GETPAGESIZE)` 
line by
`check_symbol_exists(getpagesize unistd.h HAVE_GETPAGESIZE)`
fixes the issue, but ideally all the `check_function_exists` calls should be replaced.

**Comment by busterb** [comment]
Care to propose a PR? Locally, I get something like this as a result:

```
$cmake -GNinja ..
CMake Error at CMakeLists.txt:234 (check_symbol_exists):
  Unknown CMake command "check_symbol_exists".

$ cmake --version
cmake version 3.10.2
```

I haven't looked more closely, but perhaps there's more to it. If you submit a PR the build automation should do checks on some more cmake versions.

**Comment by tux3** [comment]
It seems libressl currently asks for CMake >= 2.8.8, but `check_symbol_exists` was introduced in 3.0.

However I tried to use CMake 2.8.8 and it failed with:

```
CMake Error at crypto/CMakeLists.txt:830 (target_include_directories):
  Unknown CMake command "target_include_directories".
```

So I suppose it's fine to bump the requirement to 3.0.

**Comment by busterb** [comment]
Thanks. I didn't catch this for 2.9.0, but will grab for 2.9.1

**Comment by dmcamens-legrand** [comment]
@tux3 Hello!  I am trying to find out how to build libressl in Android Studio.  I have not been able to find any documentation specific to building for Android.  Are there any hints you can give me for doing that?  Are there any special options/parameters I need to give or would I simply invoke CMake from my gradle script?  Any insight you can give would be appreciated.  Thanks!

**Comment by tux3** [comment]
@dmcamens-legrand 
Hi! Building OpenSSL on Android is in fact a special kind of hell if you're not familiar with it, our Android project has a pretty complex build setup so unfortunately I can't just give you a build script, but here's one way to do it:

- First you need to build LibreSSL using the Android NDK. You can do that using CMake, bash scripts, or whatever build system you like (we use the Conan package manager). Just make sure it's using the NDK's toochain (which is basically a custom clang compiler) and not your system's compiler.
- Then you need to tell Gradle where to find your prebuilt library, typically you put something like this in your `build.gradle`, and have your build system copy your library in that folder :

```gradle
android {
    sourceSets.main {
        jniLibs.srcDir 'src/main/jniLibs'
    }
}
```

For reference there are other ways to do it, you could point Gradle to a CMakeLists.txt that build LibreSSL and let it take care of things automagically. That's rumored to sometimes work.

**Comment by dmcamens-legrand** [comment]
@tux3 Thank you!  I am currently trying to point Gradle to the CMakeLists.txt that comes with LibreSSL like you mentioned, but that hasn't worked yet.  My Gradle is not playing nice with CMake so far.  I am getting this error during Gradle Sync: 

**Error:Error occurred while communicating with CMake server. Check log /Users/doug/Git_Local/lightingandroid/app/.externalNativeBuild/cmake/debug/armeabi-v7a/cmake_server_log.txt for additional information.**

The log file doesn't give any helpful info though.

Still trying...
