### ISSUE TITLE
AES-NI: Enable it in Windows platform

### ISSUE THREAD

**Issue by lars18th** [libressl-portable/portable#474]
Hi,

Any idea why the AES-NI support is enabled for Linux x64 and MacOSX 64 bit builds, and not for Windows 64bit target?

I see the config files: `CMakeLists.txt`, `Makefile.am.elf-x86_64` and `Makefile.am.macosx-x86_64` with directives to compile `aes/aesni*.S` files. However, in the target repository of OpenSSL identical files `aes/aes*.asm` exist. Check it:
https://github.com/luvit/openssl/tree/master/asm/x64-win32-masm/aes
https://github.com/luvit/openssl/tree/master/asm/x64-elf-gas/aes
https://github.com/luvit/openssl/tree/master/asm/x64-macosx-gas/aes

Please, try to enable to compile the code for AES-NI in LibreSSL for the Windows 64bit target.
Thank you!

**Comment by busterb** [comment]
Thanks for the note. There is no specific technical reason it's disabled, just a matter of no-one having done the work yet.

**Comment by lars18th** [comment]
> Thanks for the note. There is no specific technical reason it's disabled, just a matter of no one having done the work yet.

Great! So, I hope someone will enable it. Then the Windows OpenSSH _native_ server will adquire AES-NI support.

Regards. :wink:

**Comment by lars18th** [comment]
Hi,
Is anyone working on this?

**Comment by busterb** [comment]
I had a notion to work on it at the hackathon this week. Patches welcome of course.

**Comment by feliwir** [comment]
Any progress regarding this topic? I read the following note in the CMakeLists.txt:
```
# XXX Disabled for now, CMake's MASM support seems to either never
# build supply ASM or build it with the C compiler in a mode where it
# does not parse correctly. It might be easier to get NASM support working.
```

**Comment by feliwir** [comment]
I've figured why the problem described above occurs. According to this document:
https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/languages/Assembler
The extensions for NASM support in CMake must be *.asm. Insead we call `set_property(SOURCE ${ASM_X86_64_MASM_SRC} PROPERTY LANGUAGE C)` which makes it not use the MASM assembler (check for Item Type). When changing the extension to *.asm and removing that property it works as expected.

**Comment by ValZapod** [comment]
https://github.com/libressl-portable/portable/pull/526 fixes this...
