### ISSUE TITLE
Win 10, VS 2017 CMake Error: CMake can not determine linker language for target: 

### ISSUE THREAD

**Issue by RussellHaley** [libressl-portable/portable#476]
Hi, I'm getting a the following errors building 2.9.0 on Win10 (MSVC version in the output below). 2.7.2 and 2.8.1 both build fine (though I had to patch the tests in 2.8.1).  

cmake output from 2.9.0:

C:\Users\russh\git\WinLua-Mk3\Sources\libressl [(v2.9.0) +4 ~0 -0 !]> mkdir .\build-2.9.0-x64

    Directory: C:\Users\russh\git\WinLua-Mk3\Sources\libressl

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/15/2018   8:50 PM                build-2.9.0-x64

C:\Users\russh\git\WinLua-Mk3\Sources\libressl [(v2.9.0) +4 ~0 -0 !]> cd .\build-2.9.0-x64\
C:\Users\russh\git\WinLua-Mk3\Sources\libressl\build-2.9.0-x64 [(v2.9.0) +4 ~0 -0 !]> cmake -DBUILD_SHARED_LIBS=ON -G"Visual Studio 15 2017 Win64" ..
-- The C compiler identification is MSVC 19.16.27024.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Using [MSVC] compiler
-- Looking for asprintf
-- Looking for asprintf - not found
-- Looking for reallocarray
-- Looking for reallocarray - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - not found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strndup
-- Looking for strndup - not found
-- Looking for strsep
-- Looking for strsep - not found
-- Looking for timegm
-- Looking for timegm - not found
-- Looking for arc4random_buf
-- Looking for arc4random_buf - not found
-- Looking for arc4random_uniform
-- Looking for arc4random_uniform - not found
-- Looking for explicit_bzero
-- Looking for explicit_bzero - not found
-- Looking for getauxval
-- Looking for getauxval - not found
-- Looking for getentropy
-- Looking for getentropy - not found
-- Looking for getpagesize
-- Looking for getpagesize - not found
-- Looking for timingsafe_bcmp
-- Looking for timingsafe_bcmp - not found
-- Looking for timingsafe_memcmp
-- Looking for timingsafe_memcmp - not found
-- Looking for memmem
-- Looking for memmem - not found
-- Looking for include file err.h
-- Looking for include file err.h - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of time_t
-- Check size of time_t - done
-- Looking for strtonum
-- Looking for strtonum - not found
-- Looking for pipe2
-- Looking for pipe2 - not found
-- Configuring done
CMake Error at crypto/CMakeLists.txt:829 (add_library):
  Cannot find source file:

    evp/m_sm3.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at ssl/CMakeLists.txt:44 (add_library):
  Cannot find source file:

    ssl_methods.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error at tests/CMakeLists.txt:373 (add_executable):
  Cannot find source file:

    sm3test.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: crypto
CMake Error: CMake can not determine linker language for target: ssl
CMake Error: CMake can not determine linker language for target: sm3test
-- Generating done
-- Build files have been written to: C:/Users/russh/Git/WinLua-Mk3/Sources/libressl/build-2.9.0-x64

**Comment by busterb** [comment]
Thanks. Are you using a release tarball or the code from this repo?

I just added 2017 as a target for appveyor, will see how it does there: https://ci.appveyor.com/project/busterb/portable/builds/21041564

**Comment by busterb** [comment]
Looks like the 2017 builds worked fine on Appveyor too.

I suspect, because it couldn't find the source file, that you might have failed to properly run the autogen.sh command to populate the source tree before building. Check the README.md file for notes on that, and I recommend using the release tarballs if you can. Thanks.

**Comment by RussellHaley** [comment]
Thanks @busterb. Egg on my face, I forgot I had run that in MSYS2 on 2.7.1. 

I just tested Debian Stretch under Window 10 WSL and autogen.sh succeeded there as well (sudo apt install git build-essential autoconf libtool).

I'd be happy to help update the readme to indicate it's possible to run autogen.sh under Windows?

**Comment by busterb** [comment]
Outside of docs, I wonder if there is a way to add a CMake rule that fails more gracefully if a file is missing, that could produce a helpful error message. I've answered this question enough times that I'm sure it would help someone.

Locally, I just run autogen.sh with Cygwin, or run 'make dist' on a machine that does have the tools installed, and copy the resulting files to the other build machines.
