### ISSUE TITLE
Function crypto_init_locks not being called

### ISSUE THREAD

**Issue by Johnex** [libressl-portable/portable#478]
While working on this pull request: https://github.com/libressl-portable/portable/pull/477
I saw that crypto_init_locks is not being called automatically anywhere in the library. That means that the WaitForSingleObject functions are using un-initialized variables, and therefore firing instantly, without waiting for a lock.

The locks are at the same time not freed anywhere in the library either, leaking memory (CloseHandle not being called) on program close.

**Comment by busterb** [comment]
Ah right, upstream modified this later to use static initialization instead.

**Comment by 4a6f656c** [comment]
It probably needs to be done via a `DllMain` in order to initialise once at DLL load time:

  https://docs.microsoft.com/en-us/cpp/build/run-time-library-behavior?view=vs-2017

**Comment by Johnex** [comment]
As i wrote in the pull request, DllMain does not work for statically linked libraries.
