### ISSUE TITLE
[Question] Redistributing libressl windows binaries

### ISSUE THREAD

**Issue by OCram85** [libressl-portable/portable#480]
Hello libressl community,
I just wanted to ask if I'm allowed to repackage your portable windows binaries into my own open-source project?

### :book:  Background
I'm currently looking for a simple solution working with certificates within my projects without any external dependencies. Therefore I would simply put your build artifacts in a internal `vendor/libressl` path and working with them. But I'm not quite sure if this allows with your libressl / openssl licencing

**Comment by busterb** [comment]
Sure? What binaries are you looking at?

**Comment by busterb** [comment]
There is no problem redistributing LibreSSL in binary form. If you have more specific questions, this might make more sense to ask on on the mailing list where more people might see it.

**Comment by OCram85** [comment]
Thanks for the feedback :D

I just wanted to include the portable windows binaries from your [ftp server](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.5.5-windows.zip).

So will there be newer windows ports than version `2.5.5` in the future?

**Comment by busterb** [comment]
LibreSSL currently builds on Windows in every release; every pull request even builds multiple versions of Visual Studio and mingw. We just have not released official binary DLLs due to the wide variety of ABIs that Windows supports, and improved tooling in LibreSSL making builds easier for anyone to perform.

**Comment by sergeevabc** [comment]
Any place to get LibreSSL 2.9.0 as `openssl.exe` x64 binary?

**Comment by OCram85** [comment]
Any changes newer release will be dropped in [https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/](https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/) or anywhere else?

**Comment by petesky** [comment]
Hello. Any chance to get 2.9.1 x86 binaries (XP support ?)
