### ISSUE TITLE
Bug in crypto/evp/c_all.c ???

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [libressl-portable/portable#483]
Current OpenSSL `crypto/evp/c_allc.c` has the following:

    #ifndef OPENSSL_NO_CHACHA
        EVP_add_cipher(EVP_chacha20());
    # ifndef OPENSSL_NO_POLY1305
        EVP_add_cipher(EVP_chacha20_poly1305());
    # endif
    #endif

LibreSSL 2.8.3 has similar in file `crypto/evp/c_all.c` file:

    #ifndef OPENSSL_NO_CHACHA
            EVP_add_cipher(EVP_chacha20());
    #endif

Is the lack of `EVP_add_cipher(EVP_chacha20_poly1305());` a bug?

The reason I ask is GnuTLS test program `tests/slow/cipher-openssl-compat.c` has the following:

    static int cipher_test(const char *ocipher, gnutls_cipher_algorithm_t gcipher,
                           unsigned tag_size)
    {
        /* snip */
                    /* decrypt with openssl */
                    evp_cipher = EVP_get_cipherbyname(ocipher);
                    if (!evp_cipher)
                            fail("EVP_get_cipherbyname failed for %s\n", ocipher);
        /* snip */
    }

It is used in the following test code:

    #if OPENSSL_VERSION_NUMBER >= 0x10100000L
            if (!gnutls_fips140_mode_enabled()) {
                    cipher_test("chacha20-poly1305-ietf", GNUTLS_CIPHER_CHACHA20_POLY1305, 16);
            }
            cipher_test("aes-128-ccm", GNUTLS_CIPHER_AES_128_CCM, 16);
            cipher_test("aes-256-ccm", GNUTLS_CIPHER_AES_256_CCM, 16);
    #endif

The `aes-[128,256]-ccm` tests I expect to fail in LibreSSL because I believe LibreSSL does not have the CCM ciphers. So those should be wrapped in a `#if !defined (LIBRESSL_VERSION_NUMBER)`

ChaCha20-Poly1305 however should I believe work, but it doesn't, and I am wondering if it is from the lack of a `EVP_add_cipher(EVP_chacha20_poly1305());` ???

It is `EVP_get_cipherbyname` that is failing.

Reference: https://gitlab.com/gnutls/gnutls/merge_requests/846

**Comment by busterb** [comment]
The first item should be addressed in https://github.com/libressl-portable/openbsd/commit/628a76852adf0351ea8664b93a5ccf7deba79e71

**Comment by AliceWonderMiscreations** [comment]
Yes it is, and I can verify that the first item is resolved with that change.

**Comment by fichtner** [comment]
Is EVP_chacha20_poly1305() still planned? OpenVPN 2.5 changed its standard to ChaCha20-Poly1305 in release 2.5 but cannot find it with LibreSSL.

**Comment by 4a6f656c** [comment]
LibreSSL 3.6.1 includes support for `EVP_chacha20_poly1305()` (and it has been confirmed to work with OpenVPN).
