### ISSUE TITLE
CMake build  fails for a series of Operating Systems and Compiller versions

### ISSUE THREAD

**Issue by Dravion** [libressl-portable/portable#490]
Updated:
CMakeLists.txt generates Errors on all tested Platforms
MacOS, Win10/Cygwin64, Win10/VS2017, Ubuntu18

CentOS Linux release 7.6.1810 (Core) wie SELinux enabled doesnt support CMake 3.0.x
but autogen.sh + configure + make builds fine.

Seems to be only a CMake Problem
 
[libressl_upstream_error.txt](https://github.com/libressl-portable/portable/files/2723439/libressl_upstream_error.txt)

**Comment by Dravion** [comment]
Looks like the CMake Script for the uip archive of Release 2.9.0 from FTP works
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.9.0.tar.gz

**Comment by busterb** [comment]
Please read the similar issue filed here: https://github.com/libressl-portable/portable/issues/476#issuecomment-450757698 and the README.md with this project.

You have to run autogen.sh regardless of whether you run ./configure or use cmake.

**Comment by busterb** [comment]
See our appveyor and .travis templates for more hints on how you build this project:

https://github.com/libressl-portable/portable/blob/master/appveyor.yml
https://github.com/libressl-portable/portable/blob/master/scripts/travis

These scripts get run on every commit and every pull request, so if you think you see something broken locally, please first check the current build status for those systems.

**Comment by busterb** [comment]
https://ci.appveyor.com/project/busterb/portable
https://travis-ci.org/libressl-portable/portable

**Comment by Dravion** [comment]
Hi Brent,
Youre right i didnt read the manual (mea culpa)

However:
On Windows i will stick to the  tar.gz archive instead which works just fine with CMake.

ps:
Is there a major diffrence between LibreSSL Portable and OpenBSD LibreSSL?
I want to support OpenBSD builds to, so a little bit clarification (or a link to the Manuals which covers
the diffrencies) would be awesome.

Keep up the good work!

**Comment by busterb** [comment]
The differences are the entirety of this repo and are minimal. That's why running that script is so important, it actually grabs the source code from the openbsd tree and populates it here. Thus you're missing most of the code if you don't.

See https://github.com/libressl-portable/portable/tree/master/patches and https://github.com/libressl-portable/portable/tree/master/crypto/compat for most of the specific code deltas that are not from openbsd directly.
