### ISSUE TITLE
Solaris11 general build errors

### ISSUE THREAD

**Issue by Dravion** [libressl-portable/portable#494]
I getting multiple errors while building 
*Upstream LibreSSL (github master)

while executing ./autogen.sh (awk error, see logfile)
*Uninstalling/ReInstalling awk or greplacing it with Gawk doesnt help on Solaris11.4

Using:
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.8.3.tar.gz
and 
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.9.0.tar.gz

Results in build error:
  CC       libcrypto_la-cpt_err.lo
In file included from /usr/include/sys/time.h:447:0,
                 from ../include/compat/sys/time.h:13,
                 from /usr/include/sys/select.h:27,
                 from ../include/compat/sys/select.h:7,
                 from /usr/include/sys/types.h:665,
                 from ../include/compat/sys/types.h:13,
                 from /usr/include/sys/wait.h:12,
                 from /usr/include/stdlib.h:16,
                 from ../include/compat/stdlib.h:13,
                 from ../include/openssl/err.h:118,
                 from cpt_err.c:65:
/usr/include/sys/timespec_util.h:29:13: error: expected identifier or '(' before 'do'
 extern void timespecsub(const struct timespec *t1, const struct timespec *t2,
             ^
/usr/include/sys/timespec_util.h:29:13: error: expected identifier or '(' before 'while'
 extern void timespecsub(const struct timespec *t1, const struct timespec *t2,
[solaris11_autogen.sh_upstream_github_awk_step_error.log](https://github.com/libressl-portable/portable/files/2729590/solaris11_autogen.sh_upstream_github_awk_step_error.log)
[solaris11_gnu_make_after_cmake_compile_error-libressl-2.9.0.tar.gz.log](https://github.com/libressl-portable/portable/files/2729591/solaris11_gnu_make_after_cmake_compile_error-libressl-2.9.0.tar.gz.log)
[solaris11_gnu_make_compile_error-libressl-2.9.0.tar.gz.log](https://github.com/libressl-portable/portable/files/2729592/solaris11_gnu_make_compile_error-libressl-2.9.0.tar.gz.log)
[solaris11_gnu_make_compile_error-libressl-2.8.3.tar.gz.log](https://github.com/libressl-portable/portable/files/2729593/solaris11_gnu_make_compile_error-libressl-2.8.3.tar.gz.log)
[solaris11_gnu_make_after_cmake_compile_error-libressl-2.8.3.tar.gz.log](https://github.com/libressl-portable/portable/files/2729594/solaris11_gnu_make_after_cmake_compile_error-libressl-2.8.3.tar.gz.log)

**Comment by kinichiro** [comment]
Can you build if you remove the part below from include/compat/time.h ?

```
#ifndef timespecsub
#define timespecsub(tsp, usp, vsp)                                      \
        do {                                                            \
                (vsp)->tv_sec = (tsp)->tv_sec - (usp)->tv_sec;          \
                (vsp)->tv_nsec = (tsp)->tv_nsec - (usp)->tv_nsec;       \
                if ((vsp)->tv_nsec < 0) {                               \
                        (vsp)->tv_sec--;                                \
                        (vsp)->tv_nsec += 1000000000L;                  \
                }                                                       \
        } while (0)
#endif
```

**Comment by busterb** [comment]
Hmm, I tried it on my Solaris 11.3 box and didn't hit any issues at all (using https://www.opencsw.org/ packages for the toolchain). Unfortunately Oracle broke the upgrade path from 11.3 to 11.4 for free users, so haven't updated it to 11.4 yet.
