### ISSUE TITLE
Change directory for install target on Windows 10?

### ISSUE THREAD

**Issue by RussellHaley** [libressl-portable/portable#495]
Hi, 
I just found the wonderful INSTALL project/target in the VS solution. I'd like to change the destination directory so I can package the files in an MSI installer. I am building from Git and I rebuild the VS solution files frequently (trying to script the process) so modifying the solution file isn't desirable. I'm hoping for a command line switch or a suggestion on where to look to modify the cmake files?

Thanks!
Russ

**Comment by kinichiro** [comment]
You can use `CMAKE_INSTALL_PREFIX` to indicate where to install, like this.

```
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=C:\libressl ..
```

**Comment by RussellHaley** [comment]
Precisely what I was hoping for! Thank you Kinichiro-san.
