### ISSUE TITLE
Cross-building on Windows with CMake is broken

### ISSUE THREAD

**Issue by theodelrieu** [libressl-portable/portable#497]
Hello,

I'm trying to cross-build to Android on a Windows machine with CMake.

It currently fails because of the `crypto/CMakeLists.txt`, which uses variables like `CMAKE_HOST_WIN32` when it should use `WIN32`.

Since my build machine is Windows, it is trying to compile compatibility files for Windows targets, and it obviously fails.

I will open a PR next week (or today if I have some time).

**Comment by busterb** [comment]
OK, thanks.
