### ISSUE TITLE
AES wrap APIs?

### ISSUE THREAD

**Issue by aduskett** [libressl-portable/portable#505]
Hey guys; 

Sorry if this isn't the correct place to discuss missing API's, however, it seems to me that LibreSSL is missing the AES wrap API's that have been available in OpenSSL since 2015. These include:

aes_128_wrap
aes_192_wrap
aes_256_wrap

I have managed to get them working in a separate patch, but I am not sure the patches would be accepted (basically they are a direct copy and paste form OpenSSL 1.0.2r), as I know there is a long history of pulling bad APIs out of OpenSSL. However; I haven't been able to find any discussion surrounding these APIs either.

So my question:
Did the LibreSSL project remove or decide not to include these APIs for a reason?
If not:
Would the LibreSSL project accept a patch that introduces these APIs?

Thanks!

Adam

**Comment by botovq** [comment]
I'm unaware of a conscious decision against key wrapping - we do provide
the old AES_{un,}wrap_key API (only without padding).

However, we try to restrict our public API to things that are actually
used in the open source ecosystem or are otherwise needed. Debian
codesearch doesn't seem to show anything beyond the usual suspects.

What is your use case?

**Comment by aduskett** [comment]
My use case is actually setting up a tang server, which requires [Jose](https://github.com/latchset/jose/)
which uses those API's.

**Comment by botovq** [comment]
Thanks for the clarification. After some looking around I agree that
your suggestion of importing the API from OpenSSL 1.0.2r is the way to
go.

A patch would be welcome. It would be nice if it would have some minimal
tests (e.g. the test vectors from the relevant RFCs) accompanying it.

Feel free to ask if you need help.

**Comment by aduskett** [comment]
Thanks! I appreciate it!
I will see if I can add those APIs for you guys!

**Comment by botovq** [comment]
We committed the missing API to OpenBSD a bit earlier today (only the
versions without padding). This repo will be synced in the near future.

We also added the function `EVP_PKEY_get0_hmac()` which was the only bit
needed from the openssl compat code. On OpenBSD-current I can build José
without patching anything. The same should be true for LibreSSL 2.9 
portable once it is released.

**Comment by botovq** [comment]
Resolved in https://github.com/libressl-portable/openbsd/commit/bcfb7dc8e0d9a7cc196d9ed8cd458e6aa5d5b494 and subsequent commits.

**Comment by aduskett** [comment]
Hey! I just wanted to say thank you. I really do appreciate the help in this, you guys are amazing!
