### ISSUE TITLE
Tag v2.9.0 references master in OPENBSD_BRANCH

### ISSUE THREAD

**Issue by phrocker** [libressl-portable/portable#512]
While attempting to use v2.9.0 it seems that https://github.com/libressl-portable/portable/blob/v2.9.0/OPENBSD_BRANCH references master instead of a tag. Is this expected? It caused us build failures while attempting to use the tag.

**Comment by busterb** [comment]
There are no OPENBSD tags at all until there is an actual Openbsd release about every 6 months. Until then, 2.9.x is experimental / development.

Is there a reason you cannot use the released tarballs?

**Comment by busterb** [comment]
A revised history would look like this:

https://github.com/busterb/portable/commits/fix-2.9.0-tag?after=fab27893b3745b4fe4471dcea59a883c8deb1a21+34

If everyone's fine with it, I could make it happen; it'd just need everyone to rebase their forks and branches since the v2.9.0 tag.

**Comment by busterb** [comment]
Hmm, there's another complication, in that the libressl-* tags on the openbsd branch aren't regular tags, they're synced to the time of the tag in the portable tree here. So if I update the tag, it moves forward.

The more I think about it, it seems like the best thing to do is just to move forward with the next release.

**Comment by phrocker** [comment]
Hi Brent, thanks for the quick response. Yah I totally agree, moving forward is better than causing any troubles for anyone using the 2.9.0 tag.
