### ISSUE TITLE
Problem to connect over s_client to site with GOST encryption

### ISSUE THREAD

**Issue by inspirit1986** [libressl-portable/portable#518]
Hi, I have a problem to connect to site zakupki.gov.ru:443
I'm using latest libressl 2.9.0
With this command 
/var/opt/lib/libressl/bin/libressl s_client -connect zakupki.gov.ru:443
I have an error - 
**140665787037504:error:0BFFF07D:x509 certificate routines:CRYPTO_internal:public key decode error:asn1/x_pubkey.c:203:
140665787037504:error:140070EF:SSL routines:CONNECT_CR_CERT:unable to find public key parameters:ssl_clnt.c:1147:**

This server use GOST encryption(Public Key Algorithm: GOST R 34.10-2012 (256 bit)) with a couple of CA certificates in chain of trust.
(I can see it with **/var/opt/lib/libressl/bin/libressl s_client -connect zakupki.gov.ru:443  -showcerts**)

so i try to download CA certs:
http://roskazna.ru/gis/udostoveryayushhij-centr/kornevye-sertifikaty/
http://roskazna.ru/upload/iblock/7e3/guts_2012.cer
http://roskazna.ru/upload/iblock/acb/fk_2012.cer
[CA-cer.zip](https://github.com/libressl-portable/portable/files/3069198/CA-cer.zip)

and convert it to pem with this command
/var/opt/lib/libressl/bin/libressl x509 -inform der -in fk_2012.cer -out fk_2012.pem
/var/opt/lib/libressl/bin/libressl x509 -inform der -in guts_2012.cer -out guts_2012.pem
I attach all of this files to this message.

Then I try to use this command:
**/var/opt/lib/libressl/bin/libressl s_client -connect zakupki.gov.ru:443 -CApath /root/cert/**

but I still have got an error when connecting to this site 
140192863901504:error:0BFFF07D:x509 certificate routines:CRYPTO_internal:public key decode error:asn1/x_pubkey.c:203:
140192863901504:error:140070EF:SSL routines:CONNECT_CR_CERT:unable to find public key parameters:ssl_clnt.c:1147:

What I'm doing wrong? Please explain this problem to me. 
Thank in advance.

**Comment by algv** [comment]
> LibreSSL is API compatible with OpenSSL 1.0.1, but does not yet include all new APIs from OpenSSL 1.0.2 and later. LibreSSL also includes APIs not yet present in OpenSSL. The current common API subset is OpenSSL 1.0.1.

openssl 1.0.2 and libressl no have GOST-3410-2012 implementation. Work with [gostengy](https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=8544) or [gost-engine](https://github.com/gost-engine/engine)

**Comment by lumag** [comment]
@algv this is not true. LibreSSL has full support of GOST R 34.10-2012.
Unfortunately zakupki.gov.ru uses Edwards Twisted GOST curve in the certificate, which is not supported in LibreSSL.

**Comment by inspirit1986** [comment]
ok, i try to test connection with openssl 1.1.1 and gost engine and cert looks good.
New, TLSv1.0, Cipher is GOST2012-GOST8912-GOST8912
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.1
    Cipher    : GOST2012-GOST8912-GOST8912
    Session-ID:
    Session-ID-ctx:
    Master-Key: 0A75B579D53C93951F98E2483FF4C72A9C0BCCC846FB3200985E473558EF445D86A12828C404F46095C73AD7E4436722
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1556201443
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no

but then I was try to test squid 4.6 with ssl_bumping  enabled and my openssl 1.1.1 and gost-engine packages and I have a couple of troubles with it. So can libressl development team implement Edwards Twisted GOST curve in Libressl future releases as @lumag said?

**Comment by mikhailnov** [comment]
What has changed? It seems to work now.

```
# libressl s_client -connect eruz.zakupki.gov.ru:443
<...>
New, TLSv1/SSLv3, Cipher is GOST2012256-GOST89-GOST89
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.1
    Cipher    : GOST2012256-GOST89-GOST89
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 77CDDB2064F51E7E2EE518C834DDCA4ACD0CCDA9DE5FDC136062691921EF11AA211A60E0D46F1078CBDB108D39A59C19
    Start Time: 1577464175
    Timeout   : 7200 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
```

**Comment by kinichiro** [comment]
certificate seems changed on Jul-23-2019.

```
$ openssl x509 -in server.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
...(snip)...
        Validity
            Not Before: Jul 23 14:36:42 2019 GMT
            Not After : Oct 23 14:36:42 2020 GMT
...(snip)...
        Subject Public Key Info:
            Public Key Algorithm: GOST R 34.10-2012 (256 bit)
                Public key:
...(snip)...
                Parameter set: id-GostR3410-2001-CryptoPro-XchA-ParamSet
                Digest Algorithm: GOST R 34.11-2012 (256 bit)
        X509v3 extensions:
...(snip)...
    Signature Algorithm: GOST R 34.11-2012 with GOST R 34.10-2012 (256 bit)
...(snip)...
```

**Comment by kinichiro** [comment]
Hi @inspirit1986 
Is this still an issue ?
Can you close this ?

**Comment by inspirit1986** [comment]
Yep, now working well. problem solved. Closing.
