### ISSUE TITLE
LibreSSL VC++ 2019 / CMake defaults to x64

### ISSUE THREAD

**Issue by Dravion** [libressl-portable/portable#519]
Howdy,
I just downloaded the 2.9.1 tar.gz from the OpenBSD Mirror and was able to build the libs,
but i noticed some small issues. 

1) CMake 3.14.3 will default now to x64 (x86_64)  not x86 or Win32 anymore
2) In Terminal, the default for Win32 is now "x86" so msbuild LibreSSL.sln will fail

Workarround:
msbuild LibreSSL.sln /t:Build /p:Platform=Win32

For Win64 => x64 aka. x86_64 defaulting with "msbuild LibreSSL.sln" works fine

**Comment by Johnex** [comment]
You probably have some issue in your build process. For building via command line, you should select the correct build environment by either using the x86, x64 Native Tools Command Prompt shortcuts in the Start menu or doing:

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

Depending on architecture and replace 2019 with 2017 or your version, and the Enterprise with Professional or your version.

After that, you should select the correct compiler to use and architecture in cmake as well, like so:

cmake -G"Visual Studio 16 2019" -A"Win32" ..
cmake -G"Visual Studio 16 2019" -A"x64"   ..

The older visual studios have like so:

cmake -G"Visual Studio 16 2017" ..
cmake -G"Visual Studio 16 2017 Win64" ..

Lastly, to build you do:

msbuild /m /p:Configuration=Release ALL_BUILD.vcxproj

/m is for multicore, goes much faster, and you probably want to build release too.

You can make a batch file that will call vcvars32.bat, do cmake for 32bit, do the build, then repeat with vcvars64.bat and cmake for 64bit.

**Comment by Dravion** [comment]
No,  thats not the Problem.
I builded a lot of LibreSSL Versions on manys OSes, but 2.9.1 behaves diffrently because Kitware switched from Default Win32 to default x64. ReRead my above comment. I can build it, but now its slightly diffrent then a few CMake Relases before.

**Comment by Johnex** [comment]
I'm pretty sure the intention was to detect the architecture all along, but there was bug that was fixed for 2.9.0 so now it works:

https://github.com/libressl-portable/portable/commit/6c6b58f610a27516bf9ab0541be29d698be85678#diff-af3b638bc2a3e6c650974192a53c7291

If you want to select a specific architecture you should do it like i wrote above.

The behavior is the now the same as on linux, if you use cmake without any options, it will build for the current system architecture.

**Comment by kinichiro** [comment]
Hi @Dravion 
Is this still an issue for you ?
If resolved already, can you close this ?

**Comment by kinichiro** [comment]
I think this can close for now.
