### ISSUE TITLE
InitOnceExecuteOnce (pthread_once) and XP Support

### ISSUE THREAD

**Issue by d3x0r** [libressl-portable/portable#520]
InitOnceExecuteOnce does not exist on XP. (I suppose the official policy is Noone supports that?)

This was an addition in 2.9.0 to support 'pthread_once' on windows in include/compat/pthread.h

is pthread_once and a static pthread_once_t really any better than a static int inited = 0; if( !inited ) { init(); inited = 1; } ?  I suppose that should be some sort of interlocked exchange to prevent mulitple threads from initializing.

Edit: Revised 'hack' to a more functional replacement
Edit3: replace while(sleep) with wait.
```

/*
 * Static once initialization values.
 */
#define PTHREAD_ONCE_INIT   { CreateEvent(NULL,TRUE,FALSE,NULL) }

/*
 * Once definitions.
 */
struct pthread_once {
	HEVENT event;
	volatile LONG inited;
};
typedef struct pthread_once pthread_once_t;

static inline int
pthread_once(pthread_once_t *once, void (*cb) (void) ) {
	if( !InterlockedExchange( &once->inited, 1 ) ) {
		cb();
		SetEvent( event );
	}
	if( WaitForSingleObject( once->event, INFINITE ) == WAIT_OBJECT_0 )
		return 0;
	return 1;
}

```

**Comment by Johnex** [comment]
Well XP has been dead since 2014, so no security updates for it. Systems should upgrade to Windows 10 since Windows 7 is about to die soon too in less than a year. There is really no reason not to use Windows 10 now, or an embedded variant for ATMs and other such systems. There is even a Windows 10 IOT version.

I also don't see your suggestion as any better, the NOP loop gives me the hibbie jibbies. It should at least be a WaitForSingleObject.

**Comment by d3x0r** [comment]
The system is, XP, and just still works.  TLS 1.3 support will really kill it (or lack thereof) other than things like firefox which provide it as a library outside of the system.
The owner doesn't want to kill it by installing something which may or may not be good; plus there's stuff already setup on it that would get lost *shrug* I've migrated and moved on as time has gone on... 

I'm not defending that anything really be done.
ya I suppose an `HEVENT event = CreateEvent();` is simple enough.

Even though it's under no support there's lots of things that just still work.

**Comment by Johnex** [comment]
Can i ask what is it being used for? Firefox, Chrome, most software have stopped support for XP for some time, so anything the person is doing on the net is risk of a 0Day or randsomware etc.

Isn't it simpler to just clone the pc to a new drive, install new windows on it, test and run updated software than to have the risk of holes taking the system down silently? I mean if it's not important to update the OS, why bother even moving to the latest LibreSSL?

**Comment by d3x0r** [comment]
it's being used for sites that still only support IE.
Not likely those sites suddenly get compromised; it's not used to 'surf'.
Me updating to latest libressl has nothing to do with whether they update their system; other than when I compile and unknowinly get `InitOnceExecuteOnce() not found in kernel32.dll` and it's not anything _I_'ve added.  and then finding it only in some MS runtime library as a reference and blaming the compiler, eventually figuring out it was here, for 'pthread_once' which is used during init code, which (IMhO) should be singled threaded before any other code; but that's just me.

(If someone else stumbles on this I've updated the code in the first case to use an event statically initialized)
