### ISSUE TITLE
Visual Studio has no problem with GCC keyword '__attribute__' ?

### ISSUE THREAD

**Issue by GekkieHenkie** [libressl-portable/portable#521]
I should get compiler errors in Visual Studio (2019, but also 2017) about the GCC specific `__attribute__` lines.
What is making me scratch my head is that the library actually compiles on one of my windows PC using the built-in VS compiler as it is without complaining, but it doesn't compile on my other machine (a dual boot with both Windows and Linux) giving the expected compiler errors about the `__attribute__` lines when compiling in Windows using the VS compiler.

I checked and compared everything that I think relates to the builds between the two machines, and they are equal. I compared source code, I compared the CMake files and intermediate output. I compared the created VS solution and vcxproj files. I ran both builds from a completely clean `git clone`, and still in the end on the one Windows pc it compiles fine, and on the other windows pc it doesn't. And I have absolutely no idea why... :s

Do you have any idea about what I could've overlooked? Is there something I could have installed on pc 1 that influences the build (e.g.: something that results in ignoring the `__attribute__` keywords)?

**Comment by kinichiro** [comment]
Hi,
Now, I could build LibreSSL 2.9.1 with VS 2017 without any errors.
I had downloaded libressl-2.9.1.tar.gz from download site.
And I built like these commands.

```
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" ..
cmake --build .
cmake --build . --target RUN_TESTS
```

'\_\_attribute__' is used in tls_ext_alpn.c, and you can see '\_\_attribute__' is defined in opensslconf.h with hitting F12 while cursor on '\_\_attribute__'.

I think you can investigate how '\_\_attribute__' is defined with F12 on your failure PC

**Comment by kinichiro** [comment]
Hi, I confirmed that I also could build with VS2019.
Is this still an issue for you ?
If already resolved, can you close this ?

**Comment by kinichiro** [comment]
We can see Appveyor CI build succeeds with VisualStudio 2019.
https://ci.appveyor.com/project/busterb/portable/builds/39129830

I will close this now.
