### ISSUE TITLE
‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]

### ISSUE THREAD

**Issue by Dravion** [libressl-portable/portable#522]
Unused warning by 
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)

No cmake used.
Release: libressl-2.9.1.tar.gz from openbsd.org
./config 
./make

build successfull but this single warning

make[2]: Entering directory '/home/dravion/Projects/libressl-2.9.1/apps/ocspcheck'
  CC       http.o
  CC       ocspcheck.o
ocspcheck.c: In function ‘main’:
ocspcheck.c:673:10: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
   (void) ftruncate(staplefd, 0);
          ^~~~~~~~~~~~~~~~~~~~~~
  CCLD     ocspcheck
make[2]: Leaving directory '/home/dravion/Projects/libressl-2.9.1/apps/ocspcheck'

**Comment by busterb** [comment]
Fixed upstream in https://github.com/libressl-portable/openbsd/commit/ed936d8fe47ab96cd1c2c53058cc2903c00b316e
