### ISSUE TITLE
What license is this project，no License file or header is showing that

### ISSUE THREAD

**Issue by butterl** [libressl-portable/portable#527]
Hi,  is there a License file or copyright header for this project ?
Thanks

**Comment by busterb** [comment]
Yes, the license for the project is copied in from the OpenBSD source:

https://github.com/libressl-portable/portable/blob/master/update.sh#L72
https://github.com/libressl-portable/openbsd/blob/master/src/lib/libssl/LICENSE

Individual files may have a more liberal license, which is indicated at the top of each file.
