### ISSUE TITLE
clienttest: test-suite failure on libressl 2.9.2 with TLSv1.3

### ISSUE THREAD

**Issue by castilma** [libressl-portable/portable#533]
Hi,

compiling libressl 2.9.2 on artix linux and raspbian with #define
LIBRESSL_HAS_TLS1_3 uncommented in opensslfeatures.h makes the
test-suite fail one test: clienttest.

I ran
./configure --prefix=/usr/local/stow/libressl-2.9.2; make -j 4; make
check  -j 4;

both logs are attached.

[test-suite.log.armv7l.gz](https://github.com/libressl-portable/portable/files/3234693/test-suite.log.armv7l.gz)
[test-suite.log.gz](https://github.com/libressl-portable/portable/files/3234704/test-suite.log.gz)

(I sent this to the libressl mailinglist, but it seems it does not appear in the libressl list archive, so I figured it was classified as spam.)

**Comment by busterb** [comment]
It is commented out on purpose. When it's ready, it will be enabled. Thanks.
