### ISSUE TITLE
Illegal pkg-config file generated on macOS.

### ISSUE THREAD

**Issue by disigma** [libressl-portable/portable#539]
The variable `PLATFORM_LIBS` is empty for Darwin targets.
https://github.com/libressl-portable/portable/blob/b1823997485db869bd02f1a32467008ba1f03eff/CMakeLists.txt#L346

Therefore, the `PLATFORM_LDADD` will become a simple `-l` with no library,  which will result in a link error when LibreSSL is being statically linked.

https://github.com/libressl-portable/portable/blob/b1823997485db869bd02f1a32467008ba1f03eff/libssl.pc.in#L15

The issue can be fixed like this:
```CMake
if(PLATFORM_LIBS)
    string(REGEX REPLACE ";" " -l" PLATFORM_LDADD ";${PLATFORM_LIBS}")
endif()
```
Which will left `PLATFORM_LDADD` empty on platforms with no `PLATFORM_LIBS`.

**Comment by kinichiro** [comment]
@disigma can you check #540 works for you ?

**Comment by disigma** [comment]
I tested it, it works fine

**Comment by kinichiro** [comment]
@disigma Thanks for testing. PR was merged and I'll close this issue.
