### ISSUE TITLE
Merge -addext option from upstream

### ISSUE THREAD

**Issue by Ypnose** [libressl-portable/portable#544]
OpenSSL binary ```OpenSSL 1.1.1  11 Sep 2018``` now supports ```-addext ext``` option, useful to provide a specific extension, like SAN.
https://www.openssl.org/docs/man1.1.1/man1/req.html

OpenSSL binary from LibreSSL ```LibreSSL 2.9.2``` doesn't support it, so it is kinda inconvenient to generate CSR, where LibreSSL is used (OpenBSD, Linux distributions migrated to LibreSSL).

Here the command I used to test :
```
openssl req -sha256 -new -newkey rsa:4096 -nodes -addext "subjectAltName = DNS:foo.co.uk" -keyout pkey.pem -out csr.pem
```
Here the related discussion :
https://github.com/openssl/openssl/issues/3311

Could it possible to merge upstream change to LibreSSL ?

**Comment by Ypnose** [comment]
Hi,
Any update on this ?

**Comment by otto-dev** [comment]
Can't use `libressl` without this because of `subjectAltNames`

**Comment by kinichiro** [comment]
Here is temporary workaround to put subjectAltName without -addext option.

```Shell
#!/usr/local/bin/bash

openssl req -newkey rsa:2048 -days 365 -nodes -x509 \
    -subj "/C=/ST=/L=/O=/OU=/CN=*.foo.co.uk" \
    -extensions SAN \
    -config <(cat /etc/ssl/openssl.cnf \
            <(printf "[SAN]\nsubjectAltName='DNS:foo.co.uk'")) \
    -keyout pkey.pem -out csr.pem
```

**Comment by kinichiro** [comment]
-addext option was added in upstreram https://github.com/libressl-portable/openbsd/commit/6d415447a0c9cf1109b47b2dab7b6a9459f9754f

**Comment by ip75** [comment]
> Here is temporary workaround to put subjectAltName without -addext option.
> 
> ```shell
> #!/usr/local/bin/bash
> 
> openssl req -newkey rsa:2048 -days 365 -nodes -x509 \
>     -subj "/C=/ST=/L=/O=/OU=/CN=*.foo.co.uk" \
>     -extensions SAN \
>     -config <(cat /etc/ssl/openssl.cnf \
>             <(printf "[SAN]\nsubjectAltName='DNS:foo.co.uk'")) \
>     -keyout pkey.pem -out csr.pem
> ```

-extensions is not work with req command. libressl-3.0.2

**Comment by 4a6f656c** [comment]
@ip75 works for me...

```
$ openssl version
LibreSSL 3.0.2
$openssl req -newkey rsa:2048 -days 365 -nodes -x509 \
    -subj "/C=/ST=/L=/O=/OU=/CN=*.foo.co.uk" \
    -extensions SAN \
    -config <(cat /etc/ssl/openssl.cnf \
            <(printf "[SAN]\nsubjectAltName='DNS:foo.co.uk'")) \
    -keyout pkey.pem -out csr.pem
$ openssl x509 -text -in csr.pem | grep DNS: -B2
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:foo.co.uk
```

**Comment by 4a6f656c** [comment]
Closing since this will be available in the next release.
