### ISSUE TITLE
/etc/ssl/cert.pem is hardcoded in libtls

### ISSUE THREAD

**Issue by reyk** [libressl-portable/portable#556]
Hi,

I've installed LibreSSL's libtls on Ubuntu and it failed because it couldn't find the CA file (it is either the Ubuntu CA path `/etc/ssl/certs/` or the LibreSSL one in the custom prefix `/path/to/libressl/etc/ssl/cert.pem`).

I saw that there was issue #160 some years ago, but it seemed to got lost with the introduction of `default_ca_file`. I propose something like the following for portable `tls_config.c`:

```diff
-static const char default_ca_file[] = "/etc/ssl/cert.pem";
+static const char default_ca_file[] = _PATH_SSL_CA_FILE;
```

Reyk

**Comment by kinichiro** [comment]
Hi,

I think there are 2 ways to solve this issue.

Adding patches/tls_config.c.patch as provided above for portable version only.
```diff
-static const char default_ca_file[] = "/etc/ssl/cert.pem";
+static const char default_ca_file[] = _PATH_SSL_CA_FILE;
```

Or changing upstream tls/tls_config.c like this. I don't think this any harm on upstream.
```diff
-static const char default_ca_file[] = "/etc/ssl/cert.pem";
+#ifndef _PATH_SSL_CA_FILE
+#define _PATH_SSL_CA_FILE "/etc/ssl/cert.pem"
+#endif
+static const char default_ca_file[] = _PATH_SSL_CA_FILE;
```

**Comment by kinichiro** [comment]
https://github.com/libressl-portable/openbsd/commit/461e241c9b6c0a199a3f128d34ec82a7f2cc1cab was committed in upstream.
