### ISSUE TITLE
Plans to keep backward compatibility

### ISSUE THREAD

**Issue by mikhailnov** [libressl-portable/portable#562]
Can you please clarify plans to keep backwards compatibility as moving forward? OpenSSL is known to break compatibility often. Will LibreSSL keep being compatible with OpenSSL 1.0? I did not find such information.

**Comment by bob-beck** [comment]
In general terms, our current plan is to strive to keep backward
compatibility for the old stuff we know to be in use. We will (and already
have) deprecated or hidden a lot
of the old API that code searches tell us isn't used anywhere.

We have selectively been bringing in the new openssl api, again for things
that are necessary or in use.

We also reserve the right to have new (not compatible with OpenSSL) api for
future features.

**Comment by 4a6f656c** [comment]
As Bob said, as far as practical we will not be removing OpenSSL 1.0 interfaces/APIs that are used in the wild, any time soon.

**Comment by mikhailnov** [comment]
Good. Thanks for answering.
