### ISSUE TITLE
No official release for Windows

### ISSUE THREAD

**Issue by jacobslusser** [libressl-portable/portable#563]
Per the documentation, 
> If you cannot follow these instructions (e.g. Windows system using CMake) or cannot meet these prerequistes, please download an official release distribution from https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/ instead. Using official releases is strongly advised if you are not a developer.

However, the last official build for Windows seems to be v2.5.5 (from 2017), whereas, the library is currently at v3.0.2.

Is it possible to get Windows binaries for the most recent version(s)?

**Comment by busterb** [comment]
The comment above was talking about a source release, not a binary release. We stopped binary releases due to subtle incompatibility between toolchains and many varying options and needs between apps on Windows. The CMake build targets are pretty good too, do test and use them!

**Comment by tianyouhui** [comment]
### I have an error while use cmake to generate on Visual Studio 2019... Would you please have a look at this?  Thanks. 

Selecting Windows SDK version 10.0.18362.0 to target Windows 6.1.7601.
The C compiler identification is MSVC 19.26.28806.0
The ASM compiler identification is MSVC
Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
CMake Error at CMakeLists.txt:22 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/xxx/source/repos/portable-master/ssl/VERSION


CMake Error at CMakeLists.txt:23 (string):
  string sub-command STRIP requires two arguments.


CMake Error at CMakeLists.txt:24 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at CMakeLists.txt:25 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.


CMake Error at CMakeLists.txt:27 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/xxx/source/repos/portable-master/crypto/VERSION


CMake Error at CMakeLists.txt:28 (string):
  string sub-command STRIP requires two arguments.


CMake Error at CMakeLists.txt:29 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at CMakeLists.txt:30 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.


CMake Error at CMakeLists.txt:32 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/xxx/source/repos/portable-master/tls/VERSION


CMake Error at CMakeLists.txt:33 (string):
  string sub-command STRIP requires two arguments.


CMake Error at CMakeLists.txt:34 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at CMakeLists.txt:35 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.


Using [MSVC] compiler
Looking for asprintf
Looking for asprintf - not found
Looking for reallocarray
Looking for reallocarray - not found
Looking for strcasecmp
Looking for strcasecmp - not found
Looking for strlcat
Looking for strlcat - not found
Looking for strlcpy
Looking for strlcpy - not found
Looking for strndup
Looking for strndup - not found
Looking for strsep
Looking for strsep - not found
Looking for timegm
Looking for timegm - not found
Looking for arc4random_buf
Looking for arc4random_buf - not found
Looking for arc4random_uniform
Looking for arc4random_uniform - not found
Looking for explicit_bzero
Looking for explicit_bzero - not found
Looking for getauxval
Looking for getauxval - not found
Looking for getentropy
Looking for getentropy - not found
Looking for getpagesize
Looking for getpagesize - not found
Looking for getprogname
Looking for getprogname - not found
Looking for syslog_r
Looking for syslog_r - not found
Looking for syslog
Looking for syslog - not found
Looking for timespecsub
Looking for timespecsub - not found
Looking for timingsafe_bcmp
Looking for timingsafe_bcmp - not found
Looking for timingsafe_memcmp
Looking for timingsafe_memcmp - not found
Looking for memmem
Looking for memmem - not found
Looking for include file err.h
Looking for include file err.h - not found
Looking for clock_gettime
Looking for clock_gettime - not found
Looking for sys/types.h
Looking for sys/types.h - found
Looking for stdint.h
Looking for stdint.h - found
Looking for stddef.h
Looking for stddef.h - found
Check size of time_t
Check size of time_t - done
CMake Error at crypto/CMakeLists.txt:957 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/xxx/source/repos/portable-master/crypto/crypto.sym


CMake Error at crypto/CMakeLists.txt:959 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at cmake_export_symbol.cmake:10 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/xxx/source/repos/portable-master/ssl/ssl.sym
Call Stack (most recent call first):
  ssl/CMakeLists.txt:63 (export_symbol)


Looking for strtonum
Looking for strtonum - not found
CMake Error at cmake_export_symbol.cmake:10 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/xxx/source/repos/portable-master/tls/tls.sym
Call Stack (most recent call first):
  tls/CMakeLists.txt:40 (export_symbol)


Looking for pipe2
Looking for pipe2 - not found
Configuring incomplete, errors occurred!
See also "C:/Users/xxx/source/repos/portable-master/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/xxx/source/repos/portable-master/build/CMakeFiles/CMakeError.log".

**Comment by pedroalbanese** [comment]
I also needed it, I ended up compiling it myself some versions here:

https://sourceforge.net/projects/libressl-3-2-0-for-windows/

I hope it helps
