### ISSUE TITLE
SRP is missing

### ISSUE THREAD

**Issue by CharlesJQuarra** [libressl-portable/portable#566]
LibreSSL is claimed to be interface-compatible with OpenSSL 1.0.1, but OpenSSL 1.0.1 implements TLS-SRP 6a. While the original FreeBSD repo seems to contain some SRP primitives (https://cvsweb.openbsd.org/src/lib/libcrypto/srp/) they do not seem to be exposed to the user as of version 3.0.2

**Comment by kinichiro** [comment]
SRP seems to be deleted at 2.0.4.
You can see ChangeLog below.
https://github.com/libressl-portable/portable/blob/master/ChangeLog

**Comment by tysonclugg** [comment]
https://resources.infosecinstitute.com/libressl-the-secure-openssl-alternative/:
> **Functionality Removal**
> With the disclosure of the POODLE vulnerability, security analysts deemed SSLv3 insecure and not for use in production environments. However, many environments still require SSLv3 for legacy purposes and are unable to migrate to TLSv1.1. To this end, OpenSSL maintains backwards compatibility with SSLv3 and all applications compiled for SSLv3 are still operational. Conversely, LibreSSL 2.2.2 entirely removed SSLv3 support. _Additionally, LibreSSL removed weak or broken cipher suites, including the Secure Remote Password (SRP), Pre-Shared Key (PSK) and all Export ciphers._ LibreSSL added support for ChaCha, GOST and IDEA ciphers. While LibreSSL’s decisions provide technically enhanced security, this may be negatively impactful in environments that require legacy SSLv3 support.

**Comment by bob-beck** [comment]
We have deleted many things from OpenSSL 1.0.1. Sorry.  If you want SSLv3, or
you want SRP, you should probably be using a different library.
