### ISSUE TITLE
Libressl FIPS compliant?

### ISSUE THREAD

**Issue by bagajjal** [libressl-portable/portable#572]
Is LibreSSL FIPS compliant? Based on some [search results](https://opensslrampage.org/post/83555615721/the-future-or-lack-thereof-of-libressls-fips), it looks LibreSSL is not FIPS compliant.

Do you have any plans to be FIPS compliant?

**Comment by tysonclugg** [comment]
https://resources.infosecinstitute.com/libressl-the-secure-openssl-alternative/:
> **FIPS 140-2 Compliance**
> The OSF sought to make OpenSSL FIPS 140-2 compliance. Consequently, OSF created the OpenSSL FIPS Object Module, which provides an API to invoke FIPS approved cryptographic functions. This is particularly important for Federal IT systems that are obligated to comply with FIPS 140-2. _Conversely, LibreSSL removed the FIPS compliant module from its code, arguing that the FIPS 140-2 uses weak or broken ciphers and is detrimental to security. LibreSSL is neither FIPS 140-2 compliant nor is it a goal of the project._ This is potentially impactful for risk-averse government IT systems that are required to comply with FIPS 140-2.

**Comment by busterb** [comment]
The answer is no, and there are no plans to be. You're of course welcome to put in the effort independently. Thanks.
