### ISSUE TITLE
libressl 3.1.0 : compilation failure on Windows (using MSYS2 + mingw-w64)

### ISSUE THREAD

**Issue by vtorri** [libressl-portable/portable#584]
i tried the unstable version of libressl to see if it compiles or not. Here is how i configure it :

```
./configure --prefix=/opt/libressl --host=x86_64-w64-mingw32 --disable-static --enable-windows-ssp
```
I run make. Here is the last lines of the output : 
```
make[1] : on entre dans le répertoire « /home/vtorri/tmp/libressl-3.1.0/tests »
  CC       handshake_table.o
make[1]: ***  Aucune règle pour fabriquer la cible « /home/vtorri/tmp/libressl-3.1.0/tls/.libs/libtls.a », nécessaire pour « handshake_table.exe ». Arrêt.
make[1] : on quitte le répertoire « /home/vtorri/tmp/libressl-3.1.0/tests »
make: *** [Makefile:453 : all-recursive] Erreur 1
```

**Comment by kinichiro** [comment]
To build regression tests it requires static library as you can see in tests/Makefile.am.
Can you try configure without `--disable-static` ?

**Comment by vtorri** [comment]
It is indeed working.

In my case (regular user on windows), i don't really need tests, and static lib are not very used on Windows. Would it be possible to add a configure option to disable tests ?

I can eventually do a PR for this

thank you

**Comment by vtorri** [comment]
Hello

PR #585

regards

Vincent Torri

PS: I can't test because there are missing files in git repo (like VERSION
files)

**Comment by kinichiro** [comment]
@vtorri BTW, I found that just `make` does not build test.

**Comment by kinichiro** [comment]
@vtorri https://github.com/libressl-portable/portable/pull/585 was merged.
Can you close this ?

**Comment by vtorri** [comment]
merged, closing
