### ISSUE TITLE
Android: LibreSSL fails to load and use system CAs

### ISSUE THREAD

**Issue by aberaud** [libressl-portable/portable#597]
On Android, LibreSSL (used with Asio) fails to use the system CAs (at `/etc/security/cacerts`) and every certificate check fails with error 19 / unknown ca, despite calling:
`ssl_ctx->set_default_verify_paths(); // calls SSL_CTX_set_default_verify_paths`

The same code works fine on classic GNU/Linux systems.

I tried adding
`ssl_ctx->add_verify_path("/etc/security/cacerts/"); // calls SSL_CTX_load_verify_locations`
manually without success.

I noticed the source tree doesn't have any reference to `/etc/security/cacerts`.
I tried changing `crypto/cryptlib.h` to use `/etc/security/cacerts` for `X509_CERT_DIR`, without any luck.

**Expected behavior:**
LibreSSL should load Android system CAs when using set_default_verify_paths();

**Comment by kinichiro** [comment]
Hi,

You can set directory when you configure libressl with cmake, like

-DOPENSSLDIR=/etc/security


2020年6月30日(火) 2:51 Adrien Béraud <notifications@github.com>:

**Comment by aberaud** [comment]
Thanks,

however, this would not allow to set X509_CERT_DIR to the Android directory `/etc/security/cacerts/` since "certs" is appended instead of "cacert".

**Comment by aberaud** [comment]
See for instance how this is handled by GnuTLS:
https://github.com/gnutls/gnutls/blob/master/lib/system/certs.c#L218

Not tested yet but current code suggests LibreSSL would also fail to use system CAs on iOS.

Have anyone tried to use LibreSSL on Android or iOS ?
Thanks

**Comment by aberaud** [comment]
Made a PR for this:
https://github.com/libressl-portable/openbsd/pull/116

However, even with the right path, LibreSSL was unable to use system CAs to verify server certificates (code working fine on GNU/Linux). Always error 19 and "tlsv1 alert unknown ca".

**Comment by aberaud** [comment]
Just noticed with great horror that no code exists to load system CAs for any other system than GNU/Linux.

That means various projects use tricks like:
https://github.com/sfackler/rust-native-tls/pull/31/files
to get certificate verification working with system CAs.

iOS and macOS would also require system-specific code.

It sounds really insane that this is sill an unsolved problem in 2020. Am I missing something ?
Many thanks

**Comment by kinichiro** [comment]
Hi,

I have one question after reading all of your commets, again.
Do you have cert hash ((e.g., 9d66eef0.0) in your /etc/security/cacerts/ ?
Since you said "However, even with the right path, LibreSSL was unable to use system CAs to verify server certificates" after posting https://github.com/libressl-portable/openbsd/pull/116 .

https://man.openbsd.org/SSL_CTX_load_verify_locations.3 describes ;

>The files are looked up by the CA subject name hash value, which must hence be available. If more than one CA certificate with the same name hash value exist, the extension must be different (e.g., 9d66eef0.0, 9d66eef0.1, etc.).

If you don't, you can create cert hash by `openssl certhash -v <dir>`.
And if you do, I think `SSL_CTX_load_verify_locations(ctx, NULL, "/etc/security/cacerts")` would work.

**Comment by kinichiro** [comment]
@aberaud do you have any update for this issue ?
I posted my investigation above, and I think cert hash is required for this case.

**Comment by aberaud** [comment]
Hi,
We ended up embedding our own CA file on Android instead of trying to use the system one.

**Comment by kinichiro** [comment]
Thanks for your answering.
Can you close this issue now ?
