### ISSUE TITLE
build system and __STRICT_ALIGNMENT

### ISSUE THREAD

**Issue by q66** [libressl-portable/portable#602]
I've been poking around LibreSSL lately wrt importing assembly support for ppc(64(le)) and aarch64, and ran into some curious things:

1) there is the `__STRICT_ALIGNMENT` macro which seems to control whether the platform does or doesn't deal with supporting unaligned memory access; there is a similar macro in OpenSSL, called `STRICT_ALIGNMENT`
2) however, OpenSSL by default forces it on, except on platforms where it seems to be safe: https://github.com/openssl/openssl/blob/33388b44b67145af2181b1e9528c381c8ea0d1b6/include/crypto/modes.h#L30 Currently, these platforms are the x86 family, aarch64 and s390(x). ARMv7 used to be allowed, but got disabled at one point https://github.com/openssl/openssl/commit/29a546720b6d8ea8b3207f500e3ed9d2834b09f2 - that's why there are the `BSWAP4` and `BSWAP8` assembly macros, despite seemingly never being used.
3) LibreSSL drops the code that does this, which means `STRICT_ALIGNMENT` is always not defined by default.
4) The build system then conditionally defines it: https://github.com/libressl-portable/portable/blob/master/configure.ac#L78

As I see it, there are some issues with this.

1) This completely missed all those other platforms for which OpenSSL defines the macro but LibreSSL then doesn't
2) That check doesn't make much sense to me - as it seems to intend to work, it will pretty much pass for x86 family and 32-bit ARM and fail for everything else. That's because `BSWAP4` is defined when on ARM or x86 and when `__STRICT_ALIGNMENT` is not defined, but not under any other circumstances.
3) Another piece of code then implies it at least for SPARC, but nothing else
4) Then there is this line: `AS_IF([test "x$BSWAP4" = "xyes" -a "$host_cpu" = "arm" ],,CPPFLAGS="$CPPFLAGS -D__STRICT_ALIGNMENT")` This basically means that `__STRICT_ALIGNMENT` is always defined unless on 32-bit ARM. That was added by 8f32297dcedbb883b29f7a9e102dd34c7b69af6c and the previous behavior was different. Now, `__STRICT_ALIGNMENT` will be defined on x86, while previously it was not.
5) Of course, there is the fact that the `BSWAP4` check actually *never* passes - it will fail on not finding `machine/endian.h` as the test is run with incomplete includes. That means ultimately, `__STRICT_ALIGNMENT` is *always* defined no matter what, even on 32-bit ARM, because `BSWAP4` is `no`.

Can you clarify what the actual intentions are here? As I see it, `__STRICT_ALIGNMENT` should be defined similarly to OpenSSL, i.e. defined by default, and then explicitly disabled for platforms where it's safe to do so (generally x86 and aarch64 and I guess s390x, on others it's "safe" on Linux because the kernel will trap unaligned accesses but it's slow)

**Comment by q66** [comment]
I added a patch here: https://github.com/q66/libressl-portable-asm/blob/master/patches/0009-strict-alignment.patch

**Comment by kinichiro** [comment]
OpenBSD upstream codebase had decided to get __STRICT_ALIGNMENT from <machine/endian.h>, rather than define it in modes_lcl.h.
This commit is it.
https://github.com/libressl-portable/openbsd/commit/d901629c6e430fc89cdf0885f86150614c9bcc09

Currently portable build is trying to detect __STRICT_ALIGNMENT by BSWAP4 and has some issue as you mentioned.
I think portable build is also able to get it from there, since it has header file shim in it.
I had posted PR #604 to propose this.

Any comments are appreciated.

**Comment by q66** [comment]
Thanks for looking into this, let's move any further discussion into your pull request.

**Comment by kinichiro** [comment]
For this issue, https://github.com/libressl-portable/portable/pull/604 and https://github.com/libressl-portable/openbsd/commit/1809bbb5299b44df6d17ca5ea3943a2bdcb57f47 were applied already.
I would like to close this for now if no objection.
Are there any other work on this ?

**Comment by q66** [comment]
i think it's all addressed
