### ISSUE TITLE
MinGW-w64 Error

### ISSUE THREAD

**Issue by pedroalbanese** [libressl-portable/portable#615]
I am following the steps outlined in README.windows, but I am getting this error both MinGW and MSYS2. What am I doing wrong? 

  CC       compat/arc4random_uniform.lo
  CC       compat/getentropy_win.lo
  CCLD     libcompat.la
  CC       compat/libcompatnoopt_la-explicit_bzero_win.lo
  CCLD     libcompatnoopt.la
  CCLD     libcrypto.la
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: asn1/.libs/libcrypto_la-p5_pbev2.o: in function `memcpy':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: bio/.libs/libcrypto_la-b_dump.o: in function `memset':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:208: undefined reference to `__memset_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: des/.libs/libcrypto_la-enc_writ.o: in function `memcpy':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: dsa/.libs/libcrypto_la-dsa_gen.o: in function `memcpy':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: ec/.libs/libcrypto_la-eck_prn.o: in function `memset':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:208: undefined reference to `__memset_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/sys-root/mingw/include/string.h:208: undefined reference to `__memset_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: evp/.libs/libcrypto_la-e_rc4_hmac_md5.o: in function `memcpy':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: evp/.libs/libcrypto_la-p5_crpt.o: in function `memcpy':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: modes/.libs/libcrypto_la-cts128.o: in function `memcpy':
/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: undefined reference to `__memcpy_chk'
/usr/lib/gcc/i686-w64-mingw32/9.2.0/../../../../i686-w64-mingw32/bin/ld: modes/.libs/libcrypto_la-cts128.o:/usr/i686-w64-mingw32/sys-root/mingw/include/string.h:202: more undefined references to `__memcpy_chk' follow
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:3905: libcrypto.la] Erro 1
make[2]: Saindo do diretório '/cygdrive/h/PRGM/Linux/LibreSSL/libressl-3.2.0/crypto'

make[1]: *** [Makefile:2166: all] Erro 2
make[1]: Saindo do diretório '/cygdrive/h/PRGM/Linux/LibreSSL/libressl-3.2.0/crypto'

make: *** [Makefile:455: all-recursive] Erro 1

**Comment by kinichiro** [comment]
I could reproduce this on cygwin with libressl-3.2.1.tar.gz.
It seems that mingw-w64 requires linking `-lssp` if `_FORTIFY_SOUECE` is defined.
https://github.com/msys2/MINGW-packages/issues/5868

I think adding -lssp to PLATFORM_LDADD will fix this.

**Comment by pedroalbanese** [comment]
Sorry, but can you explain step-by-step how to do it? I know very little about compilers.. Thx

**Comment by pedroalbanese** [comment]
Thank You very much!
