### ISSUE TITLE
Changing path to openssl.cnf

### ISSUE THREAD

**Issue by pedroalbanese** [libressl-portable/portable#616]
Hello, I managed to compile the static binary via MinGW64, but it turns out that the program cannot find the file openssl.cnf. I have tried all combinations by placing the bin directory in relation to the /usr/local/etc/ssl/openssl.cnf path. But it seems that he does not seek the relative path as when compiled via Cygwin, but the /usr/ folder at the root.

How do I disable the message that the program did not find the config file (as in openssl)? I would like to disable this check, just by adding the -config parameter to the functions that actually need this file.

At least I would like to be able to leave openssl.cnf in the same directory as the static executable, otherwise I need to have several folders inside each other to avoid this error message.

I tried to change the line in the opensslconf.h file
#if defined (HEADER_CRYPTLIB_H) &&! defined (OPENSSLDIR)
#define OPENSSLDIR "./"
#endif

But it didn't have any effect (it works in openssl, but it didn't have any effect in LibreSSL).

How do I disable the configfile checking or change the path?

Thanks.

**Comment by kinichiro** [comment]
You can use  `./configure --with-openssldir=your-dir`.

**Comment by pedroalbanese** [comment]
That worked:

./configure --with-openssldir=c:/libressl/ssl 

(with backslashes only)

Thank you!!
