### ISSUE TITLE
Windows XP compatibility issue

### ISSUE THREAD

**Issue by pedroalbanese** [libressl-portable/portable#618]
Hello, I compiled the code with MinGW-w64, on Windows XP Cygwin, but the executable doesn't run on Windows XP, only on Windows7.. on XP I'm getting the error: 

"the procedure entry point could not be located in the dynamic link library KERNEL32.dll"

How to compile a XP compatible executable with MinGW-w64?

Thx in advance.

**Comment by pedroalbanese** [comment]
I also needed it, I ended up compiling it myself some versions:

https://sourceforge.net/projects/libressl-3-2-0-for-windows/

**Comment by WSLUser** [comment]
XP is unsupported and has been for a long time. Upgrade to Windows 10.

**Comment by pedroalbanese** [comment]
North Korea's public libraries use XP to this day. Here in the third world (South America) bank ATMs still run Windows XP. They intend to upgrade to Windows 7, not 10. Windows 10 is really horrible, I appreciate the suggestion but I discard, I stay with Debian / Kali and Windows 7 (when necessary). The XP build is not just for me. Fortunately it is perfectly possible to compile and run LibreSSL for Windows XP, I just couldn't do it static (without cygwin1.dll).

There are people who cannot buy Windows 10, which here costs 80% of a minimum wage.

I am grateful despite the underlying issue raised.

**Comment by WSLUser** [comment]
10 is the best there is. 7 is pretty good but 10 has the longest support. Also you can use WSL so you can have Debian and Kali installed side by side on Windows via the MS Store. XP will not be supported because its too old. In order to get any support for it, prepare to pay billions and it has to be for business as it's a contract.

**Comment by pedroalbanese** [comment]
Precisely, colleague. I would not have the effort to compile LibreSSL for Windows 10 as there is already WSL. My concern is to extend support for the Streebog algorithm in all versions of Windows still in use.

The upgrade is not under discussion, as I said, it is an underlying issue. It is much more likely that I will return to Windows XP than "evolve" to Windows 10 As I said, it sucks. It is the modern version of the Windows 98 nightmare. But I don't need none Windows to run Kali.

Every time an operating system goes wrong, Microsoft runs to launch another fastly, this happened from Millennium to XP, from Vista to Windows 7, and from Windows 8, to 10. Windows 10 is a Frankinstein, not an OS

I just imagined that there was a way to compile with MinGW since it is possible with Cygwin. Worse, I imagined that someone there could know / inform that.

Here's proof that you don't know what you're talking about:
https://sourceforge.net/projects/libressl-3-2-0-for-windows/files/

**Comment by pedroalbanese** [comment]
Even OpenSSL 1.1.1g runs on XP, it just doesn't support GOST Engine, which requires Windows 7 SP 1.

**Comment by busterb** [comment]
Windows XP, in addition to being out of support, doesn't have all of the underlying primitives that LibreSSL needs. Windows 7 is the minimum bar just from a capabilities point of view.

**Comment by pedroalbanese** [comment]
@WSLUser

Here is the solution that costs zero cents and is more versatile and complete than LibreSSL. Never underestimate a person because of the operating system they use.
https://github.com/pedroalbanese/edgetk

**Comment by WSLUser** [comment]
Great but it's far too insecure to use. I don't plan on going to win 11 either though. Once win 10 support goes, I'm switching to linux

**Comment by TinCanTech** [comment]
"_Ten years later..._"
