### ISSUE TITLE
Incorrect key exporter behavior with TLS 1.3

### ISSUE THREAD

**Issue by nmathewson** [libressl-portable/portable#629]
Hello!

I'm a Tor developer.  Tor uses SSL_export_keying_material() as part of its protocol, and we've been seeing compatibility problems starting with LibreSSL 3.2.1.  (Link to Tor ticket is https://gitlab.torproject.org/tpo/core/tor/-/issues/40128 .)

If I am diagnosing this correctly, it looks like tls1_export_keying_material() is unconditionally using the exporter function from RFC 5705.  But TLS 1.3 defines a completely different exporter function, in RFC 8446 section 7.5.  This means that whenever LibreSSL negotiates a TLS 1.3 connection and tries to export keying material, it does not generate the same result  as other TLS 1.3 implementations.  This issue in turn causes Tor relays running LibreSSL not to interoperate with other relays running TLS 1.3.

It looks like we started encountering this with LibreSSL 3.2.1 because that's the version where LibreSSL enabled TLS 1.3 in `TLS_method()`.

[Please let me know if there is a better place to report this, or if I have completely misdiagnosed this issue. I am not super familiar with the LibreSSL source.]

**Comment by kinichiro** [comment]
I tested this issue by openssl(1) s_server and s_client with -keymatexport option like below,
and I saw "Keying material:" outputs were different between server and client.
I used LibreSSL 3.2.2.

```
$ openssl s_server -CAfile ca.pem -cert server.cer -keymatexport 'IV block' -keymatexportlen 8
```

```
$ openssl s_client -CAfile ca.pem -keymatexport 'IV block' -keymatexportlen 8
```

OpenSSL 1.1.1 outputs the same "Keying material:" value.
LibreSSL 3.2.2 with -tls1_2 option shows the same "Keying material:" outputs.

**Comment by nmathewson** [comment]
Is there a better place than this to report LibreSSL bugs?

**Comment by botovq** [comment]
On Fri, Nov 06, 2020 at 07:23:59AM -0800, Nick Mathewson wrote:
> Is there a better place than this to report LibreSSL bugs?

Thanks a lot for the report and issues are fine. You're right on the
money with your analysis. A fix is currently under review.

**Comment by nmathewson** [comment]
Thank you, Theo!  I wasn't sure whether this was the best bugtracker to use, and I'm very glad you saw the issue.

**Comment by kinichiro** [comment]
https://github.com/libressl-portable/openbsd/commit/6e2ae6018f8ad5bba7cd973e4360c215dee79bcc will resolve this issue.

**Comment by kinichiro** [comment]
@nmathewson can you close this issue ?

**Comment by kinichiro** [comment]
This issue was fixed and closed.
