### ISSUE TITLE
LibreSSL-3.2.2 regression

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#630]
LibreSSL-3.2,2 does not report expired certificate
LibreSSL-3.2.1 is ok

found on haproxy automatic testing

https://github.com/haproxy/haproxy/issues/916

**Comment by kinichiro** [comment]
Same report on ML https://marc.info/?l=libressl&m=160339671313132&w=2

**Comment by kinichiro** [comment]
Discussed on https://marc.info/?t=160342489400001&r=1&w=2 .
Commit https://github.com/libressl-portable/openbsd/commit/088a7d74ed4debc807631c57c08844f3529d725f will resolve this issue.

**Comment by 4a6f656c** [comment]
Thanks for the report - this issue has been addressed in newer releases, closing.
