### ISSUE TITLE
EVP_DigestSign/EVP_DigestVerify are not supported by LibreSSL

### ISSUE THREAD

**Issue by nicraMarcin** [libressl-portable/portable#632]
When we can expect support for EVP_DigestSign/EVP_DigestVerify?

**Comment by concatime** [comment]
If anything on the radar, just let me know :)

**Comment by orbea** [comment]
I just want to point out that m2crypto is affected by this issue since the following commit.

https://gitlab.com/m2crypto/m2crypto/-/commit/65997b1761b3ccbaef84cbc4ffc24585717e8b02

**Comment by kinichiro** [comment]
https://github.com/openbsd/src/commit/767bfe2989cb5bb831736fd5190c6ddc201753d6 committed.

**Comment by kinichiro** [comment]
@nicraMarcin I think this issue is fixed with latest LibreSSL 3.4.1.
Can you close this ?

**Comment by orbea** [comment]
With 3.4.2 and at least in the case of m2crypto this is fixed for me too (m2crypto still requires some of the unrelated OpenBSD patches).
