### ISSUE TITLE
Error in motion correction?

### ISSUE THREAD

**Issue by the-rare-jm** [libressl-portable/portable#640]
Dear Team,
    I'm using Relion 3.1.1 for processing the tutorial data set of BGal(EMPIAR-10204). When I'm running the given parameters for motion correction it shows this (metioned below) and the job is getting failed.

Correcting beam-induced motions using our own implementation ...
000/??? sec ~~(,_,">                                                          [oo]
RELION version: 3.1.1-commit-e0b939
exiting with an error ...

Please suggest what should be done and where it went wrong.
Thanks much in advance.

**Comment by 4a6f656c** [comment]
This does not appear to be related to LibreSSL - I suspect you've got the wrong project :)
