### ISSUE TITLE
Versions 3.1.0 and older no longer build

### ISSUE THREAD

**Issue by Benjamin-L** [libressl-portable/portable#643]
Due to a change in the upstream OpenBSD source, all versions of libressl-portable older than 3.1.1 no longer build correctly:

```
$ git checkout v3.1.0
$ ./autogen.sh
pulling upstream openbsd source
Already on 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
libcrypto version 46:1:0
libssl version 48:1:0
libtls version 20:1:0
cp: cannot stat '/home/benjamin/git/libressl-portable/openbsd/src/lib/libcrypto/x509v3/x509v3.h':
No such file or directory
```

**Comment by busterb** [comment]
Use the tarballs from ttps://cdn.openbsd.org/pub/OpenBSD/LibreSSL/

If you really want to reproduce the tarball contents from git, do this to ensure the correct tag is also chosen on the openbsd git repo:

```
echo "libressl-3.1.0" > OPENBSD_BRANCH
sed -i 's/git pull --rebase//' update.sh
```
the proceed as normal with autogen.sh

There's a tool called 'check-release.sh' that should automate some of this, but you might need to modify it a bit. The tarballs are really preferred if you want historical releases.
