### ISSUE TITLE
Static Compilation to run on Android

### ISSUE THREAD

**Issue by pedroalbanese** [libressl-portable/portable#645]
Hello, how to compile static to run on Android? I'm trying but the "-static" tag doesn't work. I can't use "-lssp" either, it's not found.

How to proceed?

Thanks in advance.

**Comment by kinichiro** [comment]
I'm not sure how you are building, though,
You can refer [.travis.yml](https://github.com/libressl-portable/portable/blob/master/.travis.yml) and [scripts/travis](https://github.com/libressl-portable/portable/blob/master/scripts/travis) to know how to build LibreSSL for Android.
And you can use `BUILD_SHARED_LIBS` option to enable or disable building shared libraries.
This option is default to OFF as described in [README.md](https://github.com/libressl-portable/portable/blob/master/README.md).
I think if you are running cmake without option BUILD_SHARED_LIBS, libraries would be built as static.
I hope this help.

**Comment by pedroalbanese** [comment]
I'm on Debian amd64 (Kali)

I'm compiling:
CC=arm-linux-gnueabi-gcc CPPFLAGS="-D_FORTIFY_SOURCE=0" CFLAGS="-static -s -Wl,-Bstatic" ./configure --host=arm-linux-gnueabi --with-openssldir="/sdcard/libressl/ssl/"
make

It compiles, and runs on Linux Deploy Kali armel, but does not run on the Android terminal. I can compile programs for Android like this, but the binaries must be static, otherwise it won't run.

How do I use the BUILD_SHARED_LIBS parameter? How would that same command look, with this parameter?

Thanks.

**Comment by pedroalbanese** [comment]
tried this, but it results in several errors:

cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc

make CC=arm-linux-gnueabi-gcc CFLAGS="-s -static -march=armv6"

How to do cross-compilation?

**Comment by pedroalbanese** [comment]
root@cce:/tmp/libressl-3.2.0/apps/openssl# echo "  CCLD    " openssl;/bin/bash ../../libtool --silent --tag=CC   --mode=link arm-linux-gnueabi-gcc  -static -s -Wall -std=gnu99 -fno-strict-aliasing  -fno-strict-overflow -fstack-protector-strong   -Wno-pointer-sign  -Wl,-z,relro -Wl,-z,now  -o openssl apps.o asn1pars.o ca.o ciphers.o crl.o crl2p7.o cms.o dgst.o dh.o dhparam.o dsa.o dsaparam.o ec.o ecparam.o enc.o errstr.o gendh.o gendsa.o genpkey.o genrsa.o nseq.o ocsp.o openssl.o passwd.o pkcs12.o pkcs7.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o prime.o rand.o req.o rsa.o rsautl.o s_cb.o s_client.o s_server.o s_socket.o s_time.o sess_id.o smime.o speed.o spkac.o ts.o verify.o version.o x509.o certhash.o   apps_posix.o   compat/strtonum.o /tmp/libressl-3.2.0/ssl/libssl.la /tmp/libressl-3.2.0/crypto/libcrypto.la   -lresolv -lpthread -s -static -static-libgcc -Wl,-Bdynamic,-lgcc_s,-Bstatic
  CCLD     openssl
/usr/lib/gcc-cross/arm-linux-gnueabi/10/../../../../arm-linux-gnueabi/bin/ld: s_socket.o: in function `init_client':
s_socket.c:(.text+0x60): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc-cross/arm-linux-gnueabi/10/../../../../arm-linux-gnueabi/bin/ld: s_socket.o: in function `do_accept':
s_socket.c:(.text+0x6bc): warning: Using 'gethostbyaddr' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc-cross/arm-linux-gnueabi/10/../../../../arm-linux-gnueabi/bin/ld: s_socket.c:(.text+0x75c): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc-cross/arm-linux-gnueabi/10/../../../../arm-linux-gnueabi/bin/ld: s_socket.o: in function `extract_port':
s_socket.c:(.text+0x9e0): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
root@cce:/tmp/libressl-3.2.0/apps/openssl#

**Comment by pedroalbanese** [comment]
I managed to compile with the command:

cmake -G "Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCMAKE_C_FLAGS="-static -s"

But it works the hash function, but it does not encrypt. I get the error "Killed" when I use the enc command. What is wrong?

**Comment by kinichiro** [comment]
I'm using Ubuntu 14.04 and cmake 3.6.3, ninja 1.3.4.
I unzipped Android NDK under the /usr/local.
And I did like below, as [scripts/travis](https://github.com/libressl-portable/portable/blob/master/scripts/travis#L147) does.

```
$ export ANDROID_NDK_HOME=/usr/local/android-ndk-r21b
$ export TC_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
$
$ cmake -GNinja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja \
  -DANDROID_NDK=$ANDROID_NDK_HOME -DCMAKE_TOOLCHAIN_FILE=$TC_FILE \
  -DANDROID_ABI=x86_64 -DANDROID_NATIVE_API_LEVEL=29 ..
$
$ /usr/bin/ninja
```

To build static libraries, -DBUILD_STATIC_LIBS=off is not required here since it is the default.

With this procedure above, I could build static.
I don't have running environment for Android, I didn't execute testing, though.


>I get just the message "Killed" when I use the enc command. What is wrong?

I think it should need more information to solve that issue.
Like, running environment, executed commands, debugging trace, etc.

**Comment by pedroalbanese** [comment]
Could you please compile an armv6-compatible static binary for me? I really need this .. I don't have the necessary knowledge but I need the program urgently ..

**Comment by kinichiro** [comment]
> Could you please compile an armv6-compatible static binary for me?

It appears that Android NDK supports armeabi-v7a and arm64-v8a only for ARM ABI.
So, I don't think you can specify -DANDROID_ABI=arm-v6 or like that.
https://developer.android.com/ndk/guides/abis?hl=en

**Comment by kinichiro** [comment]
@pedroalbanese Is your issue solved ? Can you close this ?

**Comment by pedroalbanese** [comment]
Sorry, I didn't make it., I cannot solve the problem. I had to write a tool (More archaic and modest ) so that could support Kuznechik and Streebog on Android.
https://github.com/pedroalbanese/gosttk

Thanks.

**Comment by pedroalbanese** [comment]
As I compile golang codes with:
CC=arm-linux-gnueabi-cc GOOS=linux GOARCH=arm GOARM=6 go build -ldflags=-s . 
I compile C codes with:
make CC=arm-linux-gnueabi-gcc CFLAGS="-s -static -march=armv6"

My smartphone is armel.. It works fine. Thank you once again.
