### ISSUE TITLE
32-bit Windows DLL has a dependency on libgcc's math libraries

### ISSUE THREAD

**Issue by busterb** [libressl-portable/portable#65]
Thanks to Stefan Kowski for reporting. We should either bundle the dll or eliminate the dependency if possible.

![libcrypto-dep](https://cloud.githubusercontent.com/assets/4108654/6527692/593d74f4-c3e2-11e4-8ed0-3e9766f02eaf.PNG)

**Comment by jonathangray** [comment]
Would using -static-libgcc solve this?

**Comment by busterb** [comment]
Yep, works like a charm. Thanks.

**Comment by busterb** [comment]
fixed in 031f0aaa8f9b2e907195dbda8b7c451a08d58bbb
