### ISSUE TITLE
hcxtools fails to build with libressl (missing EVP_PKEY_new_CMAC_key)

### ISSUE THREAD

**Issue by buzzdeee** [libressl-portable/portable#651]
tried to build latest release of hcxtools fails because of missing function: 

EVP_PKEY *EVP_PKEY_new_CMAC_key(ENGINE *e, const unsigned char *priv,
                                 size_t len, const EVP_CIPHER *cipher);

the maintainer switched to openssl 1.1 API, see: https://github.com/ZerBea/hcxtools/issues/184

**Comment by kinichiro** [comment]
committed in upstream https://github.com/openbsd/src/commit/01f300463a9cfc0059aabe3087edb65e8ae07e40

**Comment by 4a6f656c** [comment]
This function is available in the current development release and will be in the following stable release.
