### ISSUE TITLE
Conversion of SSH Ed25519 private key associated to a passphrase into PEM format

### ISSUE THREAD

**Issue by Ricky-Tigg** [libressl-portable/portable#661]
Hello. Might [issue](https://bugzilla.mindrot.org/show_bug.cgi?id=3298) be tied to LibreSSL?

**Comment by botovq** [comment]
Hi. Yes. Your bug was marked as a duplicate of bug
https://bugzilla.mindrot.org/show_bug.cgi?id=3195 which explains that it
is indeed due to lack of LibreSSL support for Ed25519. This is something
that will come eventually but not immediately.

**Comment by Ricky-Tigg** [comment]
That's now an official statement. Is is to early to presume the lack of sntrup4591761x25519-sha512@tinyssh.org which TinySSH brought and OpenSSH has supported?

**Comment by Ricky-Tigg** [comment]
That's now an official statement. Is it too early to presume the lack of sntrup4591761x25519-sha512@tinyssh.org which TinySSH brought and OpenSSH has supported?

**Comment by Ricky-Tigg** [comment]
As a duplicate of the one reported on Mozilla's platform and expecting that it may take over eight years if ever, to attest an operational support, there is no need to keep the present ticket open.
