### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_tls12_key_block_client_write", referenced from:  _tls1_change_cipher_state in lto.o

### ISSUE THREAD

**Issue by vollkommenheit** [libressl-portable/portable#666]
It seems as a result of https://github.com/libressl-portable/portable/commit/28e428e6843583a6cef9d6ff2b90a59a953ccefa, now on macOS I get:
> make[2]: Nothing to be done for `all-am'.
Making all in ssl
  CCLD     libssl.la
undef: _tls12_key_block_client_write
undef: _tls12_key_block_server_write
undef: _tls12_key_block_new
undef: _tls12_key_block_generate
undef: _tls12_key_block_free
Undefined symbols for architecture x86_64:
  "_tls12_key_block_client_write", referenced from:
      _tls1_change_cipher_state in lto.o
  "_tls12_key_block_server_write", referenced from:
      _tls1_change_cipher_state in lto.o
  "_tls12_key_block_new", referenced from:
      _tls1_setup_key_block in lto.o
  "_tls12_key_block_generate", referenced from:
      _tls1_setup_key_block in lto.o
  "_tls12_key_block_free", referenced from:
      _ssl3_free in lto.o
      _ssl3_clear in lto.o
      _ssl3_connect in lto.o
      _ssl3_accept in lto.o
      _tls1_setup_key_block in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libssl.la] Error 1
make: *** [all-recursive] Error 1

**Comment by busterb** [comment]
Mind giving some more info? It seemed to work fine in CI: https://travis-ci.org/github/libressl-portable/portable/jobs/770897359

**Comment by vollkommenheit** [comment]
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

clang --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix

ld -v
@(#)PROGRAM:ld  PROJECT:ld64-274.2
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 8.0.0, (clang-800.0.42.1)
TAPI support using: Apple TAPI version 1.30

autoconf --version
autoconf (GNU Autoconf) 2.69

**Comment by vollkommenheit** [comment]
Builds fine today.
