### ISSUE TITLE
patch error in update.sh

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#68]
Hi,

I noticed that patch error occurs in current HEAD.

    ...
    copying openssl(1) source
    can't find file to patch at input line 5
    Perhaps you used the wrong -p or --strip option?
    The text leading up to this was:
    --------------------------
    |diff --git a/src/usr.bin/openssl/openssl.c b/src/usr.bin/openssl/openssl.c
    |index e7dd11c..cfd4593 100644
    |--- a/src/usr.bin/openssl/openssl.c
    |+++ b/src/usr.bin/openssl/openssl.c
    --------------------------
    File to patch:

It seems that update.sh should execute `patch -p4` not `patch -p5`.

    (cd apps; patch -p5 < $CWD/patches/win_bio_sock_init.diff)

After changing `-p5` to `-p4`, it runs through good like this.

    ...
    copying openssl(1) source
    patching file openssl.c
    patching file s_socket.c
    copying libssl source
    ...

Thanks.

**Comment by busterb** [comment]
thanks - the OpenBSD patch command appears to be more permissive - both worked!

**Comment by kinichiro** [comment]
Oh, I see.
I encountered this on CentOS 6.5.
Thanks.
