### ISSUE TITLE
LibreSSL3.3.2 with Puppet CA/CRT

### ISSUE THREAD

**Issue by qhess34** [libressl-portable/portable#684]
LibreSSL is unable to verify a Puppet certificate while OpenSSL does
i get the error : 53:unsupported or invalid name syntax

        System      : OpenBSD 6.9
        Details     : OpenBSD 6.9 (GENERIC.MP) #473: Mon Apr 19 10:40:28 MDT 2021
                         deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP

        Architecture: OpenBSD.amd64
        Machine     : amd64

I get in trouble when I try to verify the PuppetMaster (7.5) certificate with the Puppet CA (generated with OpenSSL 1.1.1d) with Libre SSL 3.3.2

        
        With OpenSSL :
        openbsd6# openssl version
        OpenSSL 1.0.2u  20 Dec 2019

        openbsd6# openssl s_client -CAfile /etc/puppetlabs/puppet/ssl/certs/ca.pem -connect mypuppetmaster.example.com:8140 -showcerts
        CONNECTED(00000003)
        depth=1 CN = Puppet CA: mypuppetmaster.example.com
        verify return:1
        depth=0 CN = mypuppetmaster.example.com
        verify return:1
        ---

        With LibreSSL (renamed for debug):
        openbsd6# libressl version
        LibreSSL 3.3.2
        openbsd6# libressl  s_client -CAfile /etc/puppetlabs/puppet/ssl/certs/ca.pem -connect mypuppetmaster.example.com:8140 -showcerts
        CONNECTED(00000003)
        depth=1 CN = Puppet CA: mypuppetmaster.example.com
        verify error:num=53:unsupported or invalid name syntax
        verify return:0
        write W BLOCK
        ---

**Comment by bob-beck** [comment]
On Fri, Sep 03, 2021 at 09:25:33AM -0700, qhess34 wrote:
> LibreSSL is unable to verify a Puppet certificate while OpenSSL does
> i get the error : 53:unsupported or invalid name syntax
> 
>         System      : OpenBSD 6.9
>         Details     : OpenBSD 6.9 (GENERIC.MP) #473: Mon Apr 19 10:40:28 MDT 2021
>                          ***@***.***:/usr/src/sys/arch/amd64/compile/GENERIC.MP
> 
>         Architecture: OpenBSD.amd64
>         Machine     : amd64
> 
> I get in trouble when I try to verify the PuppetMaster (7.5) certificate with the Puppet CA (generated with OpenSSL 1.1.1d) with Libre SSL 3.3.2
> 
>         
>         With OpenSSL :
>         openbsd6# openssl version
>         OpenSSL 1.0.2u  20 Dec 2019
> 
>         openbsd6# openssl s_client -CAfile /etc/puppetlabs/puppet/ssl/certs/ca.pem -connect mypuppetmaster.example.com:8140 -showcerts
>         CONNECTED(00000003)
>         depth=1 CN = Puppet CA: mypuppetmaster.example.com
>         verify return:1
>         depth=0 CN = mypuppetmaster.example.com
>         verify return:1
>         ---
> 
>         With LibreSSL (renamed for debug):
>         openbsd6# libressl version
>         LibreSSL 3.3.2
>         openbsd6# libressl  s_client -CAfile /etc/puppetlabs/puppet/ssl/certs/ca.pem -connect mypuppetmaster.example.com:8140 -showcerts
>         CONNECTED(00000003)
>         depth=1 CN = Puppet CA: mypuppetmaster.example.com
>         verify error:num=53:unsupported or invalid name syntax
>         verify return:0
>         write W BLOCK
>         ---
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/libressl-portable/portable/issues/684

Can you send the certificate that fails?

**Comment by bob-beck** [comment]
On Fri, Sep 03, 2021 at 09:25:33AM -0700, qhess34 wrote:
> LibreSSL is unable to verify a Puppet certificate while OpenSSL does
> i get the error : 53:unsupported or invalid name syntax
> 
>         System      : OpenBSD 6.9
>         Details     : OpenBSD 6.9 (GENERIC.MP) #473: Mon Apr 19 10:40:28 MDT 2021
>                          ***@***.***:/usr/src/sys/arch/amd64/compile/GENERIC.MP
> 
>         Architecture: OpenBSD.amd64
>         Machine     : amd64
> 
> I get in trouble when I try to verify the PuppetMaster (7.5) certificate with the Puppet CA (generated with OpenSSL 1.1.1d) with Libre SSL 3.3.2
> 
>         
>         With OpenSSL :
>         openbsd6# openssl version
>         OpenSSL 1.0.2u  20 Dec 2019
> 
>         openbsd6# openssl s_client -CAfile /etc/puppetlabs/puppet/ssl/certs/ca.pem -connect mypuppetmaster.example.com:8140 -showcerts
>         CONNECTED(00000003)
>         depth=1 CN = Puppet CA: mypuppetmaster.example.com
>         verify return:1
>         depth=0 CN = mypuppetmaster.example.com
>         verify return:1
>         ---
> 
>         With LibreSSL (renamed for debug):
>         openbsd6# libressl version
>         LibreSSL 3.3.2
>         openbsd6# libressl  s_client -CAfile /etc/puppetlabs/puppet/ssl/certs/ca.pem -connect mypuppetmaster.example.com:8140 -showcerts
>         CONNECTED(00000003)
>         depth=1 CN = Puppet CA: mypuppetmaster.example.com
>         verify error:num=53:unsupported or invalid name syntax
>         verify return:0
>         write W BLOCK
>         ---
> 

And to be clear, I don't need your private keys, the public portions of
the cert and ca should be fine if you can.

**Comment by qhess34** [comment]
Hello,

Sorry for the delay. 
Here are the 2 files : 
[debian10.localdomain.pem.gz](https://github.com/libressl-portable/portable/files/7114106/debian10.localdomain.pem.gz)
[ca.pem.gz](https://github.com/libressl-portable/portable/files/7114107/ca.pem.gz)

Thanks

**Comment by 4a6f656c** [comment]
I believe this has been addressed in Puppet - additionally, code was added to prevent such certificates from being created with LibreSSL.
