### ISSUE TITLE
[support inquiry] Changelog with release dates?

### ISSUE THREAD

**Issue by prof-milki** [libressl-portable/portable#69]
Hi,

For the release tracking on http://freshcode.club/projects/libressl I've been using the Changelog directly from GitHub.
But I've just been tipped that this isn't representative of the official releases :/
(2.1.5 is just a prerelease according to /releases, and appeared too early.)

Now the LibreSSL Changelog is obviously/dutily kept updated for current development progress, not just for releases. Which is why it's less suitable for automatic release polling.

So, is there an alternative resource for release announcements perhaps? (Not the mailing list; something discoverable/parseable of course).

Thanks!

**Comment by busterb** [comment]
Oops, sorry about that! Yes, this is a development tree, so it can easily be ahead of the next release. The next release will actually be cut from a different branch even.

The simplest thing to do would be to backdate the Changelog file with the release dates and copy it to the mirrors, like OpenSSH does. Does that sound reasonable to you? The mirror copy would only be updated on release.

**Comment by prof-milki** [comment]
Yeah, that would be great. If there's a static copy somewhere, and published with final releases, that would work just as well.

As another option I could possibly also regex the official version number off /www.libressl.org/ and lookup a tagged URL (http://example.org/libressl/log.$version$.txt etc).

**Comment by busterb** [comment]
Your last idea is the best of all, since it matches openntpd / openssl. Will do.

**Comment by prof-milki** [comment]
Hey, this works great, and is pretty easy to extract now.
Just using a regex/Selenium-style recipe:

    version = http://www.libressl.org/
    version = /stable release is (\d[\d.]+\d)/
    changes = http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$version-relnotes.txt
    changes = /\R\R(.+)/smix
    scope = /(minor|major|bugfix|cleanup|documentation)/i*

Thanks again for the effort!
