### ISSUE TITLE
Partial support for the Sortix operating system

### ISSUE THREAD

**Issue by sortie** [libressl-portable/portable#690]
My custom Sortix operating system has been successfully shipping LibreSSL since 2014 and I just updated it to the latest development release libressl-3.4.0. Sortix abides by POSIX and doesn't provide some non-standard things in system headers whenever standardized alternatives are available. As such, LibreSSL needs a few minor patches to compile for Sortix.

I also have a few minor patches to work around some deficiencies in Sortix that I'll fix in the future, but those should of course not be upstreamed, as I'll just patch those locally.

I sent a pull request with the parts that applies cleanly to libressl-portable in https://github.com/libressl-portable/portable/pull/689.  This issue is about the other patches that apply to the parts imported from OpenBSD, and honestly the scope ranges from here to talking to tech@. I'm hoping you can have a quick look at these trivial changes and just make them the right place, as it takes a bunch of time for me to figure out exactly how to contribute these changes (and I have a *lot* of small patches to upstream to a lot of projects).

Please see my patches to my port of libressl: https://pub.sortix.org/sortix/release/nightly/patches/libssl.patch

Not all of these patches should be merged, here's my extended commentary on the parts that are relevant and not handled in #689:

* `base64.c` uses the non-standard `u_char` instead of `unsigned char`. The cleanest place to change this is probably in upstream OpenBSD. Alternatively you could provide this type yourself in the compat.
* `apps/nc/netcat.c` uses `<arpa/telnet.h>` which I don't have yet. The functionality is optional though. You could add a compat header with the couple constants that are used. I suppose the right course of action is just for me to provide it.
* `apps/nc/netcat.c` uses `mktemp(3)` to make a Unix socket which was removed in POSIX-2008 as it leads to an insecure pattern. Though, the code here is a correct use of it with the higher level retry loop. My patch makes a `mkstemp(3)` solution instead that deletes the temporarily created file. You could switch to that.
* `apps/nc/netcat.c` uses various IP options that aren't in POSIX and that I don't implement yet. These are non-essential for the program and could be appropriately ifdef'd on your side since they are not POSIX. I'll likely add those in the future and I'm fine owning this patch myself if you don't want it on your side.
* Sortix doesn't have `PATH_MAX` which is allowed by POSIX. Nonetheless it created a lot of problems, so I'll add it in the future. It created a little bit of trouble with the `readlink` logic here. I suppose the truncation check is a good idea on your end though.
* Sortix doesn't have the POSIX obsolete and non-IPv6 capable `gethostbyname` APIs and uses the `getaddrinfo` APIs instead.
* `crypto/chacha/chacha-merged.c` uses the non-standard `u_int` instead of `unsigned int`. The cleanest place to change this is probably in upstream OpenBSD. Alternatively you could provide this type yourself in the compat.
* `tests/handshake_table.c` uses `__dead` instead of the standard `noreturn` from `stdnoreturn.h` in C11. The cleanest place to change this is probably in upstream OpenBSD (and perhaps add compat for non-C11 systems if you support those). Alternatively you could provide a fallback `__dead` for systems without it in the compat.
* `tests/ssltest.c` includes the non-standard `sys/param.h` and the inclusion isn't needed.
* `tls/tls_config.c` doesn't handle that `uid_t` can be bigger than 32-bit per POSIX. E.g. Sortix has 64-bit `uid_t`. Additionally the type is unsigned, not signed. I changed it to format it using `unsigned long long` although I suppose `uintmax_t` and `%ju` is the right solution since the type could be any size, not that it actually matters.

Thank you for LibreSSL. I very much enjoy your portability approach and it's a nice port compared to the OpenSSLport  I had before I switched to LibreSSL in 2014. It's completely infeasible for me to scale to properly upstream all the many portability issues I find my ports, so I really hope you'll work with me here and fix the things you feel make sense on your end. I don't want any upstream Sortix-specific hacks as I'll maintain those locally and remove them in due time. Hopefully in the near future, LibreSSL will compile out of the box on Sortix as a supported system, but these patches gets it very close to that point and I'll do the rest.

**Comment by 4a6f656c** [comment]
We've landed most of these changes upstream - if you need further assistance please feel free to raise a new issue.
