### ISSUE TITLE
support HTTP proxies when doing OCSP queries

### ISSUE THREAD

**Issue by busterb** [libressl-portable/portable#70]
The current HTTP client in the OCSP code is very simple, and breaks if there is an HTTP proxy. It might be useful to fix it, or to use a more robust HTTP client library (if it is available) to implement the 'openssl ocsp' command.

**Comment by bob-beck** [comment]
This I believe had to do with dealing with the extra certificates in for the OCSP queries, and
I believe should now be fixed.

**Comment by bob-beck** [comment]
Aha. no this is the "openssl ocsp" command being able to understand proxy requests. 
I'm thinking we don't want to "fix" this command for a more robust library, were we to 
do this, I think we would rather make a completely different utility to make OCSP client requests.
