### ISSUE TITLE
 regression in 3.4.X (found by haproxy testing)

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#711]
in haproxy we use both OpenSSL and LibreSSL, when I update LibreSSL to 3.4.2, some tests fail.
cert revocation were resolved in https://github.com/libressl-portable/portable/issues/697
however one failure [still remains](https://github.com/chipitsine/haproxy/runs/4496790988?check_suite_focus=true) (not related to cert revocation)

steps to reproduce (test [reg-tests/ssl/ssl_client_samples.vtc](https://github.com/haproxy/haproxy/blob/master/reg-tests/ssl/ssl_client_samples.vtc)):

```
git clone https://github.com/haproxy/haproxy
cd haproxy
LIBRESSL_VERSION=3.4.2 ./scripts/build-ssl.sh
make CC=gcc TARGET=linux-glibc USE_OPENSSL=1 ADDLIB="-Wl,-rpath,${HOME}/opt/lib" SSL_LIB=${HOME}/opt/lib SSL_INC=${HOME}/opt/include
./scripts/build-vtest.sh
make reg-tests VTEST_PROGRAM=../vtest/vtest -- --debug reg-tests/ssl/ssl_client_samples.vtc
```

what I've found so far:

LibreSSL-3.3.4 = test passed
LibreSSL-3.4.0 = test failed
LibreSSL-3.4.1 = test failed
LibreSSL-3.4.2 = test failed
LibreSSL-master = test failed

exection fails in  https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L6483-L6498
which in turn is executed from some callback: https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L7418

if I reduce headers size passed in `reg-tests/ssl/ssl_client_samples.vtc` test is passed:

```
    listen ssl-lst
        mode http

        http-response add-header x-ssl-der %[ssl_c_der,hex]
        http-response add-header x-ssl-chain-der %[ssl_c_chain_der,hex]
        http-response add-header x-ssl-notafter %[ssl_c_notafter]
        http-response add-header x-ssl-notbefore %[ssl_c_notbefore]
        http-response add-header x-ssl-sig_alg %[ssl_c_sig_alg]
        http-response add-header x-ssl-i_dn %[ssl_c_i_dn]
        http-response add-header x-ssl rsaE
        #http-response add-header x-ssl-key_alg rsaEncryption

        bind "${tmpdir}/ssl.sock" ssl crt ${testdir}/common.pem ca-file ${testdir}/ca-auth.crt verify optional crt-ignore-err all crl-file ${testdir}/crl-auth.pem

        server s1 ${s1_addr}:${s1_port}
} -start

```

**Comment by chipitsine** [comment]
I've found OpenBSD [images](https://ftp.hostserver.de/archive/2021-10-17-0105/snapshots/amd64/)

openbsd-install70-2021-09-14 = test failed
openbsd-install70-2021-09-06 = test passed

I'll check source diff soon

**Comment by 4a6f656c** [comment]
This one is a strange one that's proving difficult to track down.

There are a few factors at play here, the main one being that it is triggered by client certificate authentication and TLSv1.3 - adding `force-tlsv12` to the `bind` statement for `ssl-lst` makes it pass. Likewise, using TLSv1.3 but removing the `crt` from the `server` statement in `clear-lst` also makes the connection work (but we get empty `x-ssl-*` headers - as expected).

However, if I run a haproxy with this configuration but bind on a TCP listener, I can connect using the same certificate with `nc -cv -T noverify -T noname -C ./haproxy/reg-tests/ssl/client1.pem -K ./haproxy/reg-tests/ssl/client1.pem 127.0.0.1 8443` and it works correctly.

Unfortunately, haproxy does not seem to provide any details regarding why it is failing, beyond:

```
<134>Dec 20 17:23:41 haproxy[94945]: 127.0.0.1:43617 [20/Dec/2021:17:23:41.227] clear-lst clear-lst/s1 0/0/44/-1/+48 502 +209 - - PH-- 2/1/0/0/0 0/0 "GET / HTTP/1.1"
```

Which, as I understand it, is saying it failed during proxy header validation.

We're probably seeing a subtle difference in callback behavior or similar due to the new TLS stack - any suggestions on figuring out exactly what haproxy is failing on (even being able to tell if this is the TLS client or TLS server would help)?

**Comment by chipitsine** [comment]
I've added the following patch

```diff
diff --git a/src/ssl_sock.c b/src/ssl_sock.c
index 158cb48ff..33c5d479b 100644
--- a/src/ssl_sock.c
+++ b/src/ssl_sock.c
@@ -1609,6 +1609,7 @@ int ssl_sock_bind_verifycbk(int ok, X509_STORE_CTX *x_store)
 		}
 
 		if (err < 64 && __objt_listener(conn->target)->bind_conf->ca_ignerr & (1ULL << err)) {
+			fprintf(stderr, "point 1\n");
 			ssl_sock_dump_errors(conn);
 			ERR_clear_error();
 			return 1;
@@ -1623,6 +1624,7 @@ int ssl_sock_bind_verifycbk(int ok, X509_STORE_CTX *x_store)
 
 	/* check if certificate error needs to be ignored */
 	if (err < 64 && __objt_listener(conn->target)->bind_conf->crt_ignerr & (1ULL << err)) {
+		fprintf(stderr, "point 2\n");
 		ssl_sock_dump_errors(conn);
 		ERR_clear_error();
 		return 1;
@@ -5873,6 +5875,7 @@ static int ssl_sock_handshake(struct connection *conn, unsigned int flag)
 
  out_error:
 	/* Clear openssl global errors stack */
+	fprintf(stderr, "point 3\n");
 	ssl_sock_dump_errors(conn);
 	ERR_clear_error();
 
@@ -6238,6 +6241,7 @@ static size_t ssl_sock_to_buf(struct connection *conn, void *xprt_ctx, struct bu
 
  clear_ssl_error:
 	/* Clear openssl global errors stack */
+	fprintf(stderr, "point 4\n");
 	ssl_sock_dump_errors(conn);
 	ERR_clear_error();
  read0:
@@ -6247,6 +6251,7 @@ static size_t ssl_sock_to_buf(struct connection *conn, void *xprt_ctx, struct bu
  out_error:
 	conn->flags |= CO_FL_ERROR;
 	/* Clear openssl global errors stack */
+	fprintf(stderr, "point 5\n");
 	ssl_sock_dump_errors(conn);
 	ERR_clear_error();
 	goto leave;
@@ -6399,6 +6404,7 @@ static size_t ssl_sock_from_buf(struct connection *conn, void *xprt_ctx, const s
 
  out_error:
 	/* Clear openssl global errors stack */
+	fprintf(stderr, "point 6\n");
 	ssl_sock_dump_errors(conn);
 	ERR_clear_error();
 
@@ -6483,6 +6489,7 @@ void ssl_sock_close(struct connection *conn, void *xprt_ctx) {
 static void ssl_sock_shutw(struct connection *conn, void *xprt_ctx, int clean)
 {
 	struct ssl_sock_ctx *ctx = xprt_ctx;
+	int ret;
 
 	if (conn->flags & (CO_FL_WAIT_XPRT | CO_FL_SSL_WAIT_HS))
 		return;
@@ -6490,8 +6497,12 @@ static void ssl_sock_shutw(struct connection *conn, void *xprt_ctx, int clean)
 		/* don't sent notify on SSL_shutdown */
 		SSL_set_quiet_shutdown(ctx->ssl, 1);
 	/* no handshake was in progress, try a clean ssl shutdown */
-	if (SSL_shutdown(ctx->ssl) <= 0) {
+	ret =  SSL_shutdown(ctx->ssl);
+	if (ret <= 0) {
+
+		fprintf(stderr, "point SSL_get_error = %d\n", SSL_get_error(ctx->ssl, ret));
 		/* Clear openssl global errors stack */
+		fprintf(stderr, "point 7\n");
 		ssl_sock_dump_errors(conn);
 		ERR_clear_error();
 	}

```

it helped a little bit

**Comment by 4a6f656c** [comment]
So working backwards from the `PH` in the failing log line:

```
<134>Dec 21 16:15:26 haproxy[50215]: 127.0.0.1:15088 [21/Dec/2021:16:15:26.749] clear-lst clear-lst/s1 0/0/42/-1/+45 502 +209 - - PH-- 2/1/0/0/0 0/0 "GET / HTTP/1.1"
```

I managed to add debugging for all of the `SF_FINST_H` cases and eventually tracked it back to the header size check in `h1_postparse_res_hdrs()`:

  https://github.com/haproxy/haproxy/blob/master/src/h1_htx.c#L276

Adding the following config makes it work:

```
global:
    tune.bufsize 65536
    tune.maxrewrite 32768
```

(as an aside, it seems less than ideal that it took multiple hours and 30+ debug statements to track this down)

I'm still investigating, but it seems that with TLSv1.3 `SSL_get_peer_cert_chain()` is returning the leaf certificate with the chain (this is correct for a client, but not for a server), which is pushing things over the default limit.

**Comment by 4a6f656c** [comment]
A fix for this landed in https://github.com/openbsd/src/commit/a1543fdeacfc5931a678090a5173b5e20d110ea4.

Thanks for the report.

**Comment by chipitsine** [comment]
Will new 3.4.x be released?
