### ISSUE TITLE
TLS 1.3 server side support & TLS 1.3 resumption support?

### ISSUE THREAD

**Issue by trippleflux** [libressl-portable/portable#719]
Is there any news regarding TLS 1.3 server side & TLS 1.3 resumption support?, when it's gonna happen?

**Comment by 4a6f656c** [comment]
The TLSv1.3 server side code was enabled in LibreSSL 3.2.0/3.2.2 (October 2020), although some things would not enable TLSv1.3 until the OpenSSL 1.1.1 TLSv1.3 APIs existed - they appeared in 3.4.0/3.4.1 (October 2021).

As for TLSv1.3 tickets, it will likely happen but there is currently no specific timeline.
