### ISSUE TITLE
Expired DNS Entires with LibreSSL 

### ISSUE THREAD

**Issue by kapeterson** [libressl-portable/portable#725]
We are experiencing an intermittent issue when using LibreSSL with OpenSSH on MacOS ( Multiple Versions Big Sur, Monterrey).

With LibreSSL, TTL expired DNS entries are used by the application when creating the session.  Looking at pcap files, we see:

1. DNS Query sent for the name.
2. TCP Connection Opened SYN
3. DNS Response Received
3. SYN-ACK Received
4. No Final SYN received and application error.
     - kex_exchange_identification: write: Protocol wrong type for socket

If we build the application (openssh) with OpenSSL instead of LibreSSL, the DNS behavior changes - the TCP connection is not attempted until a DNS query and response is received, and we cannot reproduce the issue.

I understand that LibreSSL uses LDNS so I'm curious if the DNS behavior behavior can be changed or if there's a way to dig deeper into the root cause here.

**Comment by busterb** [comment]
I'm not sure what you mean by 'LibreSSL uses LDNS'. It doesn't use any external DNS library, only the system resolver where applicable. What application are you building here, can we see it? Also, are you using the LibreSSL 2.8.3 that Apple ships with Monterrey, or the newer version that Homebrew or other packages ship?

**Comment by busterb** [comment]
Just for clarification, the effect you're seeing is in doing `ssh hostname`, where it's connecting to the wrong cached IP? I wonder if it's related to https://github.com/libressl-portable/portable/issues/631 but OpenSSH I don't believe uses any networking code from LibreSSL. It only links libcrypto, not libssl. It sounds also like the misbehaving versions of OpenSSH are the ones shipped by Apple with the macOS? I wonder if there are any local patches Apple is applying that affect this behavior as well. https://github.com/apple-oss-distributions/OpenSSH/tree/OpenSSH-240.40.1

**Comment by kapeterson** [comment]
The IP used is correct.   The client gets the IP from the cache and opens connection to a proper IP address.   There is a DNS response during the TCP establishment.  Not 100% sure it's related to DNS but it does not happen when an expired entry is used.

It can be avoided with expiredDNSBehavior of prohibit - this is the behavior when built with OpenSSL.  The behavior is allow when build with the LibreSSL version.

 https://developer.apple.com/documentation/network/nwparameters/3003635-expireddnsbehavior


Tha

Seems like the error is happening here and in this case the `our_version` is not showing the proper length.  **_Perhaps it should be brought up with the openssh team_** but I think a "workaround" would be changing the expiredDNSBehavior?

https://github.com/apple-oss-distributions/OpenSSH/blob/cde919fd5d3fc8bb2ca9709a9ece99737523ec22/openssh/kex.c#L1189


Successful dtruss

```
0x555d3:  write(0x2, "OpenSSH_8.1p1, LibreSSL 2.7.3\r\n\0", 0x1F)		 = 31 0
0x555d3:  write(0x6, "SSH-2.0-OpenSSH_8.1\r\n\0", 0x15)		 = 21 0
write(0x2, "debug1: Local version string SSH-2.0-OpenSSH_8.1\r\n\0", 0x32)		 = 50 0
```


Failed dtruss Trying to write a null/empty our_version.  Can only guess what is happening to that.

```
0x53281:  write(0x2, "OpenSSH_8.1p1, LibreSSL 2.7.3\r\n\0", 0x1F)
0x53281:  write(0x6, "\0", 0x15)		 = -1 Err#41
```

**Comment by 4a6f656c** [comment]
In general, LibreSSL does not perform DNS lookups - I'm going to close this issue, however please feel free to reopen it if you can demonstrate that switching from LibreSSL to OpenSSL is fixing/triggering this (without changing anything else).
