### ISSUE TITLE
crypto/rsa/rsa_oaep.c: memory leak suspected  by gcc12

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#733]
```
/home/ilia/temp/libressl-orig/crypto/rsa/rsa_oaep.c: In function ‘RSA_padding_check_PKCS1_OAEP_mgf1’:
/home/ilia/temp/libressl-orig/crypto/rsa/rsa_oaep.c:221:31: warning: leak of ‘em’ [CWE-401] [-Wanalyzer-malloc-leak]
  221 |         for (from += flen, em += num, i = 0; i < num; i++) {
      |                            ~~~^~~~~~
  ‘RSA_padding_check_PKCS1_OAEP_mgf1’: events 1-13
    |
    |  186 |         if ((mdlen = EVP_MD_size(md)) <= 0)
    |      |            ^
    |      |            |
    |      |            (1) following ‘false’ branch (when ‘mdlen > 0’)...
    |......
    |  189 |         if (tlen <= 0 || flen <= 0)
    |      |            ~~~~~~~~~~
    |      |            |     |
    |      |            |     (2) ...to here
    |      |            (3) following ‘false’ branch...
    |......
    |  200 |         if (num < flen || num < 2 * mdlen + 2) {
    |      |            ~
    |      |            |
    |      |            (4) ...to here
    |      |            (5) following ‘false’ branch...
    |......
    |  205 |         dblen = num - mdlen - 1;
    |      |                 ~~~~~~~~~~~
    |      |                     |
    |      |                     (6) ...to here
    |  206 |         if ((db = malloc(dblen)) == NULL) {
    |      |            ~
    |      |            |
    |      |            (7) following ‘false’ branch (when ‘db’ is non-NULL)...
    |......
    |  210 |         if ((em = malloc(num)) == NULL) {
    |      |            ~      ~~~~~~~~~~~
    |      |            |      |
    |      |            |      (8) ...to here
    |      |            |      (9) allocated here
    |      |            (10) assuming ‘em’ is non-NULL
    |      |            (11) following ‘false’ branch (when ‘em’ is non-NULL)...
    |......
    |  221 |         for (from += flen, em += num, i = 0; i < num; i++) {
    |      |                   ~~       ~~~~~~~~~
    |      |                   |           |
    |      |                   |           (13) ‘em’ leaks here; was allocated at (9)
    |      |                   (12) ...to here
    |
```

**Comment by botovq** [comment]
On Fri, Feb 11, 2022 at 09:57:43PM -0800, Ilya Shipitsin wrote:
>     |......
>     |  210 |         if ((em = malloc(num)) == NULL) {
>     |      |            ~      ~~~~~~~~~~~
>     |      |            |      |
>     |      |            |      (8) ...to here
>     |      |            |      (9) allocated here
>     |      |            (10) assuming ‘em’ is non-NULL
>     |      |            (11) following ‘false’ branch (when ‘em’ is non-NULL)...
>     |......
>     |  221 |         for (from += flen, em += num, i = 0; i < num; i++) {
>     |      |                   ~~       ~~~~~~~~~
>     |      |                   |           |
>     |      |                   |           (13) ‘em’ leaks here; was allocated at (9)
>     |      |                   (12) ...to here
>     |
> ```

No leak here. The loop walks backwards through em and initializes it. It
ends with '*--em = *from & mask;', so after num iterations, em points to
the allocation. Now it would be nicer to use a separate variable for
that, but this code is so hairy that I'm hesitant to diverge from OpenSSL
to silence a static analyzer.

**Comment by chipitsine** [comment]
I'm investigating how gcc12 is useful for quality gates. I'll check whether this issue worth reporting to GCC side (to reduce noise).

Thanks for the review!
