### ISSUE TITLE
LibreSSL's opensslconf.h no-ops __attribute__(...) on Windows with Clang

### ISSUE THREAD

**Issue by nickhutchinson** [libressl-portable/portable#734]
LibreSSL 3.4.2's `openssl/opensslconf.h` header contains the following, which inadvertently defines `__attribute__(a)` to a no-op on Windows when building with Clang.

```cpp
#if defined(_MSC_VER) && !defined(__attribute__)
#define __attribute__(a)
#endif
```

This test is too coarse. On Windows with targeting the MSVC ABI, Clang will define `_MSC_VER`, and does not treat `__attribute__` as a macro. Clang's builtin headers (e.g. `immintrin.h`) use `__attribute__` liberally, and do not expect it to be ifdef-ed away.

I'm not sure what the correct test should be. As a workaround, I'm currently patching `opensslconf.h` in my project to change the test to `defined(_MSC_VER) && !defined(__clang__) && !defined(__attribute__)`. But I suspect there are other compilers (Intel?) that define `_MSC_VER` and would not want libressl to no-op `__attribute__(...)`.

**Comment by kinichiro** [comment]
Hello.
I posted #753 PR as you described above, and I think this will solve your issue.
Could you check if that fixes as you expected ?

**Comment by nickhutchinson** [comment]
> Hello.
> I posted #753 PR as you described above, and I think this will solve your issue.
> Could you check if that fixes as you expected ?

Yes, patching opensslconf.h as per the referenced PR fixes the issue where including libressl's headers when compiling with Clang on Windows results in `__attribute__` being defined away.

**Comment by kinichiro** [comment]
@nickhutchinson PR had merged. Can you close this issue ?
