### ISSUE TITLE
Latest libressl that supports visual studio 2005

### ISSUE THREAD

**Issue by LinArcX** [libressl-portable/portable#738]
Hello. We have a legacy codebase that uses c++98 and visual studio 2005.

My manager decided to use TLS in this code-base. I wanted to know what is the latest version of libressl that supports vistual studio 2005?

EDIT: I know it's insane to use an outdated TLS library. Also outdated c++ version and visual studio. But please let me know what's the latest version of libressl that meet my requirements.

**Comment by busterb** [comment]
Hey @LinArcX, you'd be in a better shape to test than I since I don't keep any Windows compilers that old running. You can probably work backwards from #639 when Vista support was removed.
