### ISSUE TITLE
asan still  fails on explicit bzero

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#739]
https://github.com/libressl-portable/portable/runs/5627098306?check_suite_focus=true#step:3:1716

it should have been suppressed by https://github.com/openbsd/src/commit/aa487188ae3e5285b534ac22067648966572a1a7

more investigation needed ))

**Comment by busterb** [comment]
It seems to be inconsistent as well, e.g. https://github.com/libressl-portable/portable/runs/5686542332?check_suite_focus=true passed right before it failed once that change was merged. I've never seen an ASan test fail locally on Debian 11 either.

**Comment by chipitsine** [comment]
seems, gcc9 is too old, I decided to switch to clang: https://github.com/libressl-portable/portable/pull/741

(another option was to switch to gcc10, for example)

**Comment by busterb** [comment]
The fix seems to have done the trick, thanks @chipitsine
