### ISSUE TITLE
./openbsd/src/lib/libcrypto/armv4cpuid.S: No such file or directory

### ISSUE THREAD

**Issue by vollkommenheit** [libressl-portable/portable#742]
On Intel macOS at least, autogen.sh fails to create `./configure` due to "./openbsd/src/lib/libcrypto/armv4cpuid.S: No such file or directory",

It appears the `update.sh` that `autogen.sh` calls is looking in 
`./openbsd/src/lib/libcrypto/`:
>libcrypto_src=$OPENBSD_SRC/lib/libcrypto
...
$CP $libcrypto_src/armv4cpuid.S crypto
$CP $libcrypto_src/armcap.c crypto
$CP $libcrypto_src/arm_arch.h crypto

while these openbsd files now actually exist in:
`./openbsd/src/lib/libcrypto/arch/arm/`

Not sure if there are more such path discrepancies with upstream in `update.sh`.

**Comment by botovq** [comment]
Should already be fixed by #740

**Comment by vollkommenheit** [comment]
After manually prefixing `arch/arm` to the three lines above in `update.sh`, then it fails at:
>copying libcrypto source
generating arm ASM source for elf
generating x86_64 ASM source for elf
generating x86_64 ASM source for macosx
generating x86_64 ASM source for masm
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
cpp: error trying to exec 'cc1': execvp: No such file or directory
generating x86_64 ASM source for mingw64
copying libtls source
copying nc(1) source
copying ocspcheck(1) source
copying openssl(1) source
copying libssl source
cp: ./openbsd/src/lib/libssl/tls13_buffer.c: No such file or directory

which is traced back to ssl/Makefile.am
>libssl_la_SOURCES += tls13_buffer.c
libssl_la_SOURCES += tls13_client.c
libssl_la_SOURCES += tls13_error.c
libssl_la_SOURCES += tls13_handshake.c
libssl_la_SOURCES += tls13_handshake_msg.c
libssl_la_SOURCES += tls13_key_schedule.c
libssl_la_SOURCES += tls13_key_share.c
libssl_la_SOURCES += tls13_legacy.c
libssl_la_SOURCES += tls13_lib.c
libssl_la_SOURCES += tls13_record.c
libssl_la_SOURCES += tls13_record_layer.c
libssl_la_SOURCES += tls13_server.c

that references `tls13_*` while the upstream openbsd source appear just recently renamed to `tls_*`.

**Comment by vollkommenheit** [comment]
It turns out only two renamed files are affected:
>libssl_la_SOURCES += tls13_buffer.c
...
libssl_la_SOURCES += tls13_key_share.c

Just update to 
>libssl_la_SOURCES += tls_buffer.c
...
libssl_la_SOURCES += tls_key_share.c

**Comment by vollkommenheit** [comment]
Then it's stopped by:

>echo timingsafe_bcmp >> crypto_portable.sym
echo timingsafe_memcmp >> crypto_portable.sym
echo OPENSSL_ia32cap_P >> crypto_portable.sym
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
  CPPAS    aes/libcrypto_la-aes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-bsaes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-vpaes-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-aesni-macosx-x86_64.lo
  CPPAS    aes/libcrypto_la-aesni-sha1-macosx-x86_64.lo
  CPPAS    bn/libcrypto_la-modexp512-macosx-x86_64.lo
  CPPAS    bn/libcrypto_la-mont-macosx-x86_64.lo
  CPPAS    bn/libcrypto_la-mont5-macosx-x86_64.lo
  CPPAS    bn/libcrypto_la-gf2m-macosx-x86_64.lo
  CPPAS    camellia/libcrypto_la-cmll-macosx-x86_64.lo
  CPPAS    md5/libcrypto_la-md5-macosx-x86_64.lo
  CPPAS    modes/libcrypto_la-ghash-macosx-x86_64.lo
  CPPAS    rc4/libcrypto_la-rc4-macosx-x86_64.lo
  CPPAS    rc4/libcrypto_la-rc4-md5-macosx-x86_64.lo
  CPPAS    sha/libcrypto_la-sha1-macosx-x86_64.lo
  CPPAS    sha/libcrypto_la-sha256-macosx-x86_64.lo
  CPPAS    sha/libcrypto_la-sha512-macosx-x86_64.lo
  CPPAS    whrlpool/libcrypto_la-wp-macosx-x86_64.lo
  CPPAS    libcrypto_la-cpuid-macosx-x86_64.lo
  CC       libcrypto_la-cpt_err.lo
  CC       libcrypto_la-cryptlib.lo
  CC       libcrypto_la-crypto_init.lo
  CC       libcrypto_la-crypto_lock.lo
  CC       libcrypto_la-cversion.lo
  CC       libcrypto_la-ex_data.lo
  CC       libcrypto_la-malloc-wrapper.lo
  CC       libcrypto_la-mem_clr.lo
  CC       libcrypto_la-mem_dbg.lo
  CC       libcrypto_la-o_init.lo
  CC       libcrypto_la-o_str.lo
  CC       libcrypto_la-o_time.lo
  CC       aes/libcrypto_la-aes_cfb.lo
  CC       aes/libcrypto_la-aes_ctr.lo
  CC       aes/libcrypto_la-aes_ecb.lo
  CC       aes/libcrypto_la-aes_ige.lo
  CC       aes/libcrypto_la-aes_misc.lo
  CC       aes/libcrypto_la-aes_ofb.lo
  CC       aes/libcrypto_la-aes_wrap.lo
  CC       asn1/libcrypto_la-a_bitstr.lo
make[2]: *** No rule to make target `asn1/a_bool.c', needed by `asn1/libcrypto_la-a_bool.lo'.  Stop.
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1
Making all in crypto
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[2]: *** No rule to make target `asn1/a_bool.c', needed by `asn1/libcrypto_la-a_bool.lo'.  Stop.
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by kinichiro** [comment]
I think it is good to get latest portable build files (update.sh, Makefile.am, CMakeLists.txt, ...) from this repo, rather than edit those files manually.
Source files under the "./openbsd/" are modified sometimes, and portable build files are adjusted to follow changes of "./openbsd".

**Comment by vollkommenheit** [comment]
Looks like my build automation pulling the `master` branch is not pulling down the latest git source from this repo, as I thought it would. Closed.
