### ISSUE TITLE
SHASum changed for release?

### ISSUE THREAD

**Issue by AmarOk1412** [libressl-portable/portable#746]
https://github.com/libressl-portable/openbsd/archive/libressl-v3.4.0.tar.gz recently changed (~3 days ago)

The new shasum is 2501113a87c305fc7a3193cdc786c83cff3a580c14d62779625070f9f70c43f42a478cfada91f710292567f227761e7ec431a5db311f4ecb4b223f1681da3fd0 ; the old one was 1985643cdd9a0b66ce1e4f373d9d666a9bcab9edd8796663a310650faafd74303e6b724a0bb1ff8a7b9e9c93c63a868309a729ec31a4525998ce49ee124b41d9

I don't have a version of the previous archive, so don't know the diff of the two archives

**Comment by busterb** [comment]
Closing this issue.
