### ISSUE TITLE
Support `SSL_CERT_DIR` and `SSL_CERT_FILE` environment variables ?

### ISSUE THREAD

**Issue by abcfy2** [libressl-portable/portable#747]
Like OpenSSL: https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set_default_verify_paths.html

OpenSSL support `SSL_CERT_DIR` and `SSL_CERT_FILE` environment variables to point another cert file.

Would you please support this feature?

Regards.

**Comment by botovq** [comment]
There are no plans to support this feature:

https://man.openbsd.org/X509_LOOKUP_new.3#ENVIRONMENT
https://marc.info/?l=libressl&m=163020042711032&w=2
