### ISSUE TITLE
tls_read() from server works only w TLS 1.2, not with default (1.2 and 1.3)

### ISSUE THREAD

**Issue by ronaaron** [libressl-portable/portable#750]
So I'm trying to integrate libressl  3.5.2, and things almost work.

My particular problem is that connecting to [my server](https://8th-dev.com/) with the default TLS protocols works, but tls_read() returns -2 (and tls_error() returns NULL), which isn't helpful.

If I force TLS 1.2, then reading works fine.

I would have expected that some sort of fallback would work.

**Comment by botovq** [comment]
-2 is TLS_WANT_POLLIN. As the documentation says:

     The tls_read(), tls_write(), tls_handshake(), and tls_close() functions
     also have two special return values:

           TLS_WANT_POLLIN   The underlying read file descriptor needs to be
                             readable in order to continue.
           TLS_WANT_POLLOUT  The underlying write file descriptor needs to be
                             writeable in order to continue.

     In the case of blocking file descriptors, the same function call should
     be repeated immediately.  In the case of non-blocking file descriptors,
     the same function call should be repeated when the required condition has
     been met.

https://man.openbsd.org/tls_read#RETURN_VALUES

TLSv1.2 "works" since there's more back and forth during the handshake.

You may also find this helpful:
https://github.com/bob-beck/libtls

**Comment by ronaaron** [comment]
Thank you, I missed that part of the docs. Excellent, it works now :)
