### ISSUE TITLE
Portable not working on Windows XP SP3 x86

### ISSUE THREAD

**Issue by ujc75573** [libressl-portable/portable#76]
When opening openssl.exe using command prompt, this error shows up: The procedure entry point inet_pton could not be located in the dynamic link library WS2_32.dll.

**Comment by busterb** [comment]
We build with _WIN32_WINNT=0x600, which means LibreSSL currently requires Windows Vista or later. Patches welcome, though keep in mind that Windows XP is no longer supported by Microsoft.

**Comment by busterb** [comment]
We added support in 2.2.1.
