### ISSUE TITLE
Memory leaks after using libressl it in a shared library  

### ISSUE THREAD

**Issue by klux21** [libressl-portable/portable#762]
Valgrind reports a huge amount of memory leaks once I was trying to use libressl for TLS in a shared library that handles encrypted network communication. The reason for this are a lot allocations that happen only once and seem to be related to the implementation of singletons. The problem is that there are no atexit() calls or other ways for freeing the allocated memory on termination.
It's not a big issue for most programs but is a real problem for shared libraries that are loaded and unloaded on demand and this plenty of times and not only just once.
The initialization of the singletons happens on every load of the shared library then and causes memory leaks once it is unloaded .
It would be better to use static variables for that. Those even save memory compared to heap allocations. Another way would be the usage of a cleanup function or atexit for freeing the allocated memory on termination. 
May be you can consider this a little bit in future implementations. For now I need to prevent any unloading of the shared lib after usage but it's a nasty thing to do this because of missing cleanups only. On the other hand I'm really grateful that this library even exists. Thanks for that great work!

**Comment by 4a6f656c** [comment]
`OPENSSL_cleanup()` will be available in our next development release, which you will be able to call if you want to do so (it will not be automated in anyway).

**Comment by klux21** [comment]
That are really great news to me and I guess for a lot of other people too!
Thank you very much for caring about that problem!

**Comment by 4a6f656c** [comment]
This API is available in LibreSSL 3.6.0.
