### ISSUE TITLE
coverity build fails

### ISSUE THREAD

**Issue by chipitsine** [libressl-portable/portable#768]
https://github.com/libressl-portable/portable/runs/6996104673?check_suite_focus=true

![image](https://user-images.githubusercontent.com/2217296/174990010-555d170e-cf3b-4669-8506-001be7dca238.png)

**Comment by botovq** [comment]
Thanks for the report. I have regenerated the failing patches.

**Comment by chipitsine** [comment]
due to my previous experience, I did not set fail on coverity on purpose. coverity sometimes is not stable for several months. no fun to see on everyday failing builds

thus we have "anyway green build" ))
