### ISSUE TITLE
"make check" fails with HP C/aC++ compiler on hpux

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#77]
Hi,

now, "make check" fails with HP C/aC++ compiler on hpux.
it seems that commit https://github.com/libressl-portable/portable/commit/5cf05de18ce848d7579f235758160ee12fcd85a5 causes this issue.

first of all, HP C/aC++ compiler does NOT accept `-Wall` and `-std=gnu99`.

I did like this.

1. modify configure script, replacinig `-mlp64` with `+DD64`.
<pre>
        *hpux*)
                HOST_OS=hpux;
                CFLAGS="$CFLAGS +DD64"
                CPPFLAGS="$CPPFLAGS -D_XOPEN_SOURCE=600 -D__STRICT_ALIGNMENT"
                PLATFORM_LDADD='-lpthread'
</pre>

2. do `make check`
<pre>
# make check
No suffix list.
Making check in crypto
No suffix list.
 /bin/sh ./config.status
config.status: creating Makefile
config.status: creating include/Makefile
config.status: creating include/openssl/Makefile
config.status: creating crypto/Makefile
config.status: creating ssl/Makefile
config.status: creating tls/Makefile
config.status: creating tests/Makefile
config.status: creating apps/Makefile
config.status: creating man/Makefile
config.status: creating libcrypto.pc
config.status: creating libssl.pc
config.status: creating libtls.pc
config.status: creating openssl.pc
config.status: executing depfiles commands
config.status: executing libtool commands
  CC       aes/libcrypto_la-aes_cbc.lo
cc: warning 1913: `./-std=gnu99' does not exist or cannot be read
cc: warning 1913: `./--std=gnu99' does not exist or cannot be read
cc: warning 1913: `./-c' does not exist or cannot be read
cc: warning 1913: `+Maked' does not exist or cannot be read
cc: warning 1913: `./-DPIC' does not exist or cannot be read
cc: warning 1913: `./-o' does not exist or cannot be read
cc: warning 1913: `aes/.libs/libcrypto_la-aes_cbc.o' does not exist or cannot be read
ld: Unrecognized argument: +Maked
Fatal error.
*** Error exit code 1

Stop.
*** Error exit code 1

Stop.
</pre>

Thanks.

**Comment by bcook-r7** [comment]
Hmm, that is the exact opposite of the intent here!

Can you paste the snippet from your config.log file around here
```
configure:13505: checking whether CC supports -Wall
configure:13518: gcc -c -Wall  conftest.c >&5
configure:13518: $? = 0
configure:13519: result: yes
configure:13532: checking whether CC supports --std=gnu99
configure:13545: gcc -c --std=gnu99  conftest.c >&5
configure:13545: $? = 0
configure:13546: result: yes
```

or run 'make check V=1' to show the full command line?

**Comment by busterb** [comment]
I reverted the offending change while we figure out what the problem is.

**Comment by kinichiro** [comment]
config.log is here.
<pre>
...
configure:12969: result: no
configure:12979: checking whether CC supports -Wall
configure:12992: cc -c -Wall  -D_XOPEN_SOURCE=600 -D__STRICT_ALIGNMENT conftest.c >&5
cc: error 1914: bad form for `-W' option
configure:12992: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libressl"
| #define PACKAGE_TARNAME "libressl"
| #define PACKAGE_VERSION "2.2.0"
| #define PACKAGE_STRING "libressl 2.2.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "libressl"
| #define VERSION "2.2.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:12997: result: no
configure:13006: checking whether CC supports --std=gnu99
configure:13019: cc -c --std=gnu99  -D_XOPEN_SOURCE=600 -D__STRICT_ALIGNMENT conftest.c >&5
cc: warning 1913: `./-std=gnu99' does not exist or cannot be read
cc: warning 1913: `./-D_XOPEN_SOURCE=600' does not exist or cannot be read
cc: warning 1913: `./-D__STRICT_ALIGNMENT' does not exist or cannot be read
configure:13019: $? = 0
configure:13020: result: yes
configure:13032: checking if compiling with clang
configure:13049: cc -c -g +DD64   --std=gnu99  -D_XOPEN_SOURCE=600 -D__STRICT_ALIGNMENT conftest.c >&5
cc: warning 1913: `./-std=gnu99' does not exist or cannot be read
cc: warning 1913: `./-D_XOPEN_SOURCE=600' does not exist or cannot be read
cc: warning 1913: `./-D__STRICT_ALIGNMENT' does not exist or cannot be read
"conftest.c", line 29: error #2020: identifier "not" is undefined
        not clang
        ^

1 error detected in the compilation of "conftest.c".
configure:13049: $? = 2
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libressl"
| #define PACKAGE_TARNAME "libressl"
| #define PACKAGE_VERSION "2.2.0"
| #define PACKAGE_STRING "libressl 2.2.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "libressl"
| #define VERSION "2.2.0"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
| #ifndef __clang__
|       not clang
| #endif
|
|   ;
|   return 0;
| }
configure:13056: result: no
configure:13097: checking if cc supports "-fno-strict-overflow"
...
</pre>

**Comment by kinichiro** [comment]
Hi, thanks for your investigation.

HP C/aC++ compiler seems returns 0 on warning, and returns 1 on error.
And I think that option support checking by exit status is difficult.

HP C/aC++ compiler has -W something option.
Then, `-Wall` is treated as "bad form for '-W'" = error, and returns 1.

        # cc -c -Wall  -D_XOPEN_SOURCE=600 -D__STRICT_ALIGNMENT conftest.c
        cc: error 1914: bad form for `-W' option
        # echo $?
        1
        #

HP C/aC++ compiler doesn't accept `--` option, and this case `--std=gnu99` is treated
as file named "./-std=gnu99" to be read by compiler.

        # cc -c --std=gnu99  -D_XOPEN_SOURCE=600 -D__STRICT_ALIGNMENT conftest.c
        cc: warning 1913: `./-std=gnu99' does not exist or cannot be read
        cc: warning 1913: `./-D_XOPEN_SOURCE=600' does not exist or cannot be read
        cc: warning 1913: `./-D__STRICT_ALIGNMENT' does not exist or cannot be read
        # echo $?
        0
        #

It is just my opinion, though,
can we choose CFLAGS by value of CC in configure.ac, like this ?

        *hpux*)
                HOST_OS=hpux;
                if [ $CC = "gcc" ] ; then
                    CFLAGS="$CFLAGS -mlp64"
                else
                    CFLAGS="-g -O2 +DD64"
                fi
                CPPFLAGS="$CPPFLAGS -D_XOPEN_SOURCE=600 -D__STRICT_ALIGNMENT"
                AC_SUBST([PLATFORM_LDADD], ['-lpthread'])
                ;;

Thanks.

**Comment by busterb** [comment]
That sounds right. We currently only need a similar workaround on the IBM compiler, so it makes sense to make the adjustments platform-specific. Thanks!

**Comment by busterb** [comment]
I added the check as you suggested, thanks.
