### ISSUE TITLE
x11vnc build failure - SSL_CTX_set_security_level is missing

### ISSUE THREAD

**Issue by orbea** [libressl-portable/portable#770]
OS: `Gentoo`
x11vnc: https://github.com/LibVNC/x11vnc/commit/7388e4acfa906d2adaf8d0caf036ee1d2059c974
LibreSSL: `3.5.3`

When building x11vnc is fails with undefined references for `SSL_CTX_set_security_level`. This can be easily worked around in x11vnc by disabling it for LibreSSL (https://github.com/LibVNC/x11vnc/pull/202), but is it possible this could be added to LibreSSL in the future?

The OpenSSL documentation is here.

https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html

**Comment by botovq** [comment]
> When building x11vnc is fails with undefined references for
> `SSL_CTX_set_security_level`. This can be easily worked around in
> x11vnc by disabling it for LibreSSL
> (https://github.com/LibVNC/x11vnc/pull/202), but is it possible this
> could be added to LibreSSL in the future?

Unless we find a major issue, it will be available in LibreSSL 3.6
https://github.com/openbsd/src/blob/master/lib/libssl/ssl.h#L1574-L1578

> The OpenSSL documentation is here.
> 
> https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_security_level.html

Yes. Unfortunately, it's much more complicated than what the
documentation suggests...

**Comment by orbea** [comment]
Thank you for the quick response and its fine if this issue is waiting on 3.6.

I was able to remove around 30 packages from the Gentoo LibreSSL overlay after 3.5, thanks for keeping this project usable!
