### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [libressl-portable/portable#775]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-exporter for TLS = 1.3

Thanks in advance.

**Comment by botovq** [comment]
Could you elaborate on what you need from the SSL library beyond
SSL_export_keying_material() [1]? As far as I can tell the RFC only
specifies a label and a context and the exporter should do the rest.

We do not support the extended master secret extension, so this can't
currently be used with TLSv1.2 and lower.

[1]: https://man.openbsd.org/SSL_export_keying_material

**Comment by Neustradamus** [comment]
@botovq: For example, it is in:
- https://github.com/jas4711/gsasl/search?q=tls-exporter
- https://github.com/gnutls/gnutls/search?q=tls-exporter
- https://github.com/GNOME/glib/search?q=tls-exporter&type=commits
- https://github.com/bcgit/bc-java/search?q=tls-exporter
- https://github.com/racket/racket/search?q=tls-exporter
- https://github.com/search?q=user%3Ambhangui+tls-exporter&type=code
- https://github.com/mellium/sasl/search?q=tls-exporter

**Comment by Neustradamus** [comment]
Dear all, @libressl team, @botovq,

I have update the main description about tls-unique, tls-server-end-point, tls-exporter and I have added XEP-0388/XEP-0440/XEP-0474 links.

I think that you have seen the jabber.ru MITM:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

-----------------

There is not an announcement in code: RFC5929 / RFC9266
And I do not find:
- tls-unique
- tls-server-end-point
- tls-exporter

Example GnuTLS:
- tls-unique: https://gitlab.com/search?search=tls-unique&nav_source=navbar&project_id=179611&group_id=121613&search_code=true&repository_ref=master
- tls-exporter: https://gitlab.com/search?search=tls-exporter&nav_source=navbar&project_id=179611&group_id=121613&search_code=true&repository_ref=master
- tls-server-end-point: https://gitlab.com/search?search=tls-server-end-point&nav_source=navbar&project_id=179611&group_id=121613&search_code=true&repository_ref=master
- rfc5929: https://gitlab.com/search?search=rfc5929&nav_source=navbar&project_id=179611&group_id=121613&search_code=true&repository_ref=master
- rfc9266: https://gitlab.com/search?search=rfc9266&nav_source=navbar&project_id=179611&group_id=121613&search_code=true&repository_ref=master

Can you add it?

**Comment by botovq** [comment]
As already mentioned, there is nothing on our side that needs to be done. An application wishing to do SCRAM or GSS-API over SASL can use [SSL_export_keying_material()][1] with the appropriate label and context, as is done [here][2], for example.

[1]: https://man.openbsd.org/SSL_export_keying_material
[2]: https://github.com/Exim/exim/blob/51894f20e0c03113b4c4e07898ac5e955b21ec41/src/src/tls-openssl.c#L3442-L3458
