### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_PKCS12_MAKE_KEYBAG"

### ISSUE THREAD

**Issue by vollkommenheit** [libressl-portable/portable#791]
Last successful build from trunk was Sept. 5th. Since then, I'm getting: 
>  echo OPENSSL_ia32cap_P >> crypto_portable.sym
/usr/bin/make  check-am
...
CCLD     libcompatnoopt.la
  CCLD     libcrypto.la
Undefined symbols for architecture x86_64:
  "_PKCS12_MAKE_KEYBAG", referenced from:
     -exported_symbol[s_list] command line option
  "_PKCS12_MAKE_SHKEYBAG", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcrypto.la] Error 1
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1
start make...
Making all in crypto
/usr/bin/make  all-am
  CCLD     libcrypto.la
Undefined symbols for architecture x86_64:
  "_PKCS12_MAKE_KEYBAG", referenced from:
     -exported_symbol[s_list] command line option
  "_PKCS12_MAKE_SHKEYBAG", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcrypto.la] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by botovq** [comment]
Thanks for the report. I have pushed a fix to openbsd. It will be
available for portable once I sync (will happen in the next couple
hours).

Out of curiosity: What is your environment? Are you using gold as a
linker?
