### ISSUE TITLE
incorrect notBefore and notAfter dates from HTTPS certificates

### ISSUE THREAD

**Issue by koehn** [libressl-portable/portable#796]
When I run LibreSSL to get the dates from a certificate, the notBefore and notAfter dates are today's date and one year from today's date:

```
$ openssl version
LibreSSL 3.3.6
$ openssl s_client -connect mail.koehn.com:443 < /dev/null 2>/dev/null | openssl x509 -dates -noout -in /dev/stdin                           
notBefore=Oct 31 14:08:30 2022 GMT
notAfter=Oct 31 14:08:30 2023 GMT
```

If I run the same command but using `-starttls` on an `imap` or `smtp` server, the dates are correct:
```
$ openssl s_client -connect mail.koehn.com:143 -starttls imap  < /dev/null 2>/dev/null | openssl x509 -dates -noout -in /dev/stdin
notBefore=Sep 28 19:25:08 2022 GMT
notAfter=Dec 27 19:25:07 2022 GMT
```

If I use OpenSSL 3.0.5, the dates are correct for HTTPS certificates:
```
$ /opt/homebrew/opt/openssl@3/bin/openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
$ /opt/homebrew/opt/openssl@3/bin/openssl s_client -connect mail.koehn.com:443 < /dev/null 2>/dev/null | openssl x509 -dates -noout -in /dev/stdin
notBefore=Sep 28 19:25:08 2022 GMT
notAfter=Dec 27 19:25:07 2022 GMT
```

**Comment by koehn** [comment]
Ahh. It's a `-serverName` issue. If I set the `-serverName` LibreSSL works the way OpenSSL does. Not sure if that makes it a bug or not. 

```
$ openssl s_client -servername mail.koehn.com -connect mail.koehn.com:143 -starttls imap  < /dev/null 2>/dev/null | openssl x509 -dates -noout -in /dev/stdin
notBefore=Sep 28 19:25:08 2022 GMT
notAfter=Dec 27 19:25:07 2022 GMT
```

**Comment by botovq** [comment]
On Mon, Oct 31, 2022 at 10:04:53AM -0700, Brad Koehn wrote:
> Ahh. It's a `-serverName` issue. If I set the `-serverName` LibreSSL works the way OpenSSL does. Not sure if that makes it a bug or not. 

We only recently switched to including the SNI in s_client to match
this particular aspect of OpenSSL behavior that has confused people a
lot. This is the case since libressl 3.5:

https://github.com/libressl-portable/openbsd/commit/588880daec7326faa0df6c80a9dbb2a273590940

**Comment by koehn** [comment]
Thanks for the quick response! Closing.
