### ISSUE TITLE
LibreSSL fails to verify alternate chains. 

### ISSUE THREAD

**Issue by DomT4** [libressl-portable/portable#80]
OS X 10.10.3’s release changed some certs in the Keychain. There’s a full list of changes here: https://gist.github.com/DomT4/f86618bdfe2f27c8d66a

This has caused some chaos with OpenSSL and LibreSSL, in things built against them, using a .pem generated from OS X’s Keychains. The biggest, most popular affected sites are the whole range of Google domains.

Google cross-sign their GeoTrust root with an old Equifax root (Equifax Secure Certificate Authority) because a lot of the older clients don’t have the GeoTrust root on their system and would just error out. Have emailed with Adam Langley on the cert errors and essentially Google aren’t going to be able to stop that cross-signing any time soon.

According to Adam most SSL clients should go through the cert chain of the domain and hit the GeoTrust cert and verify at that point, if the GeoTrust root exists in a .pem file LibreSSL can find and use, which does exist when generating a PEM from the system Keychains. It’s not supposed to carry on to the Equifax root, but it is, and this is causing breakage on OS X 10.10.3 onwards.

This problem only exists in OpenSSL and LibreSSL as far as testing goes. It isn’t reproducible with Apple’s Security Framework, or GnuTLS.

Interestingly, Apple have done something to their shipped OpenSSL 0.9.8x to fix the problem - If I build OpenSSL 0.9.8x from source and use it, failure, but if I use the one Apple installs the connection verifies and succeeds. Here’s hoping they’ve punted whatever those changes were upstream to OpenSSL or OpenBSD (For LibreSSL).

This is the error you get:

```
—2015-04-10 16:58:58—  https://google.com/
Resolving google.com… 216.58.210.46, 2a00:1450:4009:800::200e
Connecting to google.com|216.58.210.46|:443… connected.
ERROR: cannot verify google.com’s certificate, issued by ‘CN=Google
Internet Authority G2,O=Google Inc,C=US’:
  Unable to locally verify the issuer’s authority.
To connect to google.com insecurely, use `—no-check-certificate’.
```

How to reproduce:
- Install LibreSSL on OS X 10.10.3 or above. I have it installed to /usr/local/opt/libressl - With the sysconfdir in /usr/local/etc.
- Generate a PEM file from OS X’s Security Keychain:
  - security find-certificate -a -p /Library/Keychains/System.keychain >> sys.pem
  - security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain >> sysroot.pem
  - cat sys.pem >> sysroot.pem
  - mv sysroot.pem /usr/local/etc/libressl
- Download and install cURL:
  - Pass “—with-ssl=/path/to/libressl/dir” and “--with-ca-bundle=/path/to/sysconfdir/libressl/sysroot.pem” to configure.
- Run “/path/to/your/installed/curl -I https://google.com”

It reproduces with wget, mutt, various other tools. If you put the Equifax certificate back, and then certhash, you can make the connection. But the Equifax cert is old, and weak, and Apple aren’t likely to return it to the Keychain. So this problem connecting to Google will persist until the reason for not stopping at and verifying on the GeoTrust root are narrowed down and hopefully fixed.

Mozilla are also pressing ahead with removing that Equifax root from their certs, so it’s not a simple case of working around it by switching PEM.

**Comment by 4a6f656c** [comment]
By default OpenSSL/LibreSSL walks the certificates presented in the bundle first, then once that is finished it attempts to find a trusted root certificate. If that fails, then it fails and does not attempt to find trust on any earlier point in the chain. In this case we get back to Equifax via the chain, then presumably fail to find the trusted root certificate.

From a super quick glance, it looks like enabling the X509_V_FLAG_TRUSTED_FIRST flag would fix/work around this problem since it looks up the trusted certificates at each point in the chain, rather than walking the chain first and then attempting to find a trusted root. I'd be curious to see what the changes are that Apple made in their version of OpenSSL 0.9.8...

**Comment by DomT4** [comment]
Yeah, I guess the problem is that in walking the chain it doesn't loop back to the first root cert in the chain and tries to verify that, and if that fails hops to the next root cert and tries to verify that, and so on? If I'm understanding you correctly there.

> I'd be curious to see what the changes are that Apple made in their version of OpenSSL 0.9.8...

I diffed the headers between Apple-provided 098 and a standard OpenSSL-provided source-installed 098 the other day, which produced some interesting changes. A lot of it is ` DEPRECATED ` warnings to ignore, but there's some interesting changes as well.

**Comment by DomT4** [comment]
If it's useful, OpenSSL added the following commits which fix the issue:

https://github.com/openssl/openssl/commit/6281abc796234
https://github.com/openssl/openssl/commit/dfd3322d72a2

Don't know how the LibreSSL team here feel about those as a solution.

**Comment by twphoenix** [comment]
Hey!

 

Important message, please visit <http://hotelmysliwski.eu/scarcely.php?apvb>

 

rene.l@fictionshare.net



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Smokexyz** [comment]
+1 this

**Comment by Sp1l** [comment]
Hi Joel,

Any progress on this bug? This has become a bigger problem after NSS recently removed some roots from the CA-bundle. 
```
$ openssl s_client -connect www.google.com:443 -verify 3
verify depth is 3
CONNECTED(00000003)
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify error:num=27:certificate not trusted
verify return:1
depth=1 C = US, O = Google Inc, CN = Google Internet Authority G2
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google Inc, CN = www.google.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=www.google.com
   i:/C=US/O=Google Inc/CN=Google Internet Authority G2
 1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
...
    Verify return code: 27 (certificate not trusted)
```

**Comment by bob-beck** [comment]
Yeah, I have some..

I have a big ugly diff ATM that brings in boringssl's x509_verify_cert and
suiteb stuff.

I had to touch safestack.h to do it, so I I will need to take many showers
tonight.

I'll clean it up shortly and post it, maybe get it in soon

With that I get:

$ openssl s_client -connect www.google.com:443 -verify 3
verify depth is 3
CONNECTED(00000003)
depth=3 C = US, O = Equifax, OU = Equifax Secure Certificate Authority
verify return:1
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
verify return:1
depth=1 C = US, O = Google Inc, CN = Google Internet Authority G2
verify return:1
depth=0 C = US, ST = California, L = Mountain View, O = Google Inc, CN =
www.google.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=www.google.com
   i:/C=US/O=Google Inc/CN=Google Internet Authority G2
 1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
   i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
 2 s:/C=US/O=GneoTrust Inc./CN=GeoTrust Global CA
   i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
---

**Comment by bob-beck** [comment]
Fix committed. It will appear in the next portable release.

**Comment by jungle-boogie** [comment]
Just curious, a portable release will occur when openBSD 6.1 is made?
