### ISSUE TITLE
libressl-dev 3.6 could not be installed while openssl-dev 3.0.7 was installed

### ISSUE THREAD

**Issue by M-Arthur** [libressl-portable/portable#804]
We encountered an issue that `libressl-dev` could not be added successfully while `openssl-dev` was installed, shown below.

![image](https://user-images.githubusercontent.com/8305963/205208461-ec3d4f62-9865-4bf1-b932-6901f89cdfcd.png)

**Specifications**
OS: 
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.17.0
PRETTY_NAME="Alpine Linux v3.17"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

libressl-dev: `3.6.1-r0`
openssl-dev: `3.0.7-r0`

Here is some background about why we ended up with this situation.
We want to use libressl. However, one of the libraries we need `rabbitmq-c-dev` has dependency on `openssl-dev` so it will automatically try to install `openssl-dev` whenever we add that library.

---

Please let me know:
- if this is expected behaviour that we have to choose one or another (which was not the case with libressl 3.5)
- if you need more information (I am a newbie in this area not sure what to provide)
- if this issue should be raised to Apline project for help

Thank you very much. I really appreciate your time and help.

**Comment by busterb** [comment]
Hi! There's not much we can do about how a distribution packages a project. The packages are likely incompatible because the headers coexist in the same place on the filesystem. I think you'd need to raise the issue with the package maintainer with Arch linux to get this resolved. Thanks!

**Comment by M-Arthur** [comment]
> Hi! There's not much we can do about how a distribution packages a project. The packages are likely incompatible because the headers coexist in the same place on the filesystem. I think you'd need to raise the issue with the package maintainer with Arch linux to get this resolved. Thanks!

Thank you ver much
