### ISSUE TITLE
encrypted file can be decoded by libreSSL 2.8.3 but not 3.3.6

### ISSUE THREAD

**Issue by ericmnel** [libressl-portable/portable#805]
I am attaching an example file, password is BDE01705DEA8FDA96216E0A376EEA7FC5.  Should decode to a single test directory with a screenshot of a flower.

I have two macs, one running MacOS 12.6 w/ LibreSSL 2.8.3, and one running MacOS 13.0.1 w/ LibreSSL 3.3.6

I use this command to encode:  tar -czf - test | openssl enc -e -aes256 -out test.tar.gz
and this to decode: openssl enc -d -aes256 -in test.tar.gz | tar xz

I can encode and decode fine with LibreSSL 2.8.3, but when I try to decode with LibreSSL 3.3.6 I get this error:

$ openssl enc -d -aes256 -in test.tar.gz | tar xz
enter aes-256-cbc decryption password:
bad decrypt
140704510428352:error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt:/AppleInternal/Library/BuildRoots/810eba08-405a-11ed-86e9-6af958a02716/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/evp/evp_enc.c:549:
tar: Error opening archive: Unrecognized archive format
[test.tar.gz](https://github.com/libressl-portable/portable/files/10178511/test.tar.gz)

**Comment by botovq** [comment]
> I use this command to encode:  tar -czf - test | openssl enc -e -aes256 -out test.tar.gz
> and this to decode: openssl enc -d -aes256 -in test.tar.gz | tar xz

The default message digest was changed from md5 to sha256 sometime in
between these two releases [1]. Try adding `-md md5` to your decrypting
command line:

    openssl enc -md md5 -d -aes256 -in test.tar.gz | tar xz

(in the future better use -md sha256 on the encrypting side on macOS 12.6).


[1]: https://github.com/openbsd/src/commit/d45026d1be92ad4889a625dd876fd4c464393c54

**Comment by ericmnel** [comment]
Thanks!  That worked.
