### ISSUE TITLE
"make check" fails with gcc compiler on hpux

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#81]
Hi,

sorry, again.

now, "make check" fails with gcc compiler on hpux.
commit https://github.com/libressl-portable/portable/commit/dcb97d12a4a6117546e453b455de53beabab7c9f seems to cause this issue.
with HP C/aC++ compiler, "make check" works fine, and it passes all 46 tests.

It seems that `configure` chose bad CFLAGS for gcc.
`+DD64` is option for HP C/aC++ compiler.
<pre>
# make check
No suffix list.
Making check in crypto
  CC       aes/libcrypto_la-aes_cbc.lo
gcc: error: +DD64: No such file or directory
*** Error exit code 1

Stop.
*** Error exit code 1

Stop.
#
</pre>
CFLAGS in Makefile is like this.
<pre>
# grep CFLAGS Makefile
CFLAGS = -g -O2 +DD64    -fno-strict-overflow -D_FORTIFY_SOURCE=2 -Wno-pointer-sign -DHAVE_GNU_STACK
</pre>

I'm afraid that `$CC` variable is not set when `configure` checks 
`if  $CC = "gcc" ; then` (around line 11915 in configure).

Thanks.

**Comment by kinichiro** [comment]
I was trying to add debug print like this.

        *hpux*)
                HOST_OS=hpux;
                echo "===== CC =====> [$CC]"
                if  $CC = "gcc" ; then

Then I got this result.
<pre>
checking whether to build static libraries... yes
===== CC =====> [gcc -std=gnu99]
gcc: error: =: No such file or directory
</pre>

variable CC is not just "gcc" but "gcc -std=gnu99".

Then, I modified `configure` like this.

        *hpux*)
                HOST_OS=hpux;
                if [ "$CC" = "gcc -std=gnu99" ] ; then

This change gives me a good CFLAGS.
<pre>
# grep CFLAGS Makefile
CFLAGS = -g -O2 -Wall -std=gnu99 -mlp64   -fno-strict-overflow -D_FORTIFY_SOURCE=2 -Wno-pointer-sign -DHAVE_GNU_STACK
</pre>

**Comment by busterb** [comment]
I wonder if something like ac_cv_prog_CC would be the right thing to test here? I merged your patch while we ponder that. Thanks!

**Comment by kinichiro** [comment]
Thanks for your quick response.
I have no idea about ac_cv_prog_CC, sorry.
