### ISSUE TITLE
signing by openssl ca command fails on mingw64

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#86]
Hi,

signing by openssl ca command fails on mingw64 environment.
error message is like this.
<pre>
Using configuration from test/openssl.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
countryName           :PRINTABLE:'JP'
stateOrProvinceName   :ASN.1 12:'Tokyo'
organizationName      :ASN.1 12:'TEST_DUMMY_COMPANY'
commonName            :ASN.1 12:'testOCSP.test_dummy.com'
Certificate is to be certified until May 11 13:39:55 2015 GMT (1 days)

Write out database with 1 new entries
unable to rename ./test/testCA/index.txt to ./test/testCA/index.txt.old
reason: File exists
</pre>
`rename()` seems can not overwrite existing file on Windows,
and `MoveFileEx()` with `MOVEFILE_REPLACE_EXISTING` seems solve this issue.

So, I would like to add 1 macro in include/stdio.h that replaces `rename()` to `MoveFileEx()`.
<pre>
...
#ifdef _WIN32
#include <errno.h>
#include <string.h>

static inline void
posix_perror(const char *s)
{
	fprintf(stderr, "%s: %s\n", s, strerror(errno));
}

#define perror(errnum) posix_perror(errnum)
#endif

#ifdef __MINGW32__
#define rename(f,t) (MoveFileEx((f),(t),MOVEFILE_REPLACE_EXISTING) ? 0 : -1)
#endif

#endif
</pre>
This macro does not set suitable `errno`, though, solves the issue.

Here is a test script (renametest.sh) to reproduce this issue.
https://gist.github.com/kinichiro/8414a4ba5905117e631d
place this under tests/, and run it.
This script is only for mingw, because of tricky `-subj` strings.

This script creates 2 CSRs and try to sign 2 times.
1st signing succeeds, but 2nd fails.

Thanks.

**Comment by kinichiro** [comment]
This issue does not affect to cygwin64.

**Comment by busterb** [comment]
The fix here required some refactoring, since we don't want to pull in the headers for MoveFileEx into stdio.h. That slowed down the build dramatically, and caused a number of compilation errors. b4a6a615134b59435efbecdd8c5b5407b6af8e8f

Thanks!

**Comment by kinichiro** [comment]
I could confirm this issue is fixed with current HEAD.
Thanks.
