### ISSUE TITLE
BIO_get_accept_socket() is confused by AF_INET vs AF_INET6

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#87]
Hi,

On Windows, OCSP Server seems to refuse connection from OCSP query sender.
I tested this with mingw64, cygwin64 and Windows command prompt with libressl-2.1.6-windows.zip.

OCSP-server log is here.

<pre>
../apps/openssl.exe ocsp -index test/testCA/index.txt -CA test/testCA/ca_cert.pem \
-CAfile test/testCA/ca_cert.pem -rsigner test/testOCSP/ocsp_cert.pem \
-rkey test/testOCSP/private/ocsp_key.pem -port 8888 -nrequest 1
Waiting for OCSP client connections...
</pre>

OCSP-query-sender got error messages like this.

<pre>
../apps/openssl.exe ocsp -issuer test/testCA/ca_cert.pem -cert test/server/server_cert.pem \
-cert test/server/revoke_cert.pem -CAfile test/testCA/ca_cert.pem \
-url http://localhost:8888 -resp_text -respout test/user1/ocsp_qry.der
Error connecting BIO
Error querying OCSP responder
3762521490:error:0200206B:system library:connect:Connection refused:bio/bss_conn.c:246:host=localhost:8888
3762521490:error:20073067:BIO routines:CONN_STATE:connect error:bio/bss_conn.c:250:
</pre>

This test succeeds on BSD5.6, CentOS7(x86_64), Solaris11(i386) and HP-UX11i(11.31).
And, OCSP-query-sender on mingw64/cygwin64 is able to communicate with OCSP-Server on linux.

Thanks

**Comment by kinichiro** [comment]
`getaddrinfo()` seems to provide default to IPv6 info on Windows,
then `-port 8888` binds IPv6 port `[::]:8888` on Windows.

I've read `BIO_get_accept_socket()` in crypto/bio/b_sock.c,
and found that `-port *:8888` could bind IPv4 port `0.0.0.0:8888`.

Then, OCSP-query-sender could communicate with OCSP-server by `-url http://localhost:8888`.

**Comment by twphoenix** [comment]
Hey!

 

Important message, please visit <http://omsspartanburg.com/use.php?iz>

 

rene.l@fictionshare.net

**Comment by bob-beck** [comment]
Kinichiro - Brent - where are we with this one? have recent OCSP changes changed this behaviour?

**Comment by kinichiro** [comment]
This issue is not about OCSP, 
it is about socket and ipv4/v6 on Windows.
I encountered this while testing ocsp responder on Windows, then subject contains OCSP.

This issue still remains.
If `openssl ocsp -port 8888 ...` on Windows, responder gets socket [::]:8888 and it doesn't accept connection from client by ipv4 style.

s_server always gets ipv4 socket if I use -accept port option.
s_server doesn't use BIO API to obtain socket, and ocsp does.

I can't tell this is a bug or specification of original openssl on Windows.

**Comment by busterb** [comment]
You're right @kinichiro , it's because of how BIO_get_accept_socket is implemented, it only specifies ai_family if you specify a host, otherwise it uses the OS's default, which is IPv6 in this case.

We could rationalize it across platforms with a patch like this to use IPv4 if nothing is specified:
```
--- a/src/lib/libssl/src/crypto/bio/b_sock.c
+++ b/src/lib/libssl/src/crypto/bio/b_sock.c
@@ -259,7 +259,8 @@ BIO_get_accept_socket(char *host, int bind_mode)
                                hint.ai_family = AF_INET;
                                h = NULL;
                        }
-               }
+               } else
+                       hint.ai_family = AF_INET;
 
                if (getaddrinfo(h, p, &hint, &res))
                        break;
```

**Comment by busterb** [comment]
It would be nice if the tool used the same mechanism for opening sockets though!

**Comment by 4a6f656c** [comment]
The real issue here is that BIO_get_accept_socket() does AF_INET6 or platform specified AF lookups, but then forces AF_INET when doing the socket/accept. The quick fix is to force AF_INET lookups since it currently is IPv4-only code. Longer term this code really needs to be rewritten to be AF agnostic (or deleted).

**Comment by bob-beck** [comment]
Oh look. a big steamy pile to roll in.

**Comment by 4a6f656c** [comment]
This should be resolved via a large clean up/rewrite of BIO_get_accept_socket() in r1.64 of lib/libcrypto/bio/b_sock.c.

**Comment by bob-beck** [comment]
https://github.com/openbsd/src/commit/aec66ea57867559762ba9f15729725e84de8915d
