### ISSUE TITLE
tests/testenc.sh fails on mingw64 environment

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#88]
Hi,

`tests/testenc.sh` fails on mingw64 environment.
<pre>
$ ./testenc.sh
cat
WARNING: can't open config file: /etc/ssl/openssl.cnf
WARNING: can't open config file: /etc/ssl/openssl.cnf
p p.clear differ: char 62, line 1
</pre>
But, it succeeds on cygwin64.

This issue is same as https://github.com/libressl-portable/portable/issues/79#issuecomment-93628872

Thanks.

**Comment by busterb** [comment]
Thanks, this required a combination of 8eec2f485a9aa4adda7fec46b15771b29c3ac9ee and b239fc25fcde7ec6f305fff290bc762d14397d15 to solve. testenc.sh now passes on mingw64

**Comment by kinichiro** [comment]
I confirmed testenc.sh succeeded with current HEAD.
Thanks.
