### ISSUE TITLE
UNIX_STD=2003 is needed when compiling with C/aC++ compiler on HP-UX

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#90]
`export UNIX_STD=2003` is needed when compiling with C/aC++ compiler on HP-UX.
If this environment variable is not set, some function does not work properly.

for example, `vsnprintf()` returns always -1 if maxsize is smaller than length of formatted string.
`vsnprintf()` is used in `crypto/compat/bsd-asprintf.c` and it can't process more than 128 bytes string.
this causes bad influence on `BIO_printf()`.

man page of `standards(5)` gives an information about UNIX conformance mode of HP-UX.

so, build process should be like this.
<pre>
$ export UNIX_STD=2003
$ ./configure
$ make check
</pre>

I would like to include `export UNIX_STD=2003` in Makefile, but I have no idea how to do it, now.

this is not needed with GCC compiler on HP-UX.

**Comment by busterb** [comment]
I didn't see a clear way to set a global environment variable either. Is there a flag you can specify to the compiler instead?

**Comment by kinichiro** [comment]
No.
Here is `standards(5)` man page, and it says 
`Both a feature test macro and an environment variable must be defined while compiling`
http://h20565.www2.hp.com/hpsc/doc/public/display?docId=emr_na-c02271540

But, it is OK, this environment variable is needed only when using HP C/aC++ compiler only.
This issue does not affect to GCC.
I'll keep in mind while compiling with C/aC++ compiler.

Thanks.

**Comment by kinichiro** [comment]
Would you like to mention about this in README like this, and close this issue ?

<pre>
...

OS specific informations:

 - HP-UX (11i)

    "export UNIX_STD=2003" is needed for HP C/aC++ compiler before "configure" and "make check".
    You can see more details about this by "standards(5)" man page.

...
</pre>

**Comment by busterb** [comment]
Done, thanks.
