### ISSUE TITLE
Problem connecting to hotmail POP3 server

### ISSUE THREAD

**Issue by Luiji** [libressl-portable/portable#91]
This might not be a bug on LibreSSL's part as much as a compatibility issue (e.g. unsupported something), but I don't know how to determine the root cause of the problem. The issue reported by the `openssl` utility on connecting to `pop3.live.com:995` is rather generic (snippet follows). `live.com:443` is just connection refused (but doing that through a browser works) and `hotmail.com:443` works perfectly fine.

OpenSSL's `openssl` also gets connection refused on `live.com:443`, however *it works perfectly fine with* `pop3.live.com:995`.

~~~
$ openssl s_client -connect pop3.live.com:995 
CONNECTED(00000003)
13952162230332:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/usr/src/lib/libssl/ssl/../../libssl/src/ssl/s23_lib.c:124:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 320 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
$ echo ';-;'
~~~

If I missed something obvious... sorry. ;-;

**Comment by kinichiro** [comment]
Hi,
this is not an answer, but with `-tls1` option LibreSSL's s_client can connect successfully to pop3.live.com:995.
<pre>
$ apps/openssl.exe s_client -connect pop3.live.com:995 -tls1
WARNING: can't open config file: /etc/ssl/openssl.cnf
CONNECTED(00000003)
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Organization Validation CA - G2
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/CN=*.hotmail.com
   i:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - G2
 1 s:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - G2
   i:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFQjCCBCqgAwIBAgISESHl0vjrML7zKmGlv42YL75vMA0GCSqGSIb3DQEBBQUA
MF0xCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMTMwMQYD
VQQDEypHbG9iYWxTaWduIE9yZ2FuaXphdGlvbiBWYWxpZGF0aW9uIENBIC0gRzIw
HhcNMTMwNDI0MjAzNTA5WhcNMTYwNDI0MjAzNTA5WjBsMQswCQYDVQQGEwJVUzET
MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
TWljcm9zb2Z0IENvcnBvcmF0aW9uMRYwFAYDVQQDDA0qLmhvdG1haWwuY29tMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAumSiBWrzHZf6WFP5a/j4+K7D
1izLoYKj5Omll0pdxKvKcBRDf+iaIkCbSOPNpx2uWGZdwNwkabYCQavaBf2ebwmS
S8i1CJpHflO+k0qYd5WUi7sSsZ3+6RaCMdLoDIPGyYMQuy7TFtVO7LSt5+qscyyi
ET8c3lE2aj/XW13UZvRrV65ZJvMjUtwaDnIcAxGeasYoebLsKdqHQ2uTr4PmNwCc
viGVFSOzkGAoC0PfyqKB2xUWy3Kc5zRI2xvUW8Jb2b/9Ze3g55pIUzKsjpglkQTm
edVPSYYPGNz6Kl/ZshBXdBAk398q1JkSmUaTMa2hJgBbcC+73ax40AJDGJlz+QID
AQABo4IB6zCCAecwDgYDVR0PAQH/BAQDAgWgMEkGA1UdIARCMEAwPgYGZ4EMAQIC
MDQwMgYIKwYBBQUHAgEWJmh0dHBzOi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9z
aXRvcnkvMEAGA1UdEQQ5MDeCDSouaG90bWFpbC5jb22CCioubGl2ZS5jb22CDSou
b3V0bG9vay5jb22CC2hvdG1haWwuY29tMAkGA1UdEwQCMAAwHQYDVR0lBBYwFAYI
KwYBBQUHAwEGCCsGAQUFBwMCMEUGA1UdHwQ+MDwwOqA4oDaGNGh0dHA6Ly9jcmwu
Z2xvYmFsc2lnbi5jb20vZ3MvZ3Nvcmdhbml6YXRpb252YWxnMi5jcmwwgZYGCCsG
AQUFBwEBBIGJMIGGMEcGCCsGAQUFBzAChjtodHRwOi8vc2VjdXJlLmdsb2JhbHNp
Z24uY29tL2NhY2VydC9nc29yZ2FuaXphdGlvbnZhbGcyLmNydDA7BggrBgEFBQcw
AYYvaHR0cDovL29jc3AyLmdsb2JhbHNpZ24uY29tL2dzb3JnYW5pemF0aW9udmFs
ZzIwHQYDVR0OBBYEFHbgHqTLsXDt7uMRyE62rnDEfLn9MB8GA1UdIwQYMBaAFF1G
so3ES3Qcu+31c7Y6tziPdZ5+MA0GCSqGSIb3DQEBBQUAA4IBAQByy1+3N6ZRVooI
xqw8Ng+UFz0g7UHkbPEnvTu1uxJ2AojFuP/P1PAk+/6uMRvpPlWg/5uqmOIWxKxJ
Lo6xSbkDf4LN+KYwes3XSuPyziZ4QbPnehHhZ0377iiA8fpRJADg9NWKCRHh5aAd
e9QvJUW/GgYkBN+F4yYc2jIjR3Rehv4JYOKS3iXO9OoHsDS2CcCFaS2imgQVfYLg
slBwT/A08PCOhW5huiluSmih7x5Qf7sFDv8jineu6ehKzi8pKnOq4k8G4QiWn38Y
CeiBkkwFOwj7T3M/ITiiSS9DHDGeokj16eBi83Zx3YYiJ9YZvnQ+4GvqJ5eJJ6pR
KKvemr+m
-----END CERTIFICATE-----
subject=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/CN=*.hotmail.com
issuer=/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - G2
---
No client certificate CA names sent
---
SSL handshake has read 2663 bytes and written 514 bytes
---
New, TLSv1/SSLv3, Cipher is RC4-MD5
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : RC4-MD5
    Session-ID: 0B220000AA3455D59CC78699901D56865C30C3C36C14CC283A7BE764BA98A587
    Session-ID-ctx:
    Master-Key: 3061D9390FBC53FD890F5B9D3DA33CA498365125071B337315559CF012E178489170E7FF64B43AC61F3896D1DCB2721F
    Start Time: 1432655576
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
+OK dub0-pop621 POP3 server ready
Q
DONE
$
</pre>
Is this help ?

**Comment by Luiji** [comment]
@kinichiro Actually that does help. The reason this came up as a problem for me was fetchmail failing, so if I can find the equivalent of `-tls1` in the C API then I should be able to tweak fetchmail to work.

It's still odd that LibreSSL requires this, though. Perhaps it's more strict during the handshaking process? (Would make sense given its MO.)

**Comment by 4a6f656c** [comment]
The equivalent in code is to use the TLSv1_client_method() function (instead of SSLv23_client_method() or similar) - you can probably trigger the same behaviour by disabling TLSv1.2 by setting the SSL_OP_NO_TLSv1_2 option:

  SSL_CTX_set_options(ctx->ssl_ctx, SSL_OP_NO_TLSv1_2);

The actual problem appears to be an interoperability issue at the remote end - with older LibreSSL/OpenSSL it falls back to TLSv1 with RC4-MD5 and disabling ECDHE ciphers also results in the same behaviour with current LibreSSL:

$ openssl s_client -connect pop3.live.com:995 -cipher ALL:!ECDHE

There are a number of things that it may be choking on...

**Comment by 4a6f656c** [comment]
I'd almost be certain that the remote end is failing to handle a larger ClientHello message - using ciphers ALL:!CAMELLIA works (total 77 cipher suites), ALL:!DHE works (total 68 cipher suites), but using ALL:!GOST fails (total 93 cipher suites)...

**Comment by 4a6f656c** [comment]
Looks like this has been resolved at the server end:

$ openssl s_client -connect pop3.live.com:995
[...]
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1
    Cipher    : ECDHE-RSA-AES256-SHA
[...]
---
+OK DUB006-POP93 POP3 server ready
QUIT
DONE
