### ISSUE TITLE
Look at OCSP_basic_verify fixes for curl

### ISSUE THREAD

**Issue by busterb** [libressl-portable/portable#92]
from Daniel Stenberg daniel@haxx.se via openbsd.org:

>OpenSSL fixed OCSP_basic_verify() in this commit:
>
>https://git.openssl.org/gitweb/?p=openssl.git;a=commit;h=4ca5efc2874e094d6382b30416824eda6dde52fe
>
>This leaves us with this funky #ifdef line to make sure we use the necessary work around-for libressl and older OpenSSL versions:
>
>https://github.com/bagder/curl/blob/master/lib/vtls/openssl.c#L1363
>
>Thanks for all your work. When do you end up fixing this, it will be interesting to get a version define or something to improve this #ifdef with!

**Comment by kinichiro** [comment]
This issue seems same as https://github.com/libressl-portable/openbsd/issues/45

And commit https://github.com/libressl-portable/openbsd/commit/bb8fc331f0ceb44405979dd11333f9de2b665641 will solve that.

**Comment by busterb** [comment]
Thanks!
