### ISSUE TITLE
generating and parsing DER format on mingw64

### ISSUE THREAD

**Issue by kinichiro** [libressl-portable/portable#94]
Hi,

it seems that generating and parsing DER format on mingw64 has a problem.

I wrote test script `ca-spkac.sh`.
https://gist.github.com/kinichiro/caef4b22bed0a5039adc

place this under tests/, and run it, this script tries to 
generate DER format certificate and convert it from DER to PEM and parse DER.
this succeeds on cygwin64, but fails on mingw64.

generating invalid DER seems caused by coverting all `0x0a(LF)` in DER to `0x0d(CR) 0x0a(LF)`.

next I copied correct generated certificate from cygwin64 environment.
and run `x509` command and `asn1parse` command by hand on mingw64, results are like this.
<pre>
$ ../apps/openssl.exe x509 -in test_ca_spkac/server/spkac.cert -inform DER -outform PEM
unable to load certificate
2587050918:error:0D06B08E:asn1 encoding routines:ASN1_D2I_READ_BIO:not enough data:asn1/a_d2i_fp.c:238:

$ ../apps/openssl.exe asn1parse -inform DER -in test_ca_spkac/server/spkac.cert
Error in encoding
2682857868:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:asn1/asn1_lib.c:144:
</pre>

**Comment by busterb** [comment]
Thanks for the report. The fix required modifying openssl.exe to use stdin/stdout in binary mode. 1d27b22e82ce00d27d0886c8488e4cbed1cb618e

**Comment by kinichiro** [comment]
Thanks, I could see this issue was fixed with current HEAD.
