### ISSUE TITLE
Location (default) of openssl.cnf on OSX 10.10.x

### ISSUE THREAD

**Issue by danielshaw** [libressl-portable/portable#95]
Successfully compiled latest from Github on OSX 10.10.3:

$ /usr/local/bin/openssl version
WARNING: can't open config file: /etc/ssl/openssl.cnf
LibreSSL 2.2.0

As above, version is 2.2.0, but note the warning. It's defaulting to look for an openssl.cnf in /etc/ssl/ - My guess is that this is a fallback default from other *nix systems.

However, on my Yosemite install: $PATH makes openssl from MacPorts the default for terminal:
$ /opt/local/bin/openssl version
OpenSSL 1.0.2a 19 Mar 2015

This version has it's .cnf at:
 /opt/local/etc/openssl/openssl.cnf

The original OSX version is also of course still there:
$ /usr/bin/openssl version
OpenSSL 0.9.8zd 8 Jan 2015

But this version has it's config file here:
/System/Library/OpenSSL/openssl.cnf

So, therefore, in order of preference/importance, installation on OSX should, in my opinion:
1. If OSX is detected, make the fall-back default as /System/Library/OpenSSL/openssl.cnf
2. Nice to have would be to have ./configure logic to look for MacPorts / Brew installed versions in common locations /opt/local and /usr/local 
3. Possibly warn also during configure/build if no .cnf is found in expected or default locations, and allow a --openssl-etc= (or similar) option to ./configure so that it can be specified manually.

Finally, with a view to LibreSSL being a 100% drop-in replacement with no dependence on a pre-existing OpenSSL being there already: Why not, if no existing openssl.cnf is found, install a default one into /$prefix/etc/ssl/ ?

**Comment by busterb** [comment]
Try setting the '--with-openssldir' configure option.

Auto-detecting is not a bad idea though, or at least using $prefix

**Comment by busterb** [comment]
#107 is a start toward implementing this - there's still a permissions bug to sort out running the 'make dist' test.

**Comment by busterb** [comment]
It seems that simply dropping an openssl.cnf into the installation directory is sufficient here.

Then, if you want to use one that already exists, specify the directory with --with-openssldir. I'd rather not embed OS-specific logic for all the places where there might be an openssl.cnf file, but make it a user option. The patch in #107 tries to ensure it doesn't overwrite a file it did not install or that has been modified since it was installed.

**Comment by busterb** [comment]
#107 is now landed - can you let me know if that is a sufficient fix for this?

**Comment by busterb** [comment]
Since we now install a workable set of defaults into into sysconfdir, and this can also be configured by the user to point elsewhere, I'm going to close this. Thanks!
